### ISSUE TITLE
[FR] Lock Widget into header

### ISSUE THREAD

**Issue by Baumtreter** [dwainscheeren/dwains-lovelace-dashboard#100]
Is it possible to integrate the lock into the header besides the Cover, light and sensor status? Would be great if a press would toggle the lock immediately without going into the entity itself. In case of multiple locks a pop-up would be great which shows the locks. A direct toggle there would be great too.

**Comment by dwainscheeren** [comment]
Will look into this for 1.4.0

**Comment by dwainscheeren** [comment]
This is fixed in 2.0
