### ISSUE TITLE
Only Climate is shown on the "Devices" tab

### ISSUE THREAD

**Issue by Backslashh** [dwainscheeren/dwains-lovelace-dashboard#111]
In the Devices tab, under the "Temperature" section, only devices classed as Climate will show. 
I'd like to have temperature from my temperature sensors as well show up here and not just the devices from the climate domain.

Would also be nice to have the temperatures plotted on a graph card showing temperature from outside and then the temperatures for each room in the house (or wherever temp sensors are)

**Comment by davidkmcgowan** [comment]
guess you could loop through sensor and look for device_class temperature and show those as well

**Comment by dwainscheeren** [comment]
Will look into this for 1.4.0
