### ISSUE TITLE
[FR] Add support for TADO water_heater.water

### ISSUE THREAD

**Issue by Diondk** [dwainscheeren/dwains-lovelace-dashboard#112]
Hi,

since a few weeks tado water has been change from climate.water to water_heater.water. 
And when i added the water_heater.water to the climate entity in the room it gives an error.

Specify an entity from within the climate domain.

Can you please make the water_heater also available in your theme?

Thanks :)

Kind Regards,
Dion

**Comment by dwainscheeren** [comment]
Will look into this for 1.4.0

**Comment by Flight777** [comment]
Second this request! 👍

**Comment by dwainscheeren** [comment]
This will be possible in DD 3.0.
