### ISSUE TITLE
[FR] Climate / Thermostat control add up/down arrows

### ISSUE THREAD

**Issue by dkmcgowan** [dwainscheeren/dwains-lovelace-dashboard#113]
This might be someone else module, if so I will move this or close it, but it would be nice if the up/down arrows were on the main page, the slider is hard to use and you have to hit the 3 dots, entity details, then use the arrows to be precise

**Comment by mase60** [comment]
i think using [`custom:`simple-thermostat](https://github.com/nervetattoo/simple-thermostat) would be a nice alternative

**Comment by dwainscheeren** [comment]
Will look into this.
