### ISSUE TITLE
[FR] Under More, House Data, Sensors, add groupings

### ISSUE THREAD

**Issue by dkmcgowan** [dwainscheeren/dwains-lovelace-dashboard#114]
It would be nice to have these sensors grouped by device_class, so show all the door sensors together, window sensors, temperature sensors, etc...  Just a heading and organization and UX thing

**Comment by dwainscheeren** [comment]
Will look into this, need to redesign that page anyway.

**Comment by dwainscheeren** [comment]
Grouping them is almost impossible. I made some changes with the help of some contributors here to the sensors in Dwains Dashboard 2.0, please look at it when its released and open a new issue if you are not satisfied.
