### ISSUE TITLE
[FR] Time format option

### ISSUE THREAD

**Issue by dkmcgowan** [dwainscheeren/dwains-lovelace-dashboard#115]
If I missed this in documentation I'm sorry and close this, but it would be nice to be able to display the Home activity data in AM/PM format and not just military time, sorry, I'm from US and we do time stupid

**Comment by dwainscheeren** [comment]
This is not possible right now, I will look into this for a next version of Dwains Theme and report here back when its fixed :)

**Comment by dwainscheeren** [comment]
I changed the time of the sensors in house information to ... seconds ago in DD 2.0. So this is sort of fixed.
