### ISSUE TITLE
[FR]Option to hide person form homepage if away

### ISSUE THREAD

**Issue by Backslashh** [dwainscheeren/dwains-lovelace-dashboard#116]
I would like to be able to dynamically update the Persons section of the home page but only for certain people.

For example, I want to track the permanent residents of my house all the time (know if they are at home or away, etc) but there are some regular guests that I would like to show on the homepage if they are at my house or not.

Maybe an option in the person config like `hide_if away: true` or something to hide the people you don't want on the homepage all the time?

**Comment by dwainscheeren** [comment]
Will look into this for 1.4.0
