### ISSUE TITLE
[FR] new room's item -> gate 

### ISSUE THREAD

**Issue by ciechompl** [dwainscheeren/dwains-lovelace-dashboard#133]
We have windows, doors etc why not to have gates ? :) I know tiny thing but should be easy to implement :)  

e.g. in garage I have doors but also garage gate .... 
in "room" garden :) I have 2 gates and 1 wicket so would also great to see a difference in UI 

priority low but would be nice to have :)

**Comment by dwainscheeren** [comment]
#22

**Comment by ciechompl** [comment]
> #22

this is not the same I'm thinking about ... i only would like to see the gates are opened on the same way as windows or doors but not under non of those categories ... simply need new "gate" category with own icon in UI.

**Comment by dwainscheeren** [comment]
Do you also want to seperate gate then from a garagedoor? A gate is then a lock?

**Comment by ciechompl** [comment]
the only issue which came to my mind just now is the fakt that in majority of the cases sensor showing status of the gate (open closed) is separated from the switch which opening the gate. Usually switch is turned "on" only for a second to initiate opening. So integration would need to have 2 entities to be provided by users ... one for state and the other one for click action ... doable ? :)

**Comment by ciechompl** [comment]
> Do you also want to seperate gate then from a garagedoor? A gate is then a lock?

at least for me gate is a gate :) ... it can be main gate to my property or garage door ... no issue :) 

i also use lock (main doors) and should not be mixed with gates .. .simply different purpose and i believe should be separated (via graphical symbol) and the way how we use it (see previous post)

**Comment by dwainscheeren** [comment]
I would put the gates in doors
