### ISSUE TITLE
[FR] Text stretching across card entity in Web Browser and Mobile. 

### ISSUE THREAD

**Issue by LoneWalkerWolf** [dwainscheeren/dwains-lovelace-dashboard#138]
On mobile (android) and desktop, the text in many of the button cards, such as temperature do not fit in the button card. 
![image](https://user-images.githubusercontent.com/63847434/84241054-d591cb80-aaf6-11ea-8fd1-987cc74796c8.png)
There is a lot of space to fit the whole text, and if it would be possible to have the text wrap around to another line.

**Comment by dwainscheeren** [comment]
This is fixed in Dwains Dashboard 2.0
