### ISSUE TITLE
[FR] Local Weather Data from own sensors

### ISSUE THREAD

**Issue by marcokitzmann** [dwainscheeren/dwains-lovelace-dashboard#140]
Currently the Weather Card only takes into account my own sensor data for temperature and air humidity. It would be great if I could also use my other locally collected weather data (air pressure, wind, rain, etc.) as a source of the Weather Card. Only where there is no self generated data (e.g. weather forecast), external weather data should be used.

**Comment by Edhall1044** [comment]
I would like this feature also.
