### ISSUE TITLE
[BUG] Devices > "Lights" icon

### ISSUE THREAD

**Issue by kbrigitta** [dwainscheeren/dwains-lovelace-dashboard#149]
Hi,
I noticed this when I was exploring the theme. When navigating to "Devices" (next to "Rooms" on the homepage), the icon for "Lights" is the icon that is used for "light_off" under the Global icons.
So even if there are lights turned on, the icon remains "light_off"

**Comment by ciechompl** [comment]
I noticed that when changed icons in icons.yaml to: 
```
icons:
    light_on: 'mdi:lightbulb-on'
    light_off: 'mdi:lightbulb-outline'
```
icons are replaced on main screen but not on the "All lights" list. 
not a big issue but simply lack of consequence :)

**Comment by ciechompl** [comment]
could be also handy if we could have an option to have icons for single bulb lights and for multiple lights (group) 

single: 
![image](https://user-images.githubusercontent.com/27088154/85153033-faecab00-b255-11ea-9844-f706ade5fc09.png)
group: 
![image](https://user-images.githubusercontent.com/27088154/85153066-08099a00-b256-11ea-8ef1-47c4dba5fc19.png)

**Comment by dwainscheeren** [comment]
If you have light group used as light in a room you mean @ciechompl ?

**Comment by dwainscheeren** [comment]
If you read this and you mean a light group icon if a light entity is a group then I maybe can make that, please make a new FR for that then :) @ciechompl
