### ISSUE TITLE
[FR] Addons on scene and camara pages

### ISSUE THREAD

**Issue by ciechompl** [dwainscheeren/dwains-lovelace-dashboard#150]
It would be very handy to add addons on scene and camara pages.
On camaras page I would like to add e.g. buttons for PZT control or switch which initiate recording.
On scene page I would like to add my quick switches (input_boolean) which trigers some automation e.g. vacation time -> when on set all devices to holiday mode, when off set all devices back to normal; "guests" -> set special lights and set air system to full speed etc. and when off back to normal. 

Scene tab is a perfect place for this :) as here we have also some other things which a let's say general for entire house. 

Sure, this can be done via scenes but at least for me it is more handy to have a switch and see in which "mode" my house is at the moment ,further only one item is needed instead of 2 scenes.

**Comment by dwainscheeren** [comment]
Will look into this :). You know you can use an input_boolean as a scene on the scene page?

**Comment by ciechompl** [comment]
> You know you can use an input_boolean as a scene on the scene page?

ohh I didn't know that :) added :) partially covers my request :) 
The only improvement would be to allow custom "name" to be used ... even if I added parameter name in config i see original entity name on the tab.

**Comment by dwainscheeren** [comment]
You also tried renaming with customize.yaml from HA self? Then I need to look into that one.

**Comment by ciechompl** [comment]
no ... just wanted to rename it in scenes.yaml -> into very short name fitting button on scenes page.
Renaming in  customize.yaml I'm using for different places in my UI ... simply I was thinking that "name" parameter in any config in your theme would be handy to adjust names just for theme without touching other places. Anyway . this is not a priority I think :)

**Comment by ciechompl** [comment]
anyway .. PZT buttons on camera page would be nice to have :)

**Comment by dwainscheeren** [comment]
In Dwains Dashboard 2.0 the scenes and camera page will be optional. You can duplicate the camera page as an more page addon and put that in the main nav.
