### ISSUE TITLE
[FR] Show covers that are not fully open

### ISSUE THREAD

**Issue by patman15** [dwainscheeren/dwains-lovelace-dashboard#158]
Hi!

I have the issue that my awning is sensitive to wind. So I wanted to get notified if it is in use. There is this nice "covers" icon on the homepage showing all `open` covers. 
![cover](https://user-images.githubusercontent.com/14628713/86044222-1ae84f80-ba4a-11ea-8a1c-f992b5cdd525.png)
The problem is my awning is always shown `open` until it is fully expanded where it is `closed`. Since I wanted it to be shown only when it is not fully retracted (99%-0%) I made a patch to the cover state file: [cover.patch.txt](https://github.com/dwainscheeren/lovelace-dwains-theme/files/4847353/cover.patch.txt)
With that you can have a config option `show_covers` in the global.yaml which allows you to select which covers you get notified about:
- `open` (default): backwards compatible option to show all covers that have a position 100%-1% (=state `open`)
- `partly_closed`: show all covers that have a position 99%-0%
- `closed`: show all covers that have a position 0% (=state `closed`)

Also I patched the icon to adapt to the selected cover option.
@dwainscheeren, if there is interest, I could complete the patch with the device/room views, the documentation, and do a pull request?

**Comment by Xetoxyc** [comment]
I would like to see this. Just create a pull request for this. If u don't like to create it I can do it for you.

**Comment by patman15** [comment]
@Xetoxyc I'll do my best to create a pull request, if I run into troubles I would appreciate your help. Thanks!

**Comment by patman15** [comment]
@Xetoxyc can you instruct me on how to fix the documentation? I do not know what to clone, I can only find the code. Thanks!

**Comment by dwainscheeren** [comment]
Added it in 2.0

**Comment by patman15** [comment]
Hi @dwainscheeren!
Thanks for integrating this into 2.0 but you missed the part of the patch for the homepage. I just tried it out, it works correctly for the header but not for the `devices` tab on the homepage.

**Comment by patman15** [comment]
It's stale because I'm waiting for 3.0 to fix it there (hopefully I'll have the time then). No point in fixing it in 2.x now.
