### ISSUE TITLE
[FR] - Support for multiple thermostats in 1 room

### ISSUE THREAD

**Issue by MRobi1** [dwainscheeren/dwains-lovelace-dashboard#159]
I have a combination of Daikin mini splits and Sinope baseboard thermostats. I have several rooms (at least 4) in the house that have multiple thermostats in them. I've created a thermostat group for those rooms (Example: group.living_room_thermostats has Daikin mini split plus 2 Sinope baseboard thermostats). 

I'd like to see Climate support groups just as lighting does. As-is I can currently only add 1 thermostat per room. If I use a group, when I click on the thermostat group in the theme I get a card error

**Comment by dwainscheeren** [comment]
This will be possible in DD 3.0.
