### ISSUE TITLE
[BUG] Automower Vacuum Cleaner

### ISSUE THREAD

**Issue by MRobi1** [dwainscheeren/dwains-lovelace-dashboard#161]
I have a Husqvarna Automower which gets integrated into HA as a vacuum cleaner. Even when parked, the theme shows the vacuum as "on". I assume the theme looks for "Docked" as a vacuum state and if it's not docked it shows as on.

The states for this integration are:
Error
Charging
Cutting
Cutting (manual timer override)
Leaving charging station
Paused
Parked due to timer
Parked due to weather timer
Parked manually
Going to charging station
Starting...
Stopping...
Preparing to park...
Hatch opened
Stopped but not on base
Off

**Comment by dwainscheeren** [comment]
Now if a vacuum doesn't have the state docked it must be on. Maybe I can add some states like `off` `charging` ?

**Comment by MRobi1** [comment]
Would it be possible to have a feature for vacuums similar to safety_ok_strings where we could define the state of a running vacuum? Or define a state of a docked vacuum? This would solve the issue of automowers always showing as a running vacuum

**Comment by dschraven** [comment]
> Now if a vacuum doesn't have the state docked it must be on. Maybe I can add some states like `off` `charging` ?

Yes please. As my Eufy vacuum has state 'off' when docked, and 'cleaning' when cleaning (obviously). Noticed states like 'error' and 'returning'. But at this point the vacuum icon in the header is always showing. I think the easy fix would be adding 'off', but in the long run the suggested fix from MRobi1 would be more valuable.

**Comment by MRobi1** [comment]
> > Now if a vacuum doesn't have the state docked it must be on. Maybe I can add some states like `off` `charging` ?
> 
> Yes please. As my Eufy vacuum has state 'off' when docked, and 'cleaning' when cleaning (obviously). Noticed states like 'error' and 'returning'. But at this point the vacuum icon in the header is always showing. I think the easy fix would be adding 'off', but in the long run the suggested fix from MRobi1 would be more valuable.

I've gotten around this by editing these 2 files within the dwains-dashboard custom component folder.
lovelace/plugins/button-card-templates/homepage/header/states/vacuum.yaml
lovelace/views/mains/01.homepage.yaml

Find "var onVacuums = 0;" and below it you'll see the if statement used to determine if it's running or not. By default if the state is not "docked" then it's assumed to be running. You can just add another statement there to make it be if it's not docked && not off then assume it's running. 

This doesn't persist through an update so you need to modify it each time. Ideally, the ability to define either docked or running states like the safety_of_strings allows would be the perfect solution, but I'm sure that's a fair amount of work to do and having just docked likely supports 80% of the vacuums out there.
