### ISSUE TITLE
[FR] same popup of room entities also for page entities

### ISSUE THREAD

**Issue by flonair** [dwainscheeren/dwains-lovelace-dashboard#163]
Once i asked in dicord if there is a way to set the popups of the room entities (right one on the pic)) also  for the page entities (left one). This should come with 1.4.0. Did I not find this feature yet?

If it has not been implemented yet, I would like to see it in a future release. :-)

![page entity](https://user-images.githubusercontent.com/60264693/86441736-f8d22400-bd0c-11ea-9803-20339c0312ab.png)

**Comment by dwainscheeren** [comment]
This is fixed in 2.0
