### ISSUE TITLE
[FR] Fans displayed similarly as lights/motion/doors/windows

### ISSUE THREAD

**Issue by deahte** [dwainscheeren/dwains-lovelace-dashboard#179]
Dwains, really cool theme for HA.  Thanks for all the time you spent on putting this together.  

I was hoping to have my fans display the same as how the lights/motion/doors/windows are throughout the interface.  Being able to see which ones were on in each room on the main screen displays, the notification header displays the number of them on, etc.  

I have 5 ceiling fans and a whole house fan (I run this more than HVAC to save costs) and it would be helpful to be displayed as frequent and actionable as those other entities.

It could be that I'm just so used to seeing them in my previous interface, that I think I need them displayed in that way.  I can live with having them display with device: in each room if need be, I just thought I would submit a FR if it was of interest to you and the community.

Thanks in advance.

**Comment by Brausmith** [comment]
I too would like to see fans added so they can be seen at a glance which ones are on.
I live in a climate where ceiling fans are used 80% of the year, and there is a ceiling fan in every room of my house.

**Comment by antonoal** [comment]
I’ve got an extractor in both of my bathrooms which kick in via Shelly 1 when humidity goes up, and I’d also like to see them as fans when they kick in.

**Comment by prjcarr** [comment]
Would love to see this also. Is there any way to add these icons similar to how lights are displayed through out? It would be great to see "3 fans on".

**Comment by simbesh** [comment]
add another request for fans being added as a native room device 👍

**Comment by snowchaser75** [comment]
+1 for fans

**Comment by bartdorsey** [comment]
+1 again for fans. It would be nice not to have to click through to see the status of the fans.

**Comment by Edhall1044** [comment]
I would like this feature also.
