### ISSUE TITLE
Put lights page cards in a single column

### ISSUE THREAD

**Issue by MikeTheCleric** [dwainscheeren/dwains-lovelace-dashboard#180]
Hi! I've got a problem. I need to put in a single column the lights of each room. Is it possible? Thanks in advice.

![Annotazione_2020-08-04_151408](https://user-images.githubusercontent.com/52752310/89318708-6e6c3f80-d67f-11ea-9deb-1e11bcd2a274.png)

**Comment by dwainscheeren** [comment]
How do you mean?

**Comment by MikeTheCleric** [comment]
Hi! I mean that every room's panel needs to be on a single column. For example in the previous image the panels "Cucina" e "Salotto" under the room "Living" should be:
___
Cucina
___
Salotto
___

I don't know if I explained the problem.

Thanks for the patience

**Comment by dwainscheeren** [comment]
So all 1 columns under a room instead of 50/50% columns if you have more then 1 light in a room?

**Comment by MikeTheCleric** [comment]
Exactly.

**Comment by dwainscheeren** [comment]
I disabled the 2 columns functionality in Dwains Dashboard 2.0 so it will be all single columns for the lights.
