### ISSUE TITLE
[BUG] Strange Popup

### ISSUE THREAD

**Issue by groft389** [dwainscheeren/dwains-lovelace-dashboard#183]
Hey,

I have a little problem with my pop-ups. Since recently a button appears there, but has no function. In addition, I can not press the individual objects within the pop-up to see more detailed information. Here's a little video of what I mean exactly:
https://streamable.com/ask8xq
Is that normal or did it ruin some update?

**Comment by dwainscheeren** [comment]
This is a bug in the latest more info card. I'm working on it

**Comment by dwainscheeren** [comment]
Fixed in 2.0
