### ISSUE TITLE
Theme's colors of original menu system

### ISSUE THREAD

**Issue by rirofal** [dwainscheeren/dwains-lovelace-dashboard#199]
When activating one of the color themes the normal menusystem is really hard to see on a mobile device.

Can you keep the themes active only on the Dwains-pages and keep the original theme on the menu system etc.

**Comment by dwainscheeren** [comment]
Will look into this, I know HA made some changes to theme color functionality

**Comment by dwainscheeren** [comment]
This is fixed in 2.0 there my theme colors are only applied to the dashboard itself and not outside of it!
