### ISSUE TITLE
HACS Missing Card-mod

### ISSUE THREAD

**Issue by NVader2000** [dwainscheeren/dwains-lovelace-dashboard#207]
I am sorry but I am new to HA. The install for this plugin/component is not straight forward and I am having difficulties understanding what needs to be done to get this to work. None of the verbiage matches the current version of HA ( 0.115.6). So, if you could provide a step-by-step (screenshot) install that would be appreciated.

**Comment by NVader2000** [comment]
Ok, made some progress here. However, in Step 3 I am not finding all the reference files and folders. "ui-lovelace.yaml" does not exists under the 'config' share of my HA install via Samban or does "dwains-theme/configs-samples"

https://dwainscheeren.github.io/lovelace-dwains-theme/getting-started/installation.html

**Comment by dwainscheeren** [comment]
Did you installed the Discord software on your pc or in webbrowser?

**Comment by NVader2000** [comment]
Yup, did that as well. The reCAPITCA keeps cycling through even though I am selecting the correct images.

**Comment by NVader2000** [comment]
Started from nothing again and got the Dwains Theme on the left pane showing up. However, I am getting the following error when I select the Dwains Theme.

Custom element doesn't exist: mod-card.

Please advise

**Comment by NVader2000** [comment]
Ok so I went through the instructions one more time and noticed that 'card-mod' is missing in HACS. According to your instructions I should find this under the HACS> Frontend. Nope 'card-mod' is not there. This will explain the error.

Please advise

**Comment by NVader2000** [comment]
Re-naming my post. Card-mod was the final and only issue. Card-mod is not included in the HACS for some reason and I had to install it manually from here, https://github.com/thomasloven/hass-config/wiki/Lovelace-Plugins. After this Dwains Theme is now working. Now that is out of the way do you have any instructions on how to use your theme?

**Comment by dwainscheeren** [comment]
This will be fixed in 1.5
