### ISSUE TITLE
Advanced vacuum cleaner theme

### ISSUE THREAD

**Issue by Chrisiesmit93** [dwainscheeren/dwains-lovelace-dashboard#208]
I have your theme in dark setting, but I don't see the bottom text for example at the advanced vacuum cleaner page.

See attached example:
![cleaner](https://user-images.githubusercontent.com/44810057/95116466-5e3c1380-0747-11eb-839e-63b2c69babfc.PNG)

**Comment by dwainscheeren** [comment]
This is fixed in 2.0
