### ISSUE TITLE
[FR] Add device state Drying, Washing, Running

### ISSUE THREAD

**Issue by RubenDijk** [dwainscheeren/dwains-lovelace-dashboard#209]
Add device state with Drying, Washing, Running.

So that it also shows in the homepage that the device is on.

![image](https://user-images.githubusercontent.com/18540436/95124790-3dc68600-0754-11eb-84c1-8ed2b45547fe.png)

there are 2 smartplugs "On" and the wasing machine and dryer with the state "drying" and "washing" i use "running" for the 
dishwasher 
![image](https://user-images.githubusercontent.com/18540436/95125723-af530400-0755-11eb-989e-bce2b0ab765e.png)

**Comment by AalianKhan** [comment]
If you are saying to show separate badges on the home page for each of your machines, this will less than ideal as badges on the homepage are just to show if something is on for example, are there any lights on? are there any devices on? If you want more information on what's on you can click it and it will show all of your devices to see which one is on and off.

**Comment by RubenDijk** [comment]
First do you use Dwains Dashboard? Then you know ther are no badges in the home page.
You can add device's to rooms. The devices that have the status "ON" are displayed in the home page.
My washer and dryer for example have no status "ON" but status "washing" and "drying". This status I would like to see added so that they are also shown as devices as being enabled.

**Comment by AalianKhan** [comment]
Sorry if I stepped on the wrong foot.
Now time to clear some things up
Yes, I do use the dashboard and I referred to the badges to the header states (that's what Dwain calls them). 
Before I understood that you want to make a special head state for your washer and dryer that displays running, washing etc instead of on.
Now I understand that your washer, dryer etc don't show in the header states at all. If that's true, then can you rename the issue to "add custom device on and off states" as in your case these devices have custom on-off states.

**Comment by RubenDijk** [comment]
Add the states Drying and Washing to custom_components\dwains_dashboard\lovelace\plugins\button-cards-templates\homepage\header\states\device.yaml

            //This room has only 1 device
              if(states['{{ room["device"] }}'] && states['{{ room["device"] }}'].state == 'on') {
                onDevices++;
              }
              if(states['{{ room["device"] }}'] && states['{{ room["device"] }}'].state == 'Drying') {
                onDevices++;
              }
              if(states['{{ room["device"] }}'] && states['{{ room["device"] }}'].state == 'Washing') {
                onDevices++;
              }
            {% else %}
            //This room has group of Devices
              if(states['{{ room["device"] }}']){
                states['{{ room["device"] }}'].attributes['entity_id'].forEach(function(entity){
                  if(states[entity] && states[entity].state == 'on'){
                    onDevices++;
                  }
                  if(states[entity] && states[entity].state == 'Drying'){
                    onDevices++;
                  }
                  if(states[entity] && states[entity].state == 'Washing'){
                    onDevices++;
                  }
