### ISSUE TITLE
[FR] Support covers with no position control

### ISSUE THREAD

**Issue by groft389** [dwainscheeren/dwains-lovelace-dashboard#213]
Heyy,

I just installed a new Cover with a Shelly 2.5 as the cover is kinda specific positioning control won't work. I disabled it in the Shelly and added it to Home Assistant (Which have no position slider, so there is a detection for that). Sadly the Dwains Dashboard still wants positions for the cover, but only open stop and close are supported.
Maybe instead of doing a slider for covers like this you could use this: (From Shelly Interface )
![Shelly OpenClosePause](https://user-images.githubusercontent.com/17033125/96338337-8869cb80-108d-11eb-8a44-8d8d9ada1f0a.PNG)

**Comment by dwainscheeren** [comment]
This will be fixed in 1.5 :) see #147

**Comment by groft389** [comment]
Cool :) Thank you ^^
Will it be still a slider or normal buttons then ?

**Comment by dwainscheeren** [comment]
Depends on how your entity works. But currently there is a bug in my dashboard that prevents the correct loading of the buttons.

**Comment by groft389** [comment]
Well which information do you need ?
Normal cover without a slider just open close and stop 
![Unbenannt](https://user-images.githubusercontent.com/17033125/96344847-983bdc80-109a-11eb-80cb-5801b9787b13.PNG)
The Position slider is greyed out

**Comment by dwainscheeren** [comment]
And what do you see in my dashboard when you go to the cover?

**Comment by groft389** [comment]
> And what do you see in my dashboard when you go to the cover?

![Unbenannt2](https://user-images.githubusercontent.com/17033125/96345741-e4871c80-109a-11eb-925d-51034afadb8b.PNG)
![Unbenannt3](https://user-images.githubusercontent.com/17033125/96345749-e51fb300-109a-11eb-9ce0-90a3276b1a8d.PNG)

**Comment by dwainscheeren** [comment]
Ah yeah that will be fixed.

If you want you can try.
Go to www/dwains-theme/plugins/dwains-cover-card/ open dwains-cover-card.js replace all the content of that file with the content of this: https://raw.githubusercontent.com/dwainscheeren/lovelace-dwains-theme/1.5/www/dwains-theme/plugins/dwains-cover-card/dwains-cover-card.js

**Comment by dwainscheeren** [comment]
Also do a HA reboot and a fully browser cache clear ( ctrl + f5 )

**Comment by groft389** [comment]
Ok did it :)
![Unbenannt4](https://user-images.githubusercontent.com/17033125/96346347-99213e00-109b-11eb-9dc4-f18ee17fb87b.PNG)

**Comment by groft389** [comment]
Thank you for the quick respone :)
Ohhh and for 1.5 I think the design I mentioned earlier would fit very well
in the Dashboard, I know you said you currently have problems with your buttons but
just for the future ^^

**Comment by groft389** [comment]
Oh just one more thing I got up with.
As the cover do not support position control.
Home Assistant doesn't even know if it is open or closed.
So I always have the icon for an open cover in the main header:
![Screenshot 2020-10-18 122801](https://user-images.githubusercontent.com/17033125/96364909-62036900-113d-11eb-9997-88e778703115.png)
Maybe this is already fixed with the other stuff. Just thought I'd mention it.
