### ISSUE TITLE
Custom Header no longer supported

### ISSUE THREAD

**Issue by Lukejb14** [dwainscheeren/dwains-lovelace-dashboard#214]
Custom Header HACS frontend has been removed from HACS.

**Comment by Tom051276** [comment]
Where can I get tthis Custom Header without HACS ?

**Comment by dwainscheeren** [comment]
https://github.com/maykar/custom-header

**Comment by trungkienpvt** [comment]
Hi @dwainscheeren I use your theme for my Hass, version 0.116.4. It's wonderful theme and many thank you for sharing it for community. But I have small issue with theme on homepage like image  https://prnt.sc/van965, and it seemed happen on chrome. If you have solution to fix it, please share to me know. Thank you bro so much.

**Comment by dsbaars** [comment]
If you are trying to manually install Custom Header from that repository, you have to put the js file in `/config/www/community/custom-header`.

**Comment by dwainscheeren** [comment]
This will be fixed in 2.0, for now you need to install custom header by hand, put the js file as explained by @dsbaars in the folder `/config/www/community/custom-header`

**Comment by trungkienpvt** [comment]
Many thank @dwainscheeren @dsbaars for your supporting. It work perfect for me ^^
