### ISSUE TITLE
Padding for vacuum and "more info" not correct

### ISSUE THREAD

**Issue by tristanXme** [dwainscheeren/dwains-lovelace-dashboard#215]
Hi,

the padding for the .card-content for the vacuum and more info is not correct.

So you should change:

`dwains-theme\views\popups\more-info.yaml`

From:
`        style: |
          .card-header {
            display: none;
          }`
To:
`        style: |
          .card-header {
            display: none;
          }
          .card-content {
          padding-top: 20px;
          }`

And also:
`dwains-theme\views\main\rooms\room\vacuum.yaml`

From:
`                style: |
                  .card-header {
                    display: none;
                  }`

To:
`                style: |
                  .card-header {
                    display: none;
                  }
                  .card-content {
                    padding-top: 24px;
                  }`

As I'm new to github, I'm, sorry for not commiting a Pull Request, but currently I don't know how to do so :D

**Comment by tristanXme** [comment]
I also noticed, that when the dark theme is enabled, the "find my vacuum" and the "start vacuum" toolbar right under the map and the filters etc. is a dark grey on a black background. That also should be fixed - sadly I did not find out how or better said where to change it in the theme without editing the integration directly.

**Comment by dwainscheeren** [comment]
This is patched in 2.0
