### ISSUE TITLE
Wrong Background-Color in dark & black theme

### ISSUE THREAD

**Issue by tristanXme** [dwainscheeren/dwains-lovelace-dashboard#216]
Hello,

in the dark theme, there is a wrong background-color defined.

in: 
`themes\dwains-theme-dark.yaml`
and
`themes\dwains-theme-black.yaml`

`  primary-color: 'var(--dwains-theme-names)'`
must be:
`  primary-color: 'var(--dwains-theme-header-background)'`

If this is not changed, for example the vacuum card isn't "readable" as the font and background color is somekind of white.

**Comment by dwainscheeren** [comment]
Thanks, fixed it in 2.0
