### ISSUE TITLE
duplicate menu names

### ISSUE THREAD

**Issue by emile-bodin** [dwainscheeren/dwains-lovelace-dashboard#217]
Hi, 

first of all, this is a awesome theme!

I do have some issues/questions
While configuring I noticed that some menu items have suplicate names.

"covers", 1 opens the covers page (which has no entries, the other one opens the "all lights" page
![image](https://user-images.githubusercontent.com/2363359/97639993-063fb680-1a40-11eb-8146-f6a994d6c7ea.png)

same goes for "house information" 1 opens the information as per house_information.yaml and the other opens a page without content
![image](https://user-images.githubusercontent.com/2363359/97640175-7fd7a480-1a40-11eb-956f-d21ce70a32f5.png)

I cleared my cache, restarted home-assitent, reloaded config files, nothing seems to help here.

btw, is there also a way to disable menu items, like plants and locks? none of the pages have configured items in my config.

thanks

**Comment by dwainscheeren** [comment]
This is normally fixed by Custom Header. But that plugin is deprecated. It will be fixed in Dwains Dashboard 2.0 which will be released soon.
