### ISSUE TITLE
Issue hiding labels on cameras

### ISSUE THREAD

**Issue by Adouken** [dwainscheeren/dwains-lovelace-dashboard#224]
I have just upgraded to 2.0 and was initially having issues I figured out that it was the camera.yaml that was the problem. My old yaml looked like this: 

`cameras:
  - entity: camera.back_garden
    show_name: false
    show_state: false
    type: picture-entity
  - entity: camera.front_door
    show_name: false
    show_state: false
    type: picture-entity`

Now it seems that the new version doesn't support anything other than just stating the entity. Is it possible to hide the name and state in the new version?

**Comment by dwainscheeren** [comment]
That code has never worked. Because `show_name` and `show_state` is not supported in any version of dwains dashboard.

**Comment by MRobi1** [comment]
This would be a nice feature to have. My camera streams already display the name, date and time. Being able to hide name and state would just make a little less text clutter on the camera stream.
