### ISSUE TITLE
Global: Inside Temperature isn't shown

### ISSUE THREAD

**Issue by TobiasKneidl** [dwainscheeren/dwains-lovelace-dashboard#225]
Hi,

if I define inside_temperature in global.yaml, I can't see any changes after config reload in the dashboard.

Neither if I define a sensor, nor if I define a climate entity. 

Where should the inside temperature be shown in the dashboard? :D

I'm using the version 2.0 with a fresh install.

**Comment by dwainscheeren** [comment]
inside_temperature is not used yet, its only there for future use.

**Comment by TobiasKneidl** [comment]
Oh okay :D

Maybe there should be a hint here, I reinstalled twice until i gave up and opened the bug here :D https://dwainscheeren.github.io/dwains-lovelace-dashboard/configuration/global.html

Anyways: Aweseome work with this Dashboard, thank you!!
