### ISSUE TITLE
No rooms defined

### ISSUE THREAD

**Issue by oleg-78** [dwainscheeren/dwains-lovelace-dashboard#227]
Hello, Dwain.
Home Assistant 0.118.0
Hass.io
Raspbian GNU/Linux 10 (buster)
Docker version 19.03.12
I am trying to install dashboard V2.0.0. I modifying the file in the /usr/share/hassio/homeassistant/custom_components/dwains_dashboard/configs/rooms.yaml folder. I add rooms, but nothing changes. I tried refreshing the page, also restarting the dwains_dashboard.reload service. But nothing changes. Tried reinstalling dashboard. On the home page inscription - "No rooms defined". What could be the problem? 

The logs say:
2020-11-19 08:24:47 ERROR (MainThread) [frontend.js.latest.202011112] https://XXXX.duckdns.org:8123/dwains-dashboard/home 0 0 Uncaught
2020-11-19 10:56:06 ERROR (MainThread) [frontend.js.latest.202011112] https://XXXX.duckdns.org:8123/dwains_dashboard/js/dwains-dashboard.js:90:13520 Uncaught TypeError: Cannot read property 'popup_cards' of undefined
Best regards,
Oleg.
![Безымянный-1](https://user-images.githubusercontent.com/25502019/99756372-d0f22a00-2b0e-11eb-928d-aa475f5b369e.jpg)

**Comment by dwainscheeren** [comment]
You need to adjust the files in `dwains-dashboard/configs/` its in your main ha folder. Don't touch anything inside the custom_component/dwains_dashboard.

**Comment by Tokn59** [comment]
I have the same issue .. My rooms.yaml includes:

rooms:
  - name: Hallway
    icon: fas:key
    light: light.shelly_shbduo_1_6640a0
    temperature: sensor.co2box_temperature
    motion: binary_sensor.hallway_sensor_motion
    media_player: media_player.serre
  - name: Woonkamer
    icon: mdi:key
    light: light.shelly_shbduo_1_6640a0
    temperature: sensor.co2box_temperature
    motion: binary_sensor.konnected_6ff0a7_zone_2

Yet nothing is shown ...

**Comment by dwainscheeren** [comment]
Make sure you are editing the right file, try a HA reboot after changing the file and see it it makes any changes.
