### ISSUE TITLE
HA selected theme light mode

### ISSUE THREAD

**Issue by TobiasKneidl** [dwainscheeren/dwains-lovelace-dashboard#228]
The integrated light and dark mode of the dashboard are working.

But if in the integration options the theme is set to "HA selected theme" and the HA theme is set to "light", the icons and the background in the dashboard are both white, so not visible.

**Comment by umutcelebi** [comment]
Any update?

**Comment by SteLu1803** [comment]
Same problem here. With Option "HA selected theme" and HA light theme or even dwains light theme, room icons are white and therefore not visible.

**Comment by dwainscheeren** [comment]
2.0.5 fixes this issue. Please set ha theme to backend selected
