### ISSUE TITLE
Cannot find the hello-room example pages?

### ISSUE THREAD

**Issue by Flight777** [dwainscheeren/dwains-lovelace-dashboard#234]
As the title says. the documentation ofter refers to hello-room example yaml pages for the add-ons, but I'm not able to find them? Is it me? :)

**Comment by jpeletier** [comment]
Looks like it disappeared in v2.0. Check v1.5: https://github.com/dwainscheeren/dwains-lovelace-dashboard/tree/1.5/dwains-theme/addons/rooms/hello-room
