### ISSUE TITLE
[FR] All Batteries - Climate is missing

### ISSUE THREAD

**Issue by WolfsWelpe** [dwainscheeren/dwains-lovelace-dashboard#236]
Hey,

Just a little thing in the All Batteries tab there is missing my climates ?
Is there already a way to add these in the all batteries tab, they are already integrated in my rooms so idk
why it doesn't show up there.
![image](https://user-images.githubusercontent.com/17033125/101529508-ef6e7700-3990-11eb-8b69-4351fbb0d28f.png)

**Comment by roblandry** [comment]
You may need to create template sensors to pull the battery_level. You may also need to assign the battery device_type to the sensor.

**Comment by WolfsWelpe** [comment]
Thank you :D
Why didn't I think of that, 
I will give it a try ^^
Have a nice morning/day/evening whenever you are reading this

**Comment by dwainscheeren** [comment]
This will be possible in DD 3.0.
