### ISSUE TITLE
Idea for notifications: Home Feed card?

### ISSUE THREAD

**Issue by Flight777** [dwainscheeren/dwains-lovelace-dashboard#237]
While I like the current notification system, it requires to set-up alot of automations for sensors that potentially already give the correct data at the right time. Would a implementation of a "home feed" like card, as the add-on below, not be more versatile and easier to control for the notifications? :)

https://github.com/gadgetchnnel/lovelace-home-feed-card

Just an idea, no criticism!

**Comment by jaburges** [comment]
why dont you just add the home feed card to your layout? 

I actually use it on my tablets (you can either use a more_page_addon) or just create a button for it (but you'll need to NOT use the default button in a room as it will be too small, so replicate the button card template and edit its size)
