### ISSUE TITLE
[FR] Agent DVR support

### ISSUE THREAD

**Issue by noorbertt** [dwainscheeren/dwains-lovelace-dashboard#251]
Hello

Maybe can you add Agent DVR support please? There is a integration for HA but would be nice a good card

**Comment by jaburges** [comment]
Its unlikely as this is quite a unique scenario - are you on the discord chat - would be good to see how many people would use this and whether its worth the time (as there is already a Camera card and Camera page which supports all types of cameras)

**Comment by AalianKhan** [comment]
it will be better if you create a custom room using the room addon and put your agent DVR card in there.

**Comment by dwainscheeren** [comment]
I also would recommend to create a custom more page for this and enable it for the main nav
