### ISSUE TITLE
Custom element doesn't exist: dwains-wrapper-card.

### ISSUE THREAD

**Issue by parente89** [dwainscheeren/dwains-lovelace-dashboard#257]
After updating the theme, it presents this error:
Custom element doesn't exist: dwains-wrapper-card.

I cleaned the cache but it doesn't work

**Comment by AalianKhan** [comment]
I had that error too but cleaning the cache and rebooting fixed the problem for me

**Comment by dwainscheeren** [comment]
Try indeed a reboot and cache reset. Make 100% sure you reset your browser cache.

**Comment by parente89** [comment]
> Try indeed a reboot and cache reset. Make 100% sure you reset your browser cache.

@dwainscheeren I tried to do everything really. I'm so sorry I can't use the theme, I'm stuck

**Comment by jaedesignz** [comment]
@parente89 as @dwainscheeren said you need to reset your cache on your browser. Log in using the incognito mode, if it works that means some how your not clearing your cache properly. Just saying... Also check if your not blocking unpkg.com if your using pihole or adguard etc..

**Comment by parente89** [comment]
@jaedesignz Thanks, I have already tried both in incognito mode and other browsers from other PCs.  But it does not work.  I don't have ads blocking software etc installed

**Comment by fhwi93ne** [comment]
I have the same issue. I made 100% sure to clean my browser cache, rebooted a couple of times. It is the same on every device I use. Browser or iOS App, the custom cards are missing somehow. Do you have any advice?

**Comment by jok0** [comment]
I am oddly getting this on the iPad app and safari.  I have cleaned the cache, deleted the app - everything.  Still getting this error.  Anyone had this?

The dashboard is working from my PC browser.

**Comment by WolfsWelpe** [comment]
@jok0 May you try a new browser or the same browser in incognito mode? Cause it worked for me as long as I used the same browser cause the dwains-wrapper-card was still in my cache. After trying it in incognito mode, new browser or on the phone it stopped working. 

When I open the dashboard with the cached dwains-wrapper-card it also looks weird tho:
![Screenshot_1](https://user-images.githubusercontent.com/17033125/140200593-3b982dff-1bd4-4c50-918a-94cafc0e9f92.png)

**Comment by WolfsWelpe** [comment]
By the way this error happened to me just after upgrading to 2021.11.0
