### ISSUE TITLE
Feature Request - HACS compatibility

### ISSUE THREAD

**Issue by bsfaxi** [dwainscheeren/dwains-lovelace-dashboard#258]
Hi Dwain,
Is it possible to make this repository "HACS compliant", so it can be imported/updated directly from HA?
Thanks in advance for your great support.
Bilel

**Comment by dwainscheeren** [comment]
When its good version 2.0.1 is hacs compatible. If you wanna try it out.

**Comment by bsfaxi** [comment]
> When its good version 2.0.1 is hacs compatible. If you wanna try it out.

Indeed, It works with category "Integrations".
My bad, I tried it with category "Lovelace".
Thanks. :)

**Comment by dwainscheeren** [comment]
Awesome :) I will prepare an officiel hacs support soon! Also check out https://github.com/hacs/default/pull/698
