### ISSUE TITLE
[FR] Botton current temperature and set temperature

### ISSUE THREAD

**Issue by tantararin** [dwainscheeren/dwains-lovelace-dashboard#259]
Hello:
First of all my congratulations for such a good job. I wanted to make an interesting proposal to you.
I have installed your dashboard to manage my small hotel. I have individualized thermostats in each room and I think it would be interesting if, apart from the botton showing the current room temperature, the selected set temperature would appear next to it. Would this be possible?
In my case it is very useful.

**Comment by dwainscheeren** [comment]
Hello,

Thanks!


By default this isn't possible you would need to change some core files to archieve this. Best is to join my Discord server for help regarding changing this.

**Comment by csiza** [comment]
![IMG_0030](https://user-images.githubusercontent.com/15094273/105068172-e806b700-5a80-11eb-8d66-04ec452a7fe9.PNG)
Here is an example from my iPad.

**Comment by dwainscheeren** [comment]
Seems like a bug. Did you remove the plugin Custom Header from your setup? Did a cache refresh and HA Reboot?

**Comment by csiza** [comment]
I did several reboots, however I did not remove the custom_header plugin yet. Should I?

**Comment by dwainscheeren** [comment]
You need to remove the Custom header plugin then do a HA reboot and then a cache reset.

**Comment by csiza** [comment]
I did several reboots, but the custom_header is still there. Should I remove it?

**Comment by csiza** [comment]
thanks. it works now perfectly... do I need to remove other plugins too, or they can stay?

**Comment by dwainscheeren** [comment]
You can remove button card and custom light card plugin.

**Comment by csiza** [comment]
will do and thanks for the quick help...

And keep up the good work!!! :)))
