### ISSUE TITLE
Custom-header

### ISSUE THREAD

**Issue by csiza** [dwainscheeren/dwains-lovelace-dashboard#260]
First of all big thank you for your great work. I am using your dashboard since many many months and I love it. 
Today I have decided to upgrade my Dashboard from 1.4 to 2.1 and everything went smoothly and worked just fine, however the header of the dashboard looks like big and not able to find where can I hide it or make it smaller, like in the previous custom_header component. I am not seeing only just the bottom half of the House Information part. 
What did I miss during the upgrade?

**Comment by dwainscheeren** [comment]
Can you show me a screenshot of what you mean?
