### ISSUE TITLE
[FR] Add Badges to the header bar

### ISSUE THREAD

**Issue by seanmccabe** [dwainscheeren/dwains-lovelace-dashboard#263]
It would be awesome if could add custom badges into the header bar next to the users and lights.
Badges would be similar to lovelace.

Means quick info is easy to see, especially things like on/offs which just show a status and don't need any real interaction.

**Comment by AalianKhan** [comment]
what would be your use case for this?

**Comment by seanmccabe** [comment]
I have these in lovelace

![image](https://user-images.githubusercontent.com/12243212/106080179-7662f300-617b-11eb-9148-b5835171c728.png)

I don't need them to be buttons as I do not trigger them from the panel, but via automations. However, it is good to know if they are active, or in the case of Earthquakes, it is just interesting information.
The same could be said for something like ping, or speedtest results. Handy to have in the header as they are useful information and rarely need any further interaction.

More examples:

![image](https://user-images.githubusercontent.com/12243212/106080303-aca07280-617b-11eb-9aa0-48e08799851e.png)

In the Dwain dashboard, I have to have them as larger panels, which just take up silly amounts of space, and look like the rest of the buttons, when really they don't serve that purpose.

![image](https://user-images.githubusercontent.com/12243212/106080409-d6f23000-617b-11eb-8248-98d679995522.png)

Hopefully that is a clear enough explination.

**Comment by AalianKhan** [comment]
I see, yes that is useful.
For me, this will add a bit too much clutter me as there is limited space on mobile
but I recently found out that its possible by using persons.yaml. 
https://dwainscheeren.github.io/dwains-lovelace-dashboard/configuration/persons.html
Just replace the track field with the sensor you want to track and disable map and you should get something like this. 
![Screen Shot 2021-01-27 at 10 27 46 PM](https://user-images.githubusercontent.com/39784853/106085809-e4ada400-60ee-11eb-8291-081901349c30.png)

```yaml
  - name: temperature
    track: sensor.temperature
    show_map: 'false'
```

**Comment by seanmccabe** [comment]
Awesome thank you. Will give this a go.

**Comment by seanmccabe** [comment]
Gave this a go and works like a charm.

Only problem I've found is is it seems to be ignoring the show_map flag.

```
- name: Night
  track: input_boolean.night_mode
  show_map: 'false'
```

![image](https://user-images.githubusercontent.com/12243212/108317264-e0befe80-7222-11eb-8406-15a424ef078b.png)

Is this a bug?

**Comment by seanmccabe** [comment]
Ok ignore me, it worked. great.
