### ISSUE TITLE
[BUG] Motion title not sitting in header on mobile app view

### ISSUE THREAD

**Issue by seanmccabe** [dwainscheeren/dwains-lovelace-dashboard#264]
The section that says motion is not sitting inside the header within the Home Assistant app, nor in Chrome when on mobile it sits below, outisde the header section.
This does not occur on desktop.

Desktop view:
![image](https://user-images.githubusercontent.com/12243212/106081457-ce025e00-617d-11eb-81dd-fbf88a9ccdc3.png)

Mobile view:
![Screenshot_20210128-152359_Home Assistant](https://user-images.githubusercontent.com/12243212/106081471-d5c20280-617d-11eb-9aeb-95fd2f15a1dd.jpg)

Mobile is a Galaxy Note20 Ultra. Occurs in both portrait and landscape.

**Comment by AalianKhan** [comment]
same
sometimes it comes in between the header and body

**Comment by AalianKhan** [comment]
I have fixed the problem by simply going to the 3 dots in the header>theme setting>reload dwains dashboard
but sometimes on my phone, the problem comes back and I have to reload again.

**Comment by seanmccabe** [comment]
That doesn't do anything on my end.
And constantly having to reload isn't really a fix.
