### ISSUE TITLE
Issue with theme displaying

### ISSUE THREAD

**Issue by WMunschau** [dwainscheeren/dwains-lovelace-dashboard#271]
I have the problem that the displaying is not loaded correctly. However, when I reload the theme, it is displayed normally again. It doesn't matter if the theme in HA is set to Auto, Light or Dark. The same problem exists on mobile devices.

Bevor reload the theme configuration:
![Bevor_reload](https://user-images.githubusercontent.com/74622818/112053928-3e61a600-8b55-11eb-92d0-849fa9f51475.jpg)

After reload the theme configuration:
![After_reload](https://user-images.githubusercontent.com/74622818/112053921-3c97e280-8b55-11eb-9a3b-5057b781b4b2.jpg)

**Comment by Gerrni** [comment]
Same here on Android devices and desktop with chrome.

**Comment by HabelStefan** [comment]
Same problem here (iOS/MacOs / app)

**Comment by B-Hartley** [comment]
Yes, I have this issue too, never thought that much about it.
The first time I access the dashboard it doesn't display correctly, but after a refresh it does.

**Comment by HabelStefan** [comment]
But it should be that way. :)

**Comment by dwainscheeren** [comment]
It's a strange bug I can't replicate at my side. Mostly its coming from a slow loading of the dashboard (it depends on some milliseconds) and then the theme is loaded too late after the check.

**Comment by dwainscheeren** [comment]
You can copy the themefiles from my custom_component to your main /themes files folder which is defined in your configuration.yaml under frontend: then set Dwains ... as default theme for your whole HA that fixes the issue :)

**Comment by HabelStefan** [comment]
I give it a try :)

**Comment by Gerrni** [comment]
Your dashboard is default. I think when you switch between some dashboards (to test something in original Lovelace dashboard) and use your back function from your smartphone.

**Comment by LooSik** [comment]
Same issue here on android app.

**Comment by Gerrni** [comment]
I will try this tomorrow.

![Screenshot_2021-04-20-00-14-28-89.jpg](https://user-images.githubusercontent.com/40135870/115310048-71f01a00-a16d-11eb-91a5-41c15b7354a2.jpg)

https://github.com/dwainscheeren/dwains-dashboard-addons/tree/master/lovelace_theme

**Comment by mmornati** [comment]
> I will try this tomorrow.
> 
> ![Screenshot_2021-04-20-00-14-28-89.jpg](https://user-images.githubusercontent.com/40135870/115310048-71f01a00-a16d-11eb-91a5-41c15b7354a2.jpg)
> 
> https://github.com/dwainscheeren/dwains-dashboard-addons/tree/master/lovelace_theme
> 
> and set them as theme for your whole HA. Then its should be fixed

And? Is that fixed in the end?
I've the same problem in all my devices and it occurred with an update (not sure ha or dashboard) and since that moment it never worked good.

**Comment by mmornati** [comment]
FYI. Just tested and it is working in this way. Changing the theme to the dwains theme allows showing the dashboard correctly all the time. 🎉

**Comment by dwainscheeren** [comment]
Yes button-card and light entity card are pre-packaged so you dont need to add them yourself to your resources.

**Comment by mmornati** [comment]
> Yes button-card and light entity card are pre-packaged so you don't need to add them yourself to your resources.

Thanks. On my side, it seems the root cause of the display problem. No idea why I installed them externally... is this the configuration of Dwains since the beginning @dwainscheeren or before we needed to install them manually?

**Comment by dwainscheeren** [comment]
Since 2.0 they are loaded automagicly :)

**Comment by mmornati** [comment]
That is! I think I missed the migration guide 🤣

**Comment by mmornati** [comment]
2 days after the fix removing external duplicated modules and all is working good. Personally I think we can close this issue... What about you @WMunschau ?

**Comment by WMunschau** [comment]
You're right. The issue can be closed.
