### ISSUE TITLE
[FR] Change cards for lights etc

### ISSUE THREAD

**Issue by icodesdeveloper** [dwainscheeren/dwains-lovelace-dashboard#273]
Dear,

It would be nice if there is an easy option to select te style of cards you want other than the default home assistant one. The whole interface is so clean but when you pop up a light the default pop up from home assistant stops the cleanness of the dwains dashboard. Maybe a homekit style or another clean pop up should make that much better.

**Comment by Krispy234** [comment]
Perhaps you could use the pop-up add on?
https://dwainscheeren.github.io/dwains-lovelace-dashboard/addons/popup.html

**Comment by dwainscheeren** [comment]
Yes that's where the custom popup's are for. Each one can make there own popups to there own taste.
