### ISSUE TITLE
Overriden load_yaml breaks secret support in 2021.4

### ISSUE THREAD

**Issue by balloob** [dwainscheeren/dwains-lovelace-dashboard#274]
Home Assistant 2021.4 rewrites secrets support. Loaders will now pass a secrets object to `load_yaml` which this integration overrides. 

Relevant code in core:
 - https://github.com/home-assistant/core/blob/dev/homeassistant/util/yaml/loader.py#L108
 - https://github.com/home-assistant/core/blob/dev/homeassistant/util/yaml/loader.py#L124

Current release of your dashboard breaks secrets support in HA for users that use Dwain.

**Comment by thewazz1** [comment]
As of right now it appears that Dwains Dashboard is inoperable under the 2021.4.0 beta versions. At least I get a message that an unknown error has occured when trying to load the dashboard.

**Comment by dwainscheeren** [comment]
Im fixing it as we speak :) Hope to release a new version tomorrow which will fix the bug

**Comment by danalex0829** [comment]
I get a Reload UI error but I am not on beta. I am on the current stable version (2021.4.0).  Any ideas as to what may be wrong?

**Comment by B-Hartley** [comment]
2021.4 betas and 2021.4 release are incompatible with old versions of dwain dashboard.

New version at:
https://github.com/dwainscheeren/dwains-lovelace-dashboard/releases/tag/v2.0.2

**Comment by rjmcfadd** [comment]
I just updated Home Assistant to 2021.4.0 then dwain dashboard to v2.0.2 but now I can't restart due to this error: 

Logger: homeassistant.components.hassio
Source: components/hassio/__init__.py:486
Integration: Home Assistant Supervisor (documentation, issues)
First occurred: 10:26:25 AM (4 occurrences)
Last logged: 10:31:30 AM

Error loading /config/configuration.yaml: Secrets not supported in this YAML file

**Comment by healeydave** [comment]
Yes, I'm getting that error too.
Home Assistant prevents  restart because it detects this problem
Error loading /config/configuration.yaml: Secrets not supported in this YAML file

**Comment by Luukxt8** [comment]
Just restart home assistant from outside hass. That worked for me :) error is gone now

**Comment by dwainscheeren** [comment]
Update to v2.0.2 and HA 2021.4

**Comment by healeydave** [comment]
Already done, HA was already on 2021.4 since yesterday's Release Party video and I've just followed the instructions to update to 2.0.2 by copying over the folder from the zip file, went to restart HA and it won't let me because of that error.

**Comment by dwainscheeren** [comment]
Just reboot your HA after you placed the 2.0.2 files and make sure to override existing ones
