### ISSUE TITLE
[FR] Fan & air purify

### ISSUE THREAD

**Issue by nhok3296** [dwainscheeren/dwains-lovelace-dashboard#28]
- My air conditioner only has dehumidifying mode (dry) and cooling (cool) each update is to fix auto and heat defaults, can you fix according to smartir's existing air conditioner mode?
- I felt that the temperature and humidity should be added together with the door and motion, separating the air conditioner like a vacuum. Can you support more fan and xiaomi air purifier?
Thanks you

**Comment by dwainscheeren** [comment]
Will look into this for you :) Can you tell me some information about the fan and xiaomi air purifier entities? What are the available states of them?

**Comment by nhok3296** [comment]
I'm sorry that my version is 3H gen not supported by homeassistant so only this link https://www.home-assistant.io/integrations/vacuum.xiaomi_miio/
- My fans include spinning, speed 1-2-3, on, off
thanks

**Comment by dwainscheeren** [comment]
Maybe you can use the feature of 1.2.1 with `page_entities` for now

**Comment by dwainscheeren** [comment]
@nhok3296 looked into 1.2.*?

**Comment by nhok3296** [comment]
> @nhok3296 looked into 1.2.*?
Thank you for your interest in contributing, if possible please update the changes without affecting the files like room.yaml, person.yaml, etc.

**Comment by nhok3296** [comment]
> @ nhok3296 nhìn vào 1.2. *?
I have not used your theme since the 1.1.5 update because of a weather error (null), and each update has to start hass and replace files constantly, it could be as simple as if I had one.  charged (but unfortunately I use a phone).  Thank you for contributing to the community, I recommend your theme to a lot of people in Vietnam, they love it

**Comment by dwainscheeren** [comment]
Those files you mention are never changed @nhok3296 (`rooms.yaml`, `persons.yaml`) etc those are always the files from your own config in `dwains-theme/configs/`

Yeah 1.1.5 had a weather bug this is fixed in 1.2.*. Also the update proces is indeed overwriting the files each time (nothing else I can do there) but it will take 1-2 minutes.

**Comment by nhok3296** [comment]
> Những tệp bạn đề cập không bao giờ thay đổi @ nhok3296 ( `rooms.yaml`, `persons.yaml`) v.v ... những tệp đó luôn là các tệp từ cấu hình của riêng bạn trong`dwains-theme/configs/`
> 
> Vâng 1.1.5 có lỗi thời tiết, lỗi này được khắc phục trong 1.2. *. Ngoài ra, quá trình cập nhật thực sự ghi đè lên các tệp mỗi lần (tôi không thể làm gì khác ở đó) nhưng sẽ mất 1-2 phút.

Can you link it to hacs?

**Comment by dwainscheeren** [comment]
> > Những tệp bạn đề cập không bao giờ thay đổi @ nhok3296 ( `rooms.yaml`, `persons.yaml`) v.v ... những tệp đó luôn là các tệp từ cấu hình của riêng bạn trong`dwains-theme/configs/`
> > Vâng 1.1.5 có lỗi thời tiết, lỗi này được khắc phục trong 1.2. *. Ngoài ra, quá trình cập nhật thực sự ghi đè lên các tệp mỗi lần (tôi không thể làm gì khác ở đó) nhưng sẽ mất 1-2 phút.
> 
> Can you link it to hacs?

That's unfortunately not possible. HACS doesn't have support for it like the theme is build.

**Comment by nhok3296** [comment]
> > > Những Tệp you mentioned never changes @ nhok3296 ( `rooms.yaml`, `persons.yaml`) vv ... those Tệp which is always the Tệp from the configuration of its own you in `dwains-theme/configs/`
> > > Vâng 1.1.5 errors thời tiết, errors been khắc phục trong 1.2. *. Trẻ ra, quá tải và tuyệt vời.
> > 
> > 
> > Bạn có thể liên kết nó với hacs?
> 
> Thật không may là không thể. HACS không có hỗ trợ cho nó giống như chủ đề được xây dựng.

Thank you

**Comment by davidkmcgowan** [comment]
I also have fan switches from GE, they show up entity wise if you use page_entities as on/off, but they support off, low, medium, and high. When adding to as page_entity, not sure how I can change it at all

**Comment by dwainscheeren** [comment]
This will be possible in DD 3.0.
