### ISSUE TITLE
Fresh Install HASSOS - Integration "

### ISSUE THREAD

**Issue by Tokn59** [dwainscheeren/dwains-lovelace-dashboard#287]
Repo steps:

- Fresh install of HASSOS (on Proxmox) - core-2021.3.4, supervisor-2021.03.9
- Downloaded latest build 2.0.2
- Unzipped
- Copied to /config/custom-components (see screenshot attached)
- Results in /config/custom-components/dwains_dashboard

![image](https://user-images.githubusercontent.com/9215231/115843107-c7068700-a41e-11eb-8643-cf3909cf116f.png)

- Supervisor - Reboot Host
- Configuration - Integrations - "+ Add integration"
- Select "Dwains dashboard"
- ERROR : Conflig flow could not be loaded

![image](https://user-images.githubusercontent.com/9215231/115843209-dede0b00-a41e-11eb-9176-43109e839653.png)

LOG:

Logger: homeassistant.config_entries
Source: config_entries.py:563
First occurred: 10:13:30 (3 occurrences)
Last logged: 10:28:04

Error occurred loading configuration flow for integration dwains_dashboard: cannot import name 'Secrets' from 'homeassistant.util.yaml' (/usr/src/homeassistant/homeassistant/util/yaml/__init__.py)

Please advise .. Thank YOU !!!

**Comment by dwainscheeren** [comment]
Please upgrade HA to 2021.4 minimum

**Comment by Tokn59** [comment]
That option does not seem to be available ... In Supervisor - System the current version is up to date ...

![image](https://user-images.githubusercontent.com/9215231/115847526-59108e80-a423-11eb-93ed-844942e959ed.png)

**Comment by dwainscheeren** [comment]
The latest version is 2021.4.6 so upgrade to it :) https://www.home-assistant.io/blog/2021/04/07/release-20214/

**Comment by Tokn59** [comment]
Easier said than done apparently .. When I execute :

core update
supervisor update

they both say I am already on the latest version ?

**Comment by Tokn59** [comment]
OK, now HASSOS presented me with an update .. seems this doesn't get pushed automatically to everyone yet. Integration now works. Next steps:

- Start Dashboard
- ERROR : Custom element doesn't exist: button-card.

This is something I have seen many times before. The custom cards are located as per your documentation in config/custom-components/dwains-dashboard/cards

For the cards to be working I always have to place them in config/www/community otherwise tha cards are not found by Lovelace ...

If I move over the cards to that location then the cards are usable by Dwain Dashboard.

I also see that by installing the integration a new folder is created:

config/dwains-dashboard

with two subfolders : 

addons
configs

Now here's confusion ... where do the rooms, cameras ... yaml files need to be edited ?

**Comment by Tokn59** [comment]
**SOLVED FOR NOW**

Part of Fontawesome was missing. Everything is working now and I learned the real config files are located in /config/dwain-dashboard/configs. 

Some other issues but will first try and set up everything as far as I can.
