### ISSUE TITLE
HACS compatibility

### ISSUE THREAD

**Issue by lbouriez** [dwainscheeren/dwains-lovelace-dashboard#289]
Hello, more a question than an issue, do you plan to make it installable from HACS ?

**Comment by LRvdLinden** [comment]
@lbouriez it is already possible. Add dwainscheeren/dwains-lovelace-dashboard as custom repo in HACS.

**Comment by lbouriez** [comment]
Thx, i will try. You shouldnwritenitnin the installation note ;)
