### ISSUE TITLE
Error after update through HAC to 2.0.3 

### ISSUE THREAD

**Issue by deku-m** [dwainscheeren/dwains-lovelace-dashboard#293]
HI,

Im getting a error after updating via HACS to 2.0.3.
Only through mobile not through webinterface via desktop/laptop.

See below:
“custom element doesnt exist: dwains-wrapper-card” 
![Screenshot_2021-05-06-10-19-11-655_io homeassistant companion android](https://user-images.githubusercontent.com/37069737/117403958-5cb71180-af09-11eb-83d5-49a6d0bf9e24.jpg)

Tried removing cache on mobile no success for the error..
Also removed it from HACS and folder and reinstalled it still error
Phone is Android 10.

The card is located under /custom_components/cards/dwains-wrapper-card/

**Comment by dwainscheeren** [comment]
Its a cache issue for sure. So make sure you really clear the cache or re-install the HA app.
