### ISSUE TITLE
Upgrade to 2.03 fails

### ISSUE THREAD

**Issue by Tokn59** [dwainscheeren/dwains-lovelace-dashboard#294]
Instructions followed : 

Download version 2.0.3 and unzip the file.
Inside this folder you will see a folder called custom_components copy this folder.
Go to the main folder of your Home Assistant installation. This is the folder where you config is. (Hint: its the folder where for example the files ui-lovelace.yaml and configuration.yaml are located).
Paste the custom_components to the main folder of your Home Assistant installation and overwrite all existing files!
Make sure you are updated to HA 2021.5!
Reboot your Home Assistant
Clear your browser cache on all devices
You are done!

Current versions HA: 

Core : 2021.5.3
Supervisor : 2021:04.3

Result : 
![image](https://user-images.githubusercontent.com/9215231/117946709-d6873a80-b30f-11eb-8d30-01599d44e590.png)

**Comment by Tokn59** [comment]
Update .... System "repaired" itself after a couple of minutes (10) after restart HA (reboot Host). 👍

**Comment by dwainscheeren** [comment]
Also double check to clear your cache, ctrl + f5 in browser :), works now?
