### ISSUE TITLE
Missing "Configs" folder

### ISSUE THREAD

**Issue by supermarkert** [dwainscheeren/dwains-lovelace-dashboard#295]
First time user, so I downloaded the latest 2.0.3 release. Followed the instructions, which states to look for the "dwains-dashboard/configs/" folder. This folder doesn't exist. 
There is an Installation folder, which contains an entry for "ignorethisfolder", within which are all the relevant config files.

**Comment by AalianKhan** [comment]
When moving the custom component folder, then restarting home assistant. The config folder should generate automatically

**Comment by supermarkert** [comment]
Not sure what you mean by "moving" the component folder, but I've copied dwains to my custom_components folder and restarted HA. I've added the integration and D is in my sidebar.
There is no "configs" folder.
![image](https://user-images.githubusercontent.com/15205204/118054928-2b00d900-b355-11eb-86f3-724020144f6a.png)

**Comment by southwestflavorz** [comment]
I'm having the same issue. I copied the dwains_dashboard to the custom_components folder and restarted HA (multiple times), but there is no configs folder inside the dwains_dashboard folder.

**Comment by AalianKhan** [comment]
What happens when you click on continue and load Dashboarf?

**Comment by southwestflavorz** [comment]
Loads the image below, but still no config folder:

![image](https://user-images.githubusercontent.com/4965670/118068017-78ca1100-b356-11eb-9f43-71d47bab46ba.png)


![image](https://user-images.githubusercontent.com/4965670/118068072-95664900-b356-11eb-9ed5-80c0cfe13c45.png)

**Comment by AalianKhan** [comment]
Oh, you are looking on the wrong folder. The path is /config/dwains-dashboard/configs

Go to where your Configuration.yaml is and you should see dwains-dashboard. Click that then configs

**Comment by southwestflavorz** [comment]
doh!!!  Thank you for the clarification. I'm slightly comforted by the fact that I'm not the only one to make this mistake...

**Comment by supermarkert** [comment]
Ahah. I read the instructions many times and kept thinking it was referring to the installation folder.
Thanks.
