### ISSUE TITLE
Feature Request - Images instead of Icons

### ISSUE THREAD

**Issue by Robvred** [dwainscheeren/dwains-lovelace-dashboard#296]
Hello,

That's will be good if we can use instead of icons on the home page, entity picture variable.

For the home page images will be more nice than a simple icon.

Thanks !

**Comment by powertoaster** [comment]
I agree completely but would word it slightly differently Icons and entity_picture. I want to use either.

**Comment by Robvred** [comment]
That's now possible with the integration of font awesome v2 ! :)

https://community.home-assistant.io/t/dwains-dashboard-1-click-install-lovelace-dashboard-for-desktop-tablet-and-mobile-v2-0-3/168593/1474?u=robvred
