### ISSUE TITLE
while scanning for the next token found character '%' 

### ISSUE THREAD

**Issue by romanNedzelsky** [dwainscheeren/dwains-lovelace-dashboard#298]
Hello everyone, I am trying to make dwains dashboard working, I've installed it based on the documentation, modify yaml configurations (added my own sensors etc) but I am still have this error:

while scanning for the next token found character '%' that cannot start any token in "/config/custom_components/dwains_dashboard/lovelace/plugins/dwains_dashboard.yaml", line 7, column 2

any idea?

**Comment by hirsts** [comment]
I have seen this many times. Prior to 2.0.3 it was intermitent (dont change anything, just restart HA would fix it). Since upgrading to 2.0.3 it is now constant and I cannot use Dwains Dashboard. I have no Dwains extensions or non-stardard configuration. Looking for solutions now......

**Comment by dwainscheeren** [comment]
Are you using lovelace_gen?

**Comment by romanNedzelsky** [comment]
yes, should I turn it off?

**Comment by dwainscheeren** [comment]
Yes, you n eed to disable lovelace_gen, my dashboard will replace it.

**Comment by hirsts** [comment]
I'm not using lovelace_gen that I know of. If its on by default, how do I disable it?

**Comment by romanNedzelsky** [comment]
well, I've removed it, but still nothing :/

**Comment by romanNedzelsky** [comment]
ok, so 
1) removed lovelace_gen
2) removed & installed dwains integration (in configuration)
3) restart of host 
4) "Unknown error" with "Reload" button

**Comment by dwainscheeren** [comment]
Check your error log.

**Comment by romanNedzelsky** [comment]
well so after the restart, HACS is gone, limited functionality, weird...

two screenshots:
![2021-05-24_21-13-04](https://user-images.githubusercontent.com/22219727/119396247-e8d08380-bcd4-11eb-8398-c2d07d3c9b69.png)
![2021-05-24_21-11-01](https://user-images.githubusercontent.com/22219727/119396251-e9691a00-bcd4-11eb-9fc4-910ac4980fb8.png)

**Comment by dwainscheeren** [comment]
Not sure what Dwains Dashboard has to do with your HACS not loading?..

**Comment by romanNedzelsky** [comment]
Not sure either, but immediately when I've disabled DwainsDashboard, HACS is back on the left side, all the webparts working again...weird ;)

**Comment by dwainscheeren** [comment]
I think this it not relevant anymore, maybe hacs bug.?
