### ISSUE TITLE
Favorites - Switch does not function

### ISSUE THREAD

**Issue by Tokn59** [dwainscheeren/dwains-lovelace-dashboard#301]
Not sure if this is by design or not.

house_information:
  favorites:
    - entity: switch.koffiemaker
      icon_on: fas:mug-hot
      icon_off: fas:coffee

Shows the coffee icon but I cannot use this to switch on/off the coffeemaker switch. When I click on it, or on the "off" it shows the logbook entries. 

![image](https://user-images.githubusercontent.com/9215231/118822521-8896a780-b8b8-11eb-9f73-dce14ebe4d04.png)

![image](https://user-images.githubusercontent.com/9215231/118822604-977d5a00-b8b8-11eb-8fd7-6c818d1b5fce.png)

**Comment by dwainscheeren** [comment]
Double click or tap an hold does work?

**Comment by Tokn59** [comment]
No that doesn't seem to work either .. it keeps bringing me to the pop up "logbook" as with single click ...

**Comment by Tokn59** [comment]
Wait let me check the switch again ..

**Comment by Tokn59** [comment]
Sorry, just checked .. the switch is OK and works ... But not in the favorites panel, only as an entity/switch
