### ISSUE TITLE
More_page / Speedtest

### ISSUE THREAD

**Issue by Natsuignir** [dwainscheeren/dwains-lovelace-dashboard#303]
Hi Everyone, 

I'm very new in the HA world and found a lot of pleasure to use Dwains Dashboard. Very nice Job to the developper. 

I have actually two problems that i cannot solve and didn't found any solution on google. 

1. more_page.yaml : 
-  I want to use more addons on my dashboard, but at this moment I only able to use one addon. 
> My configuration:
more_page:    
     addons:
       - name: SpeedTest
         main_menu: 'true'
         icon: mdi:lan
         path: 'dwains-dashboard/addons/more_page/speedtest/page.yaml'

- By adding a new line with more_page : ... I have an error in the file. 
**How can i had more then one extra page in this file ? **

2. Speedtest addon : 
- By following the different steps at the end I have the current problem 
![image](https://user-images.githubusercontent.com/83397670/119229122-b5e09100-bb16-11eb-99a5-3e0cd5fef5ad.png)

Thanks in advance for your help

**Comment by AalianKhan** [comment]
It looks like you don't have the card installed or it's not defined in the Lovelace resources. You can install via hacs or manually install and define it in configuration>Lovelace>resources https://github.com/kalkih/mini-graph-card#hacs-recommended

**Comment by Natsuignir** [comment]
> It looks like you don't have the card installed or it's not defined in the Lovelace resources. You can install via hacs or manually install and define it in configuration>Lovelace>resources https://github.com/kalkih/mini-graph-card#hacs-recommended

Thanks, 👍
