### ISSUE TITLE
Covers: close using overview

### ISSUE THREAD

**Issue by helmuthel** [dwainscheeren/dwains-lovelace-dashboard#307]
Hi!
When I go to a room, each of them has a cover, but I can't open/close them:
![image](https://user-images.githubusercontent.com/11671742/120159432-7fc99e00-c1f5-11eb-9eda-5ecea3b4eb35.png)

When I click it, I only get a slider:
![image](https://user-images.githubusercontent.com/11671742/120159467-89eb9c80-c1f5-11eb-8367-3a5087770013.png)
Even though I have the positions, I don't really care for them for SOME screens, So i'd like to have an OPEN or CLOSE button.

Is that possible?

**Edit**: I'm using a Shelly 2.5 which supports:
- open
- close
- set position
- 
![image](https://user-images.githubusercontent.com/11671742/120474972-1a1e1300-c3a9-11eb-969a-b2615f81de7d.png)

**Comment by kesm** [comment]
Same here with ZHA and a tuya device that has 15 supported_features
![image](https://user-images.githubusercontent.com/6907912/135430938-e5cd1a99-b81f-4672-bdf0-1ab6fa689392.png)

**Comment by dwainscheeren** [comment]
This is fixed in dd 3.0
