### ISSUE TITLE
HACS Compliance

### ISSUE THREAD

**Issue by BigWebstas** [dwainscheeren/dwains-lovelace-dashboard#309]
I am getting a `Repository structure for v2.0.3 is not compliant `after the latest HACS update

**Comment by dylanjwhite** [comment]
I'm seeing the same except now with `v2.0.4`

**Comment by polysa** [comment]
Same issue. Can't add the repo to Hacs. Any workaround?

**Comment by Diondk** [comment]
Hi,

Please add it as integration! not as a frontend, i just added it to hacs succesfully!

Kind regards,
Dion

**Comment by polysa** [comment]
> Hi,
> 
> Please add it as integration! not as a frontend, i just added it to hacs succesfully!
> 
> Kind regards, Dion

Thank you
