### ISSUE TITLE
FR hoover room button

### ISSUE THREAD

**Issue by Bubbleshum** [dwainscheeren/dwains-lovelace-dashboard#310]
Just installed today and looks brilliant. Just wondered if there is a way to add custom script button to rooms for hoovering that room.

Thanks in advance

**Comment by AalianKhan** [comment]
I think this is what you are looking for 
https://github.com/dwainscheeren/dwains-lovelace-dashboard/discussions/284

**Comment by Bubbleshum** [comment]
Perfect thank you
