### ISSUE TITLE
Unable to remove notifications

### ISSUE THREAD

**Issue by cobirnm** [dwainscheeren/dwains-lovelace-dashboard#311]
When I have a notification on the dashboard and try to press the "x" nothing happens. I can only remove it by calling the service.

This has happen after upgrading HA to 2021.06.x and updating the dashboard to the latest version

**Comment by Boh1** [comment]
Same for me. Version 2.0.3 with HA Core 2021.6.3.

**Comment by BernieV1977** [comment]
Also an issue on version HA Core 2021.6.4.

**Comment by ahutchison1962** [comment]
Same issue here 2021.6.4

**Comment by cobirnm** [comment]
All our hopes are in @dwainscheeren

**Comment by dwainscheeren** [comment]
I'm not sure I gonna fix this. Every new HA version something breaks. It takes me too much time to look into it, fix/patch it, make new release etc. I'm also started to work on 3.0 but I need to combine it with my normal job. I also don't receive any donations anymore to finance it. I'm thinking about making 3.0 a paid version.

**Comment by ahutchison1962** [comment]
You should do that Dwain - I would pay for it

**Comment by BernieV1977** [comment]
> I'm not sure I gonna fix this. Every new HA version something breaks. It takes me too much time to look into it, fix/patch it, make new release etc. I'm also started to work on 3.0 but I need to combine it with my normal job. I also don't receive any donations anymore to finance it. I'm thinking about making 3.0 a paid version.

For me the biggest issue I can't start using DD fulltime in my home now is the casting problem: https://github.com/dwainscheeren/dwains-lovelace-dashboard/issues/313
If you can fix this I would donate asap so I can start using your brilliant dashboard and then I wouldn't have a problem to pay for 3.0.

**Comment by Boh1** [comment]
Having donated some money already, I'd be happy to pay for 3.0 version if that would give Dwain (or anyone else) the time to maintain this.

**Comment by dwainscheeren** [comment]
This will be fixed in 2.0.4

**Comment by cobirnm** [comment]
@dwainscheeren I have installed 2.0.4 but the issue is still present. Did you manage to fix it?

**Comment by dwainscheeren** [comment]
Yes, did you clear your cache?

**Comment by cobirnm** [comment]
> Yes, did you clear your cache?

You are correct. I missed that step! it's solved. Thank you for all your hard work!
