### ISSUE TITLE
Where is documentation?

### ISSUE THREAD

**Issue by maskaz** [dwainscheeren/dwains-lovelace-dashboard#312]
Hi.
Documenation looks like a mess.
It is exist, but outdated, example: "A good example is to checkout the hello-house-information-page addon in dwains-dashboard/addons/house_information/hello-house-information-page/page.yaml to re-use or inspire you."
But install archive do not cantaines any file or dir under "addons" directory.

Or totaly dead, like this link from one of the Issues, that might can help resolve problem, but cannot because it is dead already:
https://dwainscheeren.github.io/lovelace-dwains-theme/configuration/rooms.html#rooms-information

Can i ask (I am begging) to clear/create proper docs?

Regards

**Comment by dwainscheeren** [comment]
documentation is here https://dwainscheeren.github.io/dwains-lovelace-dashboard/ just 1 minute to find it on homepage of this repo.
