### ISSUE TITLE
Not possible to cast Dwains Dashboard

### ISSUE THREAD

**Issue by BernieV1977** [dwainscheeren/dwains-lovelace-dashboard#313]
I cannot cast Dwains Dashboard
It doesn't work by automation using the service cast.show_lovelace_view
Casting a tab from a browser works but this is unuseable (no touch screen possibility)

![image](https://user-images.githubusercontent.com/16529684/120986631-1578a680-c77d-11eb-8cb9-05bb6bc0197f.jpg)

Regards,
Bernd

**Comment by dwainscheeren** [comment]
Did you ask on the HAA discord if anyone else got it working? I dont got a device to cast to so I cant test it.

**Comment by BernieV1977** [comment]
> Did you ask on the HAA discord if anyone else got it working? I dont got a device to cast to so I cant test it.

Just did it

**Comment by dwainscheeren** [comment]
Please try 3.0 when its released
