### ISSUE TITLE
Scenes page not showing correctly

### ISSUE THREAD

**Issue by etpedro** [dwainscheeren/dwains-lovelace-dashboard#317]
Hi,

The documentation page for scenes is not showing tables the right way:
https://dwainscheeren.github.io/dwains-lovelace-dashboard/configuration/scenes.html

Is it possible to fix?
Do you want me to help you with it?

Regards,
Pedro

**Comment by etpedro** [comment]
It should be something like this:

Entities array 
| Name | Type | Default | Example | Description |
|———|———|———|———|———|
| entity | array | Required | See table below | scene.watching_tv | Scene entity_id. Can be a scene entity or something like switch or input_boolean. | 
| icon | string | far:play-circle | fas:couch | Icon to display | 
| icon_color | string | var(–dwains-theme-header-text) | ‘#ffffff’ | Icon color | 
| background | string | optional | ‘linear-gradient( 135deg, #FEB692 10%, #EA5455 100%)’ | Background color, you can use css styling here |

**Comment by dwainscheeren** [comment]
Thanks! Will take a look at it :)
