### ISSUE TITLE
Header Style - Help

### ISSUE THREAD

**Issue by siaox** [dwainscheeren/dwains-lovelace-dashboard#319]
![Screenshot_20210719-184429__01](https://user-images.githubusercontent.com/32471359/126166266-9435f6ef-3b07-4acc-b3b6-837ab4d06553.jpg)

Hi there this is a dope dashboard. I'm not sure if this is an old feature or if I might be missing something in my cofigs:

1. My persons and weather are showing up as small badges in the home screen of the dashboard - is there something I'm missing to make it look like the promotional pictures? ( Hopefully attached the screenshot correctly)

2. I'm using openweather instead of darksky will that cause any issues for my first point?

Thanks.

**Comment by Klumpke** [comment]
Hi @siaox,
the screenshots on the github page are from version 1.
It's true that in version 2.x it looks like your image.

**Comment by siaox** [comment]
@Klumpke 

Thanks for that - wasn't sure if I did something wrong
