### ISSUE TITLE
Feature Request - New device type - Ceiling Fan

### ISSUE THREAD

**Issue by HairyHook** [dwainscheeren/dwains-lovelace-dashboard#320]
Hello,

It would be great if we could have a new device type for ceiling fans (or any fan device type).

Great job with the dashboard!

**Comment by GoTTi74** [comment]
@HairyHook 

Such a feature exists as add-on here: https://github.com/dwainscheeren/dwains-dashboard-addons/tree/master/rooms/fan-control

**Comment by HairyHook** [comment]
Appreciate the link, did not know such an addon existed. Thanks.
