### ISSUE TITLE
[FR]Integrate new Energy Integration to Dwains Dashboard

### ISSUE THREAD

**Issue by XxCabbyoO** [dwainscheeren/dwains-lovelace-dashboard#322]
It would be great, if it is possible to integrate the new Energy Integration to Dwain Dashbaord, maybe under Devices.

Infos coming soon: https://rc.home-assistant.io/integrations/energy/

seen at beta: https://rc.home-assistant.io/blog/2021/07/28/release-20218/

**Comment by t0bse** [comment]
comeback possible for DD3?
