### ISSUE TITLE
after update to 2021.8.x person tracking history is missing

### ISSUE THREAD

**Issue by boyphongsakorn** [dwainscheeren/dwains-lovelace-dashboard#325]
after i update core to 2021.8.x person tracking history is missing

![person tracking history is missing](https://i.ibb.co/L1JykqZ/2021-08-05-120833.png)

**Comment by timknowlden** [comment]
any fix for this?

**Comment by ratleback** [comment]
Mine was freezing after I clicked on person head. I had to go back on browser to start again.

**Comment by kbrigitta** [comment]
I'm having the same issue. Still no fix/explanation for this?

**Comment by totalitarian** [comment]
I’m also getting freezing when clicking on a person’s head. Makes the app / browser hang.

**Comment by ratleback** [comment]
> I’m also getting freezing when clicking on a person’s head. Makes the app / browser hang.

I tried on windows edge it still fine. Don't know why though.

**Comment by totalitarian** [comment]
> > I’m also getting freezing when clicking on a person’s head. Makes the app / browser hang.
> 
> I tried on windows edge it still fine. Don't know why though.

Yew works fine on edge. I wonder if others have the same issue? Maybe he have a plugin installed that is causing compatibility issues

**Comment by Luukxt8** [comment]
I have this issue with the iOS app. What I noticed in the browser dev console on a PC is that I get like 12k+ button-card js errors within a few seconds when opening a persons page.

**Comment by ratleback** [comment]
> I have this issue with the iOS app. What I noticed in the browser dev console on a PC is that I get like 12k+ button-card js errors within a few seconds when opening a persons page.
> 
> Looks like that some browsers can’t handle that amount of errors within that short time period.

Yeah, I got that error too. Look like It happened after few recent updates.

**Comment by Luukxt8** [comment]
My work around for this is to remove(comment) the button-card lines with the person history in it from the persons.yaml at HomeAssistant\custom_components\dwains_dashboard\lovelace\views\main\persons\person.yaml. This fixed it for me.
Line 50 to 67. See screenshot
![image](https://user-images.githubusercontent.com/50046608/130495533-c81e058f-d4c6-4114-9155-f00e10386227.png)

**Comment by totalitarian** [comment]
> My work around for this is to remove(comment) the button-card lines with the person history in it from the persons.yaml at HomeAssistant\custom_components\dwains_dashboard\lovelace\views\main\persons\person.yaml. This fixed it for me.
> Line 50 to 67. See screenshot
> ![image](https://user-images.githubusercontent.com/50046608/130495533-c81e058f-d4c6-4114-9155-f00e10386227.png)

Excellent, thank you! Wonder which specific line is causing the issue. @dwainscheeren  you still alive buddy?

**Comment by Klumpke** [comment]
You can also comment out lines 54 to 67.
It only goes wrong with the custom_field history graph.
This seems to be more of a problem in button-card custom-card.

**Comment by timknowlden** [comment]
Is there a way to fix this without losing any functionality?

**Comment by antonoal** [comment]
There's an open issue in button-card's repo about it: https://github.com/custom-cards/button-card/issues/457

**Comment by dwainscheeren** [comment]
This will be fixed in 2.0.4
