### ISSUE TITLE
Trouble with adding a menu to other fuctions

### ISSUE THREAD

**Issue by denperss** [dwainscheeren/dwains-lovelace-dashboard#326]
Hello, 

Ive got some issues by adding etc. Shopping list to a page on the dashboard.. 
It seems that i can only use path: 'dwains-dashboard/addons/more_page/statistics/page.yaml'
but not path: '/shopping-list' 

# https://dwainscheeren.github.io/dwains-lovelace-dashboard/configuration/more_page.html
more_page:
   addons:

     - name: Shopping card. 
       main_menu: 'true' #Show this addon in the main navigation bar!
       icon: fas:shopping-cart
       path: '/shopping-list'

     - name: Todo
       main_menu: 'true' #Show this addon in the main navigation bar!
       icon: fas:list-ol
       path: 'dwains-dashboard/addons/more_page/statistics/page.yaml'

What am i doing wrong here ???

**Comment by Klumpke** [comment]
This is not how it's meant to be.
At path you can only enter a path to your custom more-page yaml file.
