### ISSUE TITLE
[FR] Camera on Main Page

### ISSUE THREAD

**Issue by skeal** [dwainscheeren/dwains-lovelace-dashboard#327]
Hello Dwain and very much thank you for this dashboard.

I already configured everything and presented it to the boss, my wife. But guess what ... my pitch failed :-)

And that's just because I cannot place camera stream directly on the main page, or can I?
This would be the only thing that would be needed as she directly wants to see who is on the front door when the door bell rings or when the children are in the garden without having to touch anything. Something like a walk by picture :-)

**Comment by Seechay** [comment]
You could probably achieve this using browser_mod. Setup a popup card on a more_page and use browser_mod to trigger switching to or popping up the card when the door bell rings or when motion is detected in the garden?

**Comment by skeal** [comment]
Thanks for this but I would need the camera stream all the time on the main page to satisfy my wife's need for a dashboard :)

**Comment by dwainscheeren** [comment]
For now its not possible, only with changing the core files. Try adding a camera card here https://github.com/dwainscheeren/dwains-lovelace-dashboard/blob/2.0/custom_components/dwains_dashboard/lovelace/views/main/01.homepage.yaml#L236

**Comment by labaland** [comment]
> For now its not possible, only with changing the core files. Try adding a camera card here https://github.com/dwainscheeren/dwains-lovelace-dashboard/blob/2.0/custom_components/dwains_dashboard/lovelace/views/main/01.homepage.yaml#L236

plz fix camera on homescreen!! Many want it :) How awesome to always have doorbell on the tablet?? <3

**Comment by dwainscheeren** [comment]
This if possible in DD 3.0
