### ISSUE TITLE
Theme changes by itself

### ISSUE THREAD

**Issue by manunited10** [dwainscheeren/dwains-lovelace-dashboard#330]
Greetings,
Trying this dashboard was on my todo list for a while. Yesterday I gave it a go (clean instal). Setup is easy and straight forward. Took me a few hours to config my entities into this dashboard and everything was all good. My main intention was to use this dashboard on my phone as I have some good tablet-mount dashbaords already.
In general, the effort has been put on this dashboard is valuable and well done to the author(s) that made it this easy.

After setting up everything on computer, I started looking at the phone. At first the dashbaord couldn't load on my phone and cleaning cache, force close, restart, etc. didn't work. Eventually, I had to reinstall the HA companion app to make it work which is a bit pain (same thing on my wife's phone).

Anyway, the main problem is now the dashboard shows `random theme` on the phones and even on the computer browser. I googled and found out that in the HA Integration page we could play with the theme, but that doesn't help a lot. Every hour or so the dashboard changes its theme from white to dark to black-and-white (without me even touching the code). A bit weired. Sometimes (not always) when I press `Reload theme configuration` on the `more` page of the dashboard, the theme changes to white. Can anyone tell me what I missed?
The other thing is, when black-and-white theme loads (by itself) onto our phone, the header tabs (i.e. Homepage, Lights, Cameras and three dots) they move to `bottom` of the screen!

And one more minor issue is although the HA Integration config has a field to rename the dashboard, it never changes (service reload and even restarting HA didn't help as well). 
Any help would be appreciated.

Home Assistant is 2021.9.5
dwains dashboard is 2.0.3

**Comment by dwainscheeren** [comment]
Its a bug on some devices, the best way is to install the DD theme in HA and set that as your theme for your whole HA. https://github.com/dwainscheeren/dwains-dashboard-addons/tree/master/lovelace_theme

**Comment by samuelcanadi** [comment]
I have the same problem with dark schemes. Changing the theme to DD themes doesn't help.
