### ISSUE TITLE
Button card loaded twice

### ISSUE THREAD

**Issue by johntdyer** [dwainscheeren/dwains-lovelace-dashboard#331]
I am transitioning / testing this and I really like it... however it seems you're loading some cards again that I've already loaded in my lovelace config....   Is there a way to stop this from loading again so I can get rid of the error in my console log ?

**Comment by Diondk** [comment]
Most of the cards are created by Dwain himself, only 2 others are loaded.
They are located here:  https://github.com/dwainscheeren/dwains-lovelace-dashboard/blob/2.0/custom_components/dwains_dashboard/load_plugins.py

But when you update to a new version these files will be overwritten automatically again so you will have to change it every time.
