### ISSUE TITLE
Entity name too long for the button

### ISSUE THREAD

**Issue by jake404** [dwainscheeren/dwains-lovelace-dashboard#333]
When an entity name is too long for the button, it covers the state value. 

The entity should either truncate or render on multiple rows. Even better would be to have a name parameter for the entity in the rooms.yaml. In the image below it would then be named just 'Temperature', as we already know the room name from the header.

![image](https://user-images.githubusercontent.com/12189899/139130970-374de4e2-6dce-418b-9ecb-d1ac6e830314.png)

**Comment by ikrowni** [comment]
Was the ability to rename devices added yet? The dashboard looks amazing except all the names are garbled up making it look a mess.

**Comment by AbhiOommen** [comment]
@dwainscheeren Happy New Year! 

Is this ability to include a `name:` in the config to change the friendly_name attribute something you would be adding soon?

**Comment by dwainscheeren** [comment]
Im planning this for 3.*

**Comment by AbhiOommen** [comment]
Thank You! This would be excellent. Love your theme/dashboard as is, these small tweaks would be an excellent addition  as well.

Could you please take a look at my question here and comment #365  - just trying to understand the capabilities and functionality I could add myself here.

**Comment by dwainscheeren** [comment]
This will be fixed in 3.0
