### ISSUE TITLE
Fresh installation, config files not in /dwains-dashboard/configs

### ISSUE THREAD

**Issue by Morbus7** [dwainscheeren/dwains-lovelace-dashboard#334]
Im moving from HS4 to HA.
Freshly installed HA, and installed dwains dashboard today.
I followed the installation instructions from this link: https://dwainscheeren.github.io/dwains-lovelace-dashboard/getting-started/installation.html

Im at step 6, but theres no such folder named "configs" in /dwains-dashboard/ (full path is /root/config/custom-components/dwain-dashboard/

![image](https://user-images.githubusercontent.com/37591738/144049834-dd7bf9dd-44c3-42c1-8dab-dec66baac032.png)

When I enter the dashboard via the "D" in the sidepanel, this is what I get.
![image](https://user-images.githubusercontent.com/37591738/144049769-943e2998-9b87-4255-91d2-7ca944e5d51a.png)

Can I just create the "configs" directory and copy the files from "/config/custom_components/dwains_dashboard/installation/ignorethisfolder" As I can see that this folder contains the rooms, global, persons, cameras etc files.

**Comment by dwainscheeren** [comment]
Please look in "/root/config/dwains-dashboard" its created automaticly

**Comment by Morbus7** [comment]
Ah great. There they are. However I seem unable to find out where I actually add all my sensors/devices.
I cant find the "auto generating lovelace ui dashboard" as claimed by the banner on the github page :) 

Love the images on those banners with the dark theme, with bluish buttons. Could you point me in the direction to get me started on a view like that?

**Comment by dwainscheeren** [comment]
You need to add the sensors, lights etc inside rooms.yaml then refresh the dashboard and it will automatic build all pages and the dashboard for you.
