### ISSUE TITLE
Dark Sky (weather) not available for new users

### ISSUE THREAD

**Issue by bafplus** [dwainscheeren/dwains-lovelace-dashboard#335]
New users cant create api key for use with the Dark Sky integration.

See: https://alerts.home-assistant.io/#dark_sky.markdown

Maybe time to switch to a different weather integration?

**Comment by dwainscheeren** [comment]
You can use any of the weather integrations you want inside DD :)

**Comment by bafplus** [comment]
Ow cool! Thats not clear in the documentation. Will try to make it a bit more clear and make a PR for it.

**Comment by TheGroundZero** [comment]
Met.no is a good alternative in my experience

**Comment by cab113** [comment]
We can use pirate weather as it easily maps all entities in the same way as darksky. Almost same api design and almost no tweak required to behave same as dark sky. Easy integration in HA
