### ISSUE TITLE
New Install: No such file or directory

### ISSUE THREAD

**Issue by Colorado4Wheeler** [dwainscheeren/dwains-lovelace-dashboard#336]
After a fresh install and setting up one room to test I get an error:

```
[Errno 2] No such file or directory: '/config/dwains-dashboard/addons/popups/cover/popup.yaml'
```

When I look at dwains-dashboard/addons there are no files there at all (checked in Studio Code Server and shell).  I did reload both HA and the UI after each config.

Removing the integration, restarting and re-adding does not resolve the issue.

**Comment by dwainscheeren** [comment]
I dont follow you? The code is an example code.
