### ISSUE TITLE
Person name too long and cut off

### ISSUE THREAD

**Issue by GuyZipory** [dwainscheeren/dwains-lovelace-dashboard#343]
When I write my full name, the name cuts at the start and end.
![image](https://user-images.githubusercontent.com/11477714/145454256-6baf13dd-e72f-47c4-8fb7-75565bdfdef1.png)

**Comment by ikrowni** [comment]
Anyone looking into a fix for this?

**Comment by dwainscheeren** [comment]
This will be fixed in DD 3.0
