### ISSUE TITLE
Theme not working with v2021.12.0

### ISSUE THREAD

**Issue by coweater** [dwainscheeren/dwains-lovelace-dashboard#344]
I just installed the latest HA version and the theme no longer works. I uninstalled and reinstalled the theme and get the following error,
"custom element doesn't exist: dwains-dashboard".

I have loaded my previous rooms etc config but cant figure what is wrong.

**Comment by lukastillmann** [comment]
There is already a fix and a bugfix release on the way:

https://github.com/dwainscheeren/dwains-lovelace-dashboard/issues/340#issuecomment-991966614

**Comment by michealkd** [comment]
confirmed 2.0.5 fixed this issue. until a package is released you'll have to manually git pull the custom_components/dwains-dashboard folder.

**Comment by coweater** [comment]
Cheers gents, i found in chrome i could ctrl F5 and that fixed the issue after reading the link from @lukastillmann. I did pull the the CC from github to test and that worked also. The rooms are so much more useful than the new areas!

**Comment by coweater** [comment]
Check the custom components directory and ensure everything is there, also ctrl F5 to force a refresh of the cache - that worked for me after the HA upgrade.
