### ISSUE TITLE
Icons missing

### ISSUE THREAD

**Issue by BartEngelen** [dwainscheeren/dwains-lovelace-dashboard#346]
Hello all,

I updatet dwains-dashboard to v2.0.5 and updatet home assistant to 2021.12.1
But after this I still got no icons anymore on the buttons (on all pages).
![image](https://user-images.githubusercontent.com/17978789/146167758-8a3deb95-17ec-4a45-a719-36174e7e5c22.png)

Regards,

Bart Engelen

**Comment by dwainscheeren** [comment]
Which icons do you use?
Which theme do you got selected in DD?
Which theme do you got selected in HA itself?

**Comment by BartEngelen** [comment]
Hello,
1. I use the "mdi" icons set
![image](https://user-images.githubusercontent.com/17978789/146171321-d04ba06b-ca99-43ba-a1dd-ea0fc6174e47.png)
2. I use the theme: "Auto Mode (Dark/Light)
![image](https://user-images.githubusercontent.com/17978789/146172003-fbee3807-fff4-4948-a421-19dbcdc93b2a.png)
3. Theme selected in HA is "Backend-selected"
![image](https://user-images.githubusercontent.com/17978789/146172104-28c2b5ec-8bd0-4813-a28b-3aaec55c050b.png)

**Comment by BartEngelen** [comment]
Hello,

I changed the theme in HA to default and now it seems to work.
![image](https://user-images.githubusercontent.com/17978789/146174384-cb62cb5e-d29d-49c1-81cf-fdf98fdf177f.png)

![image](https://user-images.githubusercontent.com/17978789/146174444-121cb03e-72d4-4fd6-b0a0-fbd9b9b91997.png)

Regards,

Bart Engelen

**Comment by dwainscheeren** [comment]
Awesome :)

**Comment by BartEngelen** [comment]
Hello,
Can you tell me how I can switch between dark and ligth mode in DD ?
It seems my theme is always in light mode ?
Regards,
Bart Engelen

**Comment by dwainscheeren** [comment]
Inside integrations -> dwains dashboard settings you can select light, dark or auto. When sunset is active in ha you will get dark mode.
