### ISSUE TITLE
Dwains Dashboard PL version?

### ISSUE THREAD

**Issue by Krzysztonek** [dwainscheeren/dwains-lovelace-dashboard#353]
Hi @dwainscheeren,

You did a great job, Dwain! From now on Dwains Dashboard becomes My Favorite HA Dashboard!
However, seems the list of the language versions is still limited. Would be great if you allow me to do some translation into my native Polish and to officially publish the result. I believe, I'm not the only HA user from Poland, who would be happy to see your dashboard in his/her native language. 

I've been using HA since 2019, I'm an IT hardware engineer working for IBM Inc. Poland, with a wide technical background, ready to contribute to your DD project, spending some time on translating your DD into Polish.

If it sounds good to you, please let me know how to start with this task, giving me some hints on the technical requirements, how to find the source strings location, where to export the output files, how to share them with others, etc.

In fact, I've already prepared the `pl.yaml` file but first, it needs to be installed, reviewed, and checked.

Cheers,
Kris

**Comment by dwainscheeren** [comment]
You can make a PR?

**Comment by Krzysztonek** [comment]
Dwain,
[**Done**](https://github.com/Krzysztonek/Dwains-Dashboard-PL) as requested.

**Comment by dwainscheeren** [comment]
I don't see any open PR for it.

**Comment by misiuplus** [comment]
Hi, 
When will the pl version be available?

**Comment by Krzysztonek** [comment]
Hi @misiuplus ,

I already translated all the source files into Polish. They were successfully installed, checked, bugs and typos removed. Now they should be validated by @dwainscheeren and then might be included in the DD Setup
So, let's wait a bit for the feedback from @dwainscheeren and his final decisions.  :)

**Comment by misiuplus** [comment]
Hi @Krzysztonek good job!
I eagerly await @dwainscheeren decision

**Comment by TomaszDom** [comment]
I have submitted my own translation with a correct PR that was actually tested (hopefully no ellipses in the UI), is compatible with overall Polish translation of HA (rooms are "obszary", not "pomieszczenia") and doesn't contain gross mistakes like "Odświerz", I think this can be closed.
