### ISSUE TITLE
add Vacuum advanced view attributes 

### ISSUE THREAD

**Issue by nihonjin98** [dwainscheeren/dwains-lovelace-dashboard#357]
Hi I have the advanced_view set to true and and my vacuum robot map shows correctly and the brush hours text displays below the map but the attribute or entities are not showing the values for each of the hours left.  I can manually add these in my normal lovelace using the vacuum card but how and where do i put the stats attributes within your yaml configuration so that they display the values correctly?  Here is what i have so far in my rooms.yaml file:

vacuum: 
       advanced_view: 'true'
       entity: vacuum.viomi_v18_561f_robot_cleaner
       camera: camera.xiaomi_cloud_map_extractor
       stats:
         default:
            - attribute: viomi_vacuum.hypa_life
              unit: percent
              subtitle: Filter
            - attribute: viomi_vacuum.side_brush_hours
              unit: hours
              subtitle: Side brush
            - attribute: viomi_vacuum.main_brush_hours
              unit: hours
              subtitle: Main brush
            - attribute: viomi_vacuum.mop_hours
              unit: hours
              subtitle: Mop
         cleaning:
            - attribute: viomi_vacuum.clean_area
              unit: m2
              subtitle: Cleaning area
            - attribute: viomi_vacuum.clean_use_time
              unit: minutes
              subtitle: Cleaning time

But nothing is showing up.

**Comment by nihonjin98** [comment]
Never mind I found I can manually update the values within the custom components files.

**Comment by lbouriez** [comment]
Hey @nihonjin98 , can you share how did you solve this ?
