### ISSUE TITLE
Error on fresh install

### ISSUE THREAD

**Issue by bobvmierlo** [dwainscheeren/dwains-lovelace-dashboard#359]
Did a fresh install with very basic config. Only extra I've done is the calendar addon and I've followed the instructions by the letter.
Then after a restart of HA I get the following error when opening the dashboard. On the very first launch without any extra config the dashboard worked fine. I can't seem to figure out the problem.

```
This error originated from a custom integration.

Logger: custom_components.dwains_dashboard.process_yaml
Source: custom_components/dwains_dashboard/process_yaml.py:87
Integration: Dwains Dashboard (documentation, issues)
First occurred: 21:11:11 (1 occurrences)
Last logged: 21:11:11

Unable to include file /config/dwains-dashboard/views/partials/heading.yaml: [Errno 2] No such file or directory: '/config/dwains-dashboard/views/partials/heading.yaml'
```

**Comment by emile-bodin** [comment]
Which version did you install?
Latest version is 2.0.5

Look here: https://dwainscheeren.github.io/dwains-lovelace-dashboard/information/update.html
**Section 6 - Install Dwains Dashboard 2.0**

- Partial heading.yaml is deprecated! Replace it with a new card called dwains-heading-card.

**Comment by bobvmierlo** [comment]
I must have gotten some old yaml code somewhere, it's fixed now by changed the custom card.
