### ISSUE TITLE
zoOZ illuminance chosen as temp instead of temperature sensor

### ISSUE THREAD

**Issue by derekslenk** [dwainscheeren/dwains-lovelace-dashboard#364]
Should be self-explanatory in the images below. I have the [zoOZ 4-in-1 sensor](https://www.thesmartesthouse.com/products/zooz-z-wave-plus-4-in-1-sensor-zse40) which, among other things, reports illuminance and temperature. The whole device is in the Office area within HA, so I think the code is picking up the wrong thing to display first?

![image](https://user-images.githubusercontent.com/42957/147618625-e59f3ef1-5b83-4cf4-b49f-79d7cea7b62b.png)
![image](https://user-images.githubusercontent.com/42957/147618636-b8759f60-cd79-4231-8f04-de7d8184a678.png)
![image](https://user-images.githubusercontent.com/42957/147618640-77147415-5a55-41ca-a697-85528ff9f414.png)
![image](https://user-images.githubusercontent.com/42957/147618671-188acc06-4422-4797-8942-62c3d1ef0d5c.png)

**Comment by dwainscheeren** [comment]
This will be fixed in DD 3.0
