### ISSUE TITLE
Dashboard hangs on Fire HD 8 tablet and Onn 7 inch tablet

### ISSUE THREAD

**Issue by verwirrrung** [dwainscheeren/dwains-lovelace-dashboard#368]
I am using two Android tablets (Fire HD 8, On 7" tablet) as wall mounted dashboard for my home automation and I recently just installed Dwains dashboard, replacing my own. but when using the HA companion app or any web browser on the two android tablets and I open Dwains dashboard, the application hangs after a couple of seconds. otherwise, the app or browser just works fine when going/using any other HA component feature, or even my old dashboard. The issue does not show up on my Samsung S10 Android phone nor my apple products, and the dashboard works flawlessly on my Windows 10 PC. 

I don't see any error message, except for that one time that briefly popped up on the Onn tablet screen. - Android Webview Render Process Unresponsive. Thoughts?

- Fire HD 8
- On 7" tablet
- Samsung S10
- iPhone 12 Pro
- iPad 2020 model

**Comment by zerocritical** [comment]
I had been facing similar issue with Samsung A7 lite. I think I was able to resolve it by disabling the animations in developer mode.

Goto settings - About - software information 
Tab on build number 7 times
Once developer mode is on, go to settings - developer options
Scroll down to drawing options
Turn off all animation scale from 1x to off

Hopefully this works on other tablets too.
