### ISSUE TITLE
FR: Allow grouping of rooms by floor

### ISSUE THREAD

**Issue by confucius78** [dwainscheeren/dwains-lovelace-dashboard#370]
Hi all,

I have to say I am very impressed with this dashboard and I have to say it works great as-is!
Perhaps a a future improvement, it would be nice to be able to have a way of grouping different rooms, like in floors, and use that hierarchy in the ‘rooms’ navigation tab. If there are many rooms it can look a bit cluttered.

In addition, this grouping could be used to control lights and other controllable entities for that entire group. Hope I explain myself well 🙃

**Comment by iroQuai** [comment]
I also think it could help if there were sections possible! Small horizontal  line or something?

**Comment by confucius78** [comment]
Yeah that makes sense as well. My thought with having floors is that would declutter the interface a bit

**Comment by dwainscheeren** [comment]
This is possible in DD 3.0 :)

**Comment by bernydev** [comment]
After grouping by floors, how do I go about changing the orders of the floors. I currently have my devices grouped by rooms and then by 1st Floor and 2nd Floor. I am trying to position the 1st Floor group of rooms on top. Is this possible?
