### ISSUE TITLE
How to Dim the light from the room?

### ISSUE THREAD

**Issue by sbiitmc** [dwainscheeren/dwains-lovelace-dashboard#373]
Im configuring my rooms with your dashboard, but it seems that I can only turn the lights on/off, not dim the light like in the standard lovelace card.
Is there a work around for that?

Thanks for yoour great work!

**Comment by dwainscheeren** [comment]
Double click on the light or hold?

**Comment by sbiitmc** [comment]
Fast dbl click worked for me, thanks!
