### ISSUE TITLE
Custom Element Doesn't Exist on host computer

### ISSUE THREAD

**Issue by loca5790** [dwainscheeren/dwains-lovelace-dashboard#375]
Rebooting DD's I have no custom element cards avaialble local but on any remote devices on the IP it loads fine.

I have added an allow list on the url previously mentioned.  I have updated HAC's.  I have cleared cache.  I have checked yaml's and logs.  I have rebooted.

I am on an RPI4.  I did not notice the issue until a power failure but to be fair I never hook up an hdmi cable to the RPI4.  It's just a host.

**Comment by loca5790** [comment]
Just a follow up.... the dashboard loads on another computer and shows everything.  When I load it on the PI for the first time it initally glances the full screen and cards but then it updates to not available.

**Comment by dwainscheeren** [comment]
Clear browser cache

**Comment by loca5790** [comment]
> Clear browser cache

When I do the panels load for a split second and populate then the same error comes up.

**Comment by dwainscheeren** [comment]
No idea then, which browser do you use, chrome or firefox?

**Comment by loca5790** [comment]
It's on chrome on the PI.  Works on Safari and firefox on others on network.

**Comment by loca5790** [comment]
And..... I didn't touch anything came back after 20 minutes and it's working now?... no idea and nothing in logs.

**Comment by lbouriez** [comment]
I had the same issue on my laptop, was the cache

**Comment by dwainscheeren** [comment]
In 99.99% of the cases, its an cache issue
