### ISSUE TITLE
Dashboard not working anymore

### ISSUE THREAD

**Issue by mirkin1993** [dwainscheeren/dwains-lovelace-dashboard#380]
Hi,

Since today I got this error when opening the dashboard: 
while scanning for the next token found character '%' that cannot start any token in "/config/custom_components/dwains_dashboard/lovelace/plugins/dwains_dashboard.yaml", line 8, column 2

I haven't changed anything on my dashboard in weeks..

**Comment by dwainscheeren** [comment]
Hi,

Did you update anything else?

**Comment by mirkin1993** [comment]
Hi,

No I didn't update anything

**Comment by dwainscheeren** [comment]
Working again?

**Comment by confucius78** [comment]
I seem to have a similar issue with a room name. My daughters’ name was in the room name and it contains a ‘special’ character: ë. This seems to break the dashboard, as I am unable to open the page for her room.

I suspect it is related to me having installed HA beta this weekend. It was working fine before and I did not change the dashboard config files

**Comment by MrHasse** [comment]
> 
Updated to 2022.02 and its the same for me. Using swedish åöä on rooms don't open them. Renaming rooms "fixed" it.

**Comment by confucius78** [comment]
There's a fix on the way for this, if Dwain is able to look at the code we should see something next week or so

**Comment by dwainscheeren** [comment]
Check out #390
