### ISSUE TITLE
Alarm Panel "Alarmo" not shown correctly

### ISSUE THREAD

**Issue by TimoHornSerrig** [dwainscheeren/dwains-lovelace-dashboard#389]
Im using the Integration "Alarmo" (see https://github.com/nielsfaber/alarmo).  But the Alarm panel card is not shown correctly. At the standard lovelace it is shown correctly. 
![Alarm Panel 01](https://user-images.githubusercontent.com/94793014/152130604-825c321b-73af-4243-976e-6eb1b19d3fc2.jpg)
![Alarm Panel 02](https://user-images.githubusercontent.com/94793014/152130629-25017d65-eba6-4914-99d7-7d06ddef31ac.jpg)

**Comment by dwainscheeren** [comment]
See #367
