### ISSUE TITLE
[FR] More info in room icon

### ISSUE THREAD

**Issue by haplm** [dwainscheeren/dwains-lovelace-dashboard#39]
It would be great to see not only temperature, but also humidity, possibly also CO2 on each room icon. I have all these sensors for pretty much each room, but I need to drill all the way down to room Climate page to see the Humidity. CO2 is even worse, as it isn't recognised as climate (although it is, and very important one), and is grouped with 'other' sensors.

**Comment by dwainscheeren** [comment]
Which place do you mean with room icon. The buttons on the homepage?

**Comment by haplm** [comment]
Yes. Right now they only show temperature and motiion, right?

**Comment by dwainscheeren** [comment]
And open doors, open windows

**Comment by dwainscheeren** [comment]
Also take a look at #25 maybe these 2 FR can be merged.

**Comment by haplm** [comment]
IMO #25 is different. He is asking whether icons which are already there  could be visible all the time, with different icons assigned to each state (open/closed).

I'm asking for additional info to be placed on the button (humidity, CO2).

I understand that with more info displayed, the buttons may get crowded easily, but if you allow some degree of configuration around what should be displayed directly on the button, and what should be just on the climate page, it should be fine. User can choose.

Also - I plan to display the dashboard on 8" tablet, so I have a bit more room (or more precisely the text is more readable)

**Comment by dwainscheeren** [comment]
Okay now I understand, I will need to look into this. It's definitive possible but need to find a nice way to wrap a function around it with the correct config inside the `rooms.yaml` I will come back on it asap

**Comment by haplm** [comment]
Thanks!

**Comment by dwainscheeren** [comment]
What resolution does that 8" tablet have?

**Comment by haplm** [comment]
1280 x 800

(but I'm seeing the same thing in the browser on my computer)

**Comment by dwainscheeren** [comment]
This will be possible in DD 3.0.
