### ISSUE TITLE
TypeError: undefined is not an object 

### ISSUE THREAD

**Issue by MNLFDF** [dwainscheeren/dwains-lovelace-dashboard#391]
Logger: frontend.js.latest.202202030
Source: components/system_log/__init__.py:190 
First occurred: 07:18:02 (4 occurrences) 
Last logged: 07:18:02

http://192.168.0.5:8123/dwains_dashboard/js/dwains-dashboard.js:90:22170 TypeError: undefined is not an object (evaluating 't.config.dwains_dashboard.popup_cards')

I don’t use any pop-up cards.

**Comment by jov58** [comment]
Same error here after updating to HA 2022.2.3

Logger: frontend.js.latest.202202030
Source: components/system_log/__init__.py:190
First occurred: 22:20:46 (2 occurrences)
Last logged: 22:21:10
http://ip:8123/dwains_dashboard/js/dwains-dashboard.js:90:13803 TypeError: t.config.dwains_dashboard is undefined.

Is there anything I can/should do in the configs?

**Comment by dwainscheeren** [comment]
You can ignore that
