### ISSUE TITLE
German letters like äöü don´t work as room name

### ISSUE THREAD

**Issue by domi190399** [dwainscheeren/dwains-lovelace-dashboard#393]
If you use german letters like äöü in the rooms.yaml as a name these rooms will not open when you click on them. As a workaround, you can write for example "Kueche" instead of "Küche" but it would be nice to make the special letters usable or make different lines for the Name of the button and the corresponding part of the web address.

**Comment by SirUli** [comment]
Hi @domi190399 

this will be fixed in v2.0.6 to my understanding: https://github.com/dwainscheeren/dwains-lovelace-dashboard/pull/390

You can try when you enable the installation of Beta Versions in HACS which will allow you to install the v2.0.6

Best Regards, Uli

**Comment by dwainscheeren** [comment]
See #390
