### ISSUE TITLE
Home Assistant Button Entity Not Supported

### ISSUE THREAD

**Issue by Boh1** [dwainscheeren/dwains-lovelace-dashboard#394]
I have a device in HA that uses the 'new' button entity, but I can't successfully make that device work in DT.

My rooms.yaml concerning this device looks like this:

```  - name: Garage
    icon: mdi:garage
      device: button.garage_door_opener
    page_entities:
      columns: 2
      entities:
        - entity: binary_sensor.garage_entry_door
        - entity: binary_sensor.garage_door
 ```

But any attempt to 'press' the button via the DT UI results in an error message of:

`Failed to call service button/turn_off. Service not found.`

A earlier version of this code worked fine when the device type (in HA and DT) was 'switch'. This only became an issue _after_ changing the type to 'button' in both HA and DT.

Perhaps this more of a feature request than a bug, but thought I'd highlight this behaviour  regardless.

**Comment by dwainscheeren** [comment]
This will be fixed in 3.0
