### ISSUE TITLE
Camera setup

### ISSUE THREAD

**Issue by paulonHA** [dwainscheeren/dwains-lovelace-dashboard#397]
Hi,

I got some questions about how to properly sertup cameras. Currently I have 3 cameras (arlo) and 1 wired doorbell (arlo). All devices are connected over the base statiopn from arlo and everything is working properly so far in the main overview. However I'm not able to display the cameras and doorbell in the dwains-dashboard. The cameras are currently showing idle and the doorbell unavailable. When I'm adding the   main_menu: 'false' and live_view: 'false' I can see a still picture for the cameras. What can I do to get this running properly so that the cameras and doorbell are showing a live video? BTW I'm a total noob to all of this. Thx in adavance.

**Comment by dwainscheeren** [comment]
DD just uses the picture-entiy with a camera feed, so its not really related to DD.

**Comment by paulonHA** [comment]
Well thx anyway but i will delete your dashboard as it is quite useless without the cameras and they are working properly on the normal dashboard.

**Comment by dwainscheeren** [comment]
then something is not working with your cameras, maybe try dd 3.0 when its released it loads cameras in a new way.
