### ISSUE TITLE
Can't use ÆØÅ

### ISSUE THREAD

**Issue by microfix** [dwainscheeren/dwains-lovelace-dashboard#398]
Live in Denmark, we use æ ø å in room naming, but i cant call "bedroom" "soveværelse" 
When i do, and i open the dashboard, pushing the room tile that contain a æøå sign, nothing happens.
I expect it to open the room menu, under that specific room, i can push it if i call it bedroom. then i works. 

Btw hope you undestand, :)  And thanks for making this awesome app. Using it everyday.

**Comment by dwainscheeren** [comment]
Please try DD 2.0.7 and use the new title functionaliteit

**Comment by dwainscheeren** [comment]
https://github.com/dwainscheeren/dwains-lovelace-dashboard/pull/390
