### ISSUE TITLE
Footer/Navigation iOS

### ISSUE THREAD

**Issue by Piti8576** [dwainscheeren/dwains-lovelace-dashboard#399]
On my iPhone the Bottom Navbar is not good. 
Can you Set the Navigation higher so that is no issue with the navbar from iPhone?

![3DC801BE-158C-4C2E-9A04-477ADB95B4CC](https://user-images.githubusercontent.com/5464582/154131004-478cc3c5-e1d6-4f5c-9f60-7325f027cc4f.jpeg)

Latest Beta from Dashboard. 
iPhone 12 Mini

**Comment by dwainscheeren** [comment]
This will be possible in DD 3.0.
