### ISSUE TITLE
[FR] Extend climate with other climate sensors

### ISSUE THREAD

**Issue by haplm** [dwainscheeren/dwains-lovelace-dashboard#40]
It would be great to have following additional sensors on the climate page:
1) CO2
2) Dust
3) VOC (Chemicals)

Also it would be nice to have a separate tab (like 'All Lights') showing only climate data for the whole house (perhaps in form of larger badges for each room).

**Comment by dwainscheeren** [comment]
Are these 3 separated sensors so 3 entities? Can you show me the states of these so I can work something out for this.

**Comment by haplm** [comment]
Yes, they are. States is a number like this: 762.0.

Parsing it as a number and ignoring decimal points would be lovely

CO2 is typically between 400 and 4000
VOC is between 100 and 1000
Dust is between 1 and 255

**Comment by dwainscheeren** [comment]
This will be possible in DD 3.0.
