### ISSUE TITLE
State color page_entities

### ISSUE THREAD

**Issue by tuanha2000vn** [dwainscheeren/dwains-lovelace-dashboard#413]
![image](https://user-images.githubusercontent.com/2765517/156085369-12fb3ab6-8fcb-4f53-9764-1291f0ccd785.png)

Hi it's possible to set the color of the entity state in page_entities? On color: yellow, Off color: light blue

Thank.

**Comment by dwainscheeren** [comment]
This will be possible in dd v3 :)

**Comment by obonner** [comment]
Hi - Is this possible now? I can't figure out how to make it work.

**Comment by dwainscheeren** [comment]
Yes just use your own custom card and style that.
