### ISSUE TITLE
No Dashboard in any windows.

### ISSUE THREAD

**Issue by addboy58** [dwainscheeren/dwains-lovelace-dashboard#416]
I have no Dashboard in by PC, iPad or Eco show 15 since upgrading HS and operating system.

**Comment by dwainscheeren** [comment]
? Check your ha error log

**Comment by addboy58** [comment]
This what I see:

Logger: frontend.js.latest.202202031
Source: components/system_log/__init__.py:190
First occurred: 1:52:16 PM (2 occurrences)
Last logged: 1:54:38 PM

http://homeassistant.local:8123/dwains_dashboard/js/dwains-dashboard.js:90:13531 Uncaught TypeError: Cannot read properties of undefined (reading 'popup_cards')

thx
D

**Comment by dwainscheeren** [comment]
You can ignore that error.
