### ISSUE TITLE
Room link not working when using non english characters

### ISSUE THREAD

**Issue by JacoboSanchez** [dwainscheeren/dwains-lovelace-dashboard#420]
If I define a room like the following example having à, ò characters:
![image](https://user-images.githubusercontent.com/11249890/156557215-710a7720-40c9-45c4-97ce-2ead7bc58f9f.png)

And I click on the room icon;
![image](https://user-images.githubusercontent.com/11249890/156557339-dea7fa9a-d9c9-4d0d-8660-b2fc68336f3c.png)

The generated link on the browser does not open any new dialog with the room info:
![image](https://user-images.githubusercontent.com/11249890/156557445-65a559fa-27e0-44e3-b45e-992b4a33fa34.png)

**Comment by confucius78** [comment]
Hi,

this issue has been already resolved in the latest version, please have a look at #390

**Comment by JacoboSanchez** [comment]
Thank you and sorry for the duplicated issue.
I had the latest version installed but as examples in the documentation do not use the new title tag I did not know about them. 
Thanks again!
