### ISSUE TITLE
Multiple Lights in a room

### ISSUE THREAD

**Issue by domemshur** [dwainscheeren/dwains-lovelace-dashboard#437]
Can you only put one light in a room? It seems like I have to group all the lights per room. I would like to have more than one light per room.

Thanks

**Comment by dwainscheeren** [comment]
Its in the docs, did you read them? https://dwainscheeren.github.io/dwains-lovelace-dashboard/v2/information/faq.html#how-can-i-add-multiple-entities-for-example-lights-inside-1-room
