### ISSUE TITLE
Dwains dashboard didn't bring in contents of the lovelace dashboard

### ISSUE THREAD

**Issue by rdperkins** [dwainscheeren/dwains-lovelace-dashboard#441]
My Overview (Lovelace) has multiple views and >100 devices shown. Nothing came into Dwains' dashboard.

**Comment by rdperkins** [comment]
I uncommented what I thought was relevant, but when I click on the dashboard I get the following message "[Errno 2] No such file or directory: '/config/dwains-dashboard/addons/popups/cover/popup.yaml'". There is an addons folder but it's empty. What do I need to do?

**Comment by Nick-Case** [comment]
I'd guess you need to look through your configs. One of the example ones will have an "addon" called "popup" or "popups", delete or comment out that line, and it should work

**Comment by rdperkins** [comment]
I had done that and cleared the error. Dwain's dashboard show the one light and device I had in the rooms.yaml, but no other. Does that mean the dashboard isn't truly autogenerating and that I need to copy-paste and modify the file to manually add my devices?

**Comment by dwainscheeren** [comment]
Wait for DD v3 it will be 100% automatic generated.
