### ISSUE TITLE
V 3.0 Beta - Hidden Entities Still Show on Dashboard

### ISSUE THREAD

**Issue by LordNex** [dwainscheeren/dwains-lovelace-dashboard#448]
With the latest release of Home Assistant, they added the ability to hide entities without disabling them. When I try this under the 3.0 beta they still show up. If i disable them they then leave the dashboard.

**Comment by LordNex** [comment]
Ive also noticed that some of the non needed entities showing up. For isntance, My TP Link wall plugs have an LED that shows if its on or not. HA now brings that in as a controlable item. Which is fine but may not want to have viewed on each page. If I could disable it, it would still function and be there in the backend. but not up front on the dashboard. Unfortunatly you can only enable or Disable under DD3.0

**Comment by LordNex** [comment]
I’ve tried that. Selecting Hide does nothing at all. The only way to hide an entity from the DD is to disable it which causes it to loose all function.

For instance, I have a bathroom vanity light with 2 Zigbee bulbs in. With the new sysyatem I was able to create the ZHA group and then hide the individual lights and the group still worked. Now if I try , hide does nothing, and if I disable them, the group quits functioning. Please reopen and give this a try it’s easy to spot. I’m really surprised you “beta testers” haven’t discovered it yet.


On Apr 12, 2022, at 3:42 AM, Dwain Scheeren ***@***.***> wrote:

﻿

In dd v3 you can hide or disable an entity by clicking the three dots below the entity card after you enabled edit mode.

**Comment by dwainscheeren** [comment]
![image](https://user-images.githubusercontent.com/3868853/163025199-c0182663-0f41-4e75-a318-a77fc239474f.png)
Hide entity in DD you must use.

**Comment by LordNex** [comment]
Ok I finally found it. Although it's not where most people I would think would look. Just my suggestion but if there was a way you could tie that in with HAs built in ability to hide entities I think would make more sense logically. But that's again for your response and help!

**Comment by wtstreetglow** [comment]
I would definitely second what you are saying @LordNex I just stumbled upon the same thing

**Comment by dwainscheeren** [comment]
Not sure, but its quite clear in the documentation?? https://dwainscheeren.github.io/dwains-lovelace-dashboard/v3/information/configuration.html#how-to-hidedisable-entities

**Comment by wtstreetglow** [comment]
Definitely agree @dwainscheeren . Original comment deleted. I think I just thought, if you chose hide from the "devices and services" of home assistant that it would hide it from coming onto your dashboards but now I see that is not even how the original default "overview" dashboard works. Thank you for your clarifications.

**Comment by Ulrar** [comment]
Hi,

Is there a way to automatically hide entities that are hidden in HA, or to sync the state periodically or with a service ?
I ask because I have around a hundred hidden entities in HA and I'd really rather not go through that again in DD if at all possible.

**Comment by wtstreetglow** [comment]
A couple of us have asked that one. It's seeming like there is not but let's see what the master says. He has done such a good job with his efforts.

**Comment by LordNex** [comment]
Thanks kind of the lines I was going down. I didn’t know about the second although I read the how too I must have missed that part. But I can see having them in two places could be confusing  to some others as well.

I’m happy with doing things the approved way. But also agree with wtstreetglow and lemonnier that it would be nice to toggle either and end up with the same result so that people are not confused by usage.


On May 6, 2022, at 7:04 AM, wtstreetglow ***@***.***> wrote:

﻿

A couple of us have asked that one. It's seeming like there is not but let's see what the master says. He has done such a good job with his efforts.
