### ISSUE TITLE
LG WebOS not open panel

### ISSUE THREAD

**Issue by Saentist** [dwainscheeren/dwains-lovelace-dashboard#451]
LG WebOS Smart TV cannot open dashbord
it show YAML code on red background.

**Comment by dwainscheeren** [comment]
Try DD 3.0

**Comment by Saentist** [comment]
No success with ver 3
![IMG_20220425_200837.jpg](https://user-images.githubusercontent.com/16975883/165138875-024c8ae9-88ba-47dc-a93c-99c95f6fbf7d.jpg)

Even on sidebar is missing

**Comment by Saentist** [comment]
There is a misunderstood.
Panel work
![image](https://user-images.githubusercontent.com/16975883/165160357-39894314-f272-4932-973b-87257abbb23a.png)

but do not open on Embedded browsers 
I test on my LG SmartTV and on Sony BlueRay Player

https://developers.google.com/web/tools/lighthouse
Lighthouse say that page is too big, and maybe browser refuse to load it completly .
