### ISSUE TITLE
Display of timestamps in scenes

### ISSUE THREAD

**Issue by fwmarcel** [dwainscheeren/dwains-lovelace-dashboard#457]
first of all, thank you for this absolutely brilliant update from DD.
I love it.

However, something still seems to be going wrong with the rendering of scenes.
Instead of a "local" representation, a timestamp is represented as follows.
So that the time even goes beyond the edge of the card.
A representation according to the different possibilities, as this can also be made in the settings would be super.

Many thanks in advance!

![image](https://user-images.githubusercontent.com/22275913/164986597-4c00ff26-afcf-478b-9d5c-d240c046ad98.png)

**Comment by dwainscheeren** [comment]
Something for 3.1 indeed :) For now you can replace the card with a own button-card templated to fix it or any other card you like/prefer. Maybe use: https://github.com/dwainscheeren/dwains-dashboard-blueprints/tree/main/card-blueprints/normal-cards/scene-button-card

**Comment by fwmarcel** [comment]
thanks for the quick tip

**Comment by dwainscheeren** [comment]
Fixed in next release.
