### ISSUE TITLE
Not able to change order of Lovelace entity 

### ISSUE THREAD

**Issue by S10XtremeNLow** [dwainscheeren/dwains-lovelace-dashboard#458]
When adding a Lovelace entity, not able to change the order.

**Comment by dwainscheeren** [comment]
This will be possible in 3.1 :) See: https://github.com/dwainscheeren/dwains-lovelace-dashboard/discussions/456

**Comment by S10XtremeNLow** [comment]
> This will be possible in 3.1 :) See: #456

Awesome! This is an amazing dashboard.

**Comment by mvenus2** [comment]
> Owner

I am running 3.1.1 but unfortunatly i dont see an option to change the order of my cards. Am i missing something?

**Comment by alexanderwassberg** [comment]
> > Owner
> 
> I am running 3.1.1 but unfortunatly i dont see an option to change the order of my cards. Am i missing something?

Same here.
