### ISSUE TITLE
Wheather forecast can't be disbled again

### ISSUE THREAD

**Issue by Peenpower** [dwainscheeren/dwains-lovelace-dashboard#463]
After setting up a fresh install of V3, the first thing added the wheater. 

After this refreshed the page and wanted to disable it again, clicked on the option tab removed the entity and clicked save. But the button isn't doing a thing.

**Comment by Peenpower** [comment]
https://youtu.be/HcANY6wYr-g

**Comment by dwainscheeren** [comment]
Fixed in 3.1 :)
