### ISSUE TITLE
Empty device views

### ISSUE THREAD

**Issue by lseufer** [dwainscheeren/dwains-lovelace-dashboard#464]
Hi there,

great work on V3. 

Is there a way to hide automatically hide devices groups that have no devices? Fo example, I have no camera, no "select", no scene and I'd like to hide those groups.

Cheers

**Comment by dwainscheeren** [comment]
Hello, when it's good if you don't got any device in these 'domains' it won't show them.

**Comment by lseufer** [comment]
I wasn't clear, sorry! Look, here I don't have thermostat but the "group" still appears. Is there a way to hide it without modifying the code?
Thanks!

<img width="1047" alt="Capture d’écran 2022-04-27 à 15 45 18" src="https://user-images.githubusercontent.com/7261297/165533006-ace69aec-216c-4df3-81bd-51a4d651cb52.png">

**Comment by dwainscheeren** [comment]
Do you really have no thermostat or did you disable them in dd?

**Comment by lseufer** [comment]
No thermostat or camera or button in HA.

**Comment by lseufer** [comment]
OK my bad they were hidden in HA. 

If you can make it possible to hide domains that would be very nice.

**Comment by dwainscheeren** [comment]
I can look for an option. Now because you got hidden entities inside the domain/device it still shows it so you can open it, enter edit mode an un-hide the entities. If I would hide the button of the device when all entities are hidden you never can un-hide them through UI that's why :)

**Comment by dwainscheeren** [comment]
You can disable them now in 3.1 :)
