### ISSUE TITLE
Feature Request: Global DD name and Area DD name

### ISSUE THREAD

**Issue by mrjack711** [dwainscheeren/dwains-lovelace-dashboard#465]
It would be very useful to have the ability to set a global DD name and an area DD name for each entity or just have an option to show the full HA entity name when using the bar that show currently on entities.

When looking at entities in different areas (e.g. Master Bedroom) it's cleaner to see "Bedside Lamp" rather than "Master Bedroom Bedside Lamp".
In the bar that shows all entities currently on, its better to have the full name to differentiate between devices from different areas.

Great integration by the way.

**Comment by dwainscheeren** [comment]
Not sure what you mean but you can add friendly dd names to entities already

**Comment by mrjack711** [comment]
Apologies, i'll try and give an example.

Within the Living Room area, i currently have the following light entities renamed with DD names (their full HA entity names have "Living Room " as a prefix:

![image](https://user-images.githubusercontent.com/18040642/165398741-28185de5-ac2d-45f3-b026-a59e0fe8748e.png)
This works great within the individual areas as I know that these belong to Living Room and they look cleaner without the prefix.

When i view these here, i have no idea where they belong as i removed the "Living Room" prefix from the full HA entity name:

![image](https://user-images.githubusercontent.com/18040642/165398922-68bf399c-d41f-4218-9587-4e4f4077aaf8.png)
It would be useful to know which area the entities belong to in here.

**Comment by dwainscheeren** [comment]
It's on the list of 3.1 to show the corresponding area there in that popup to each entity :)

**Comment by mrjack711** [comment]
Sounds perfect, many thanks
