### ISSUE TITLE
General Lovelace problem after DD install

### ISSUE THREAD

**Issue by confucius78** [dwainscheeren/dwains-lovelace-dashboard#468]
Hi,

just installed DD v3.0, HA is running on RPi 4b

I am noticing a funtionality drop after I have opened DD.

It looks like other dashboard pages outside DD are not allowing entity popups to load correctly (state history does not load). 

The only workaround is to open the dashboard page, reload and then click the entity. After that it shows the state history.

App cache was cleared. The issue seems to occur only if DD has been opened and did not exist in DD 2.07

**Comment by johannwilken** [comment]
I have the same issue. Other dashboards are unresponsive at times and generic cameras are not loading.

**Comment by dwainscheeren** [comment]
How many entities do you got in your ha setup? And what is the devices you are viewing the dashboard with ? (like Intel i7, 8gb memory etc)

**Comment by confucius78** [comment]
Mostly on iOS, which is where the issue is on iphone, ipad pro 2018. 

I do however experience it on my pc as well, which is i7 12700 with 32 GB and a 3080 nvidia card. 

Speed client side doesnt seem to be the issue 😇

**Comment by dwainscheeren** [comment]
See #478 move there to discuss the issue :)

**Comment by johannwilken** [comment]
Hi Dwain,

I have about +-100 entities, not all of them in DD. I Run HA baremetal on
an i3 8gb RAM and 240gb SSD.

Then for viewing is on 2x samsung tab a8, Samsung S21 and Huawei P20. My
workstation where I do all the stuff is an dual xeon 30gb RAM and 240 SSD.
All doing the same.

I also have an issue where if DD is my main view when opening the app on my
phone it will open fine but no popup cards work. Then if close the app and
reopen the it doesnt want to open.

Regards,

Johan
