### ISSUE TITLE
ip ban triggered when clicked on dashboard

### ISSUE THREAD

**Issue by Shiroe93** [dwainscheeren/dwains-lovelace-dashboard#469]
i've recently istalled this dashboard and i have a strange problem 
 everytime i click on it from the side panel it triggers my ip ban integration

**Comment by dwainscheeren** [comment]
Do you got something in your main HA configuration regarding try login limit or something like that? Using nabu casu or?

**Comment by Shiroe93** [comment]
That's a bummer I was looking at your dashboard from the moment I started using home assistant but at at frist I was put of by the setup so now that you automated a was happy to be able to try it
Anyway if you find a solution please let me know
I'm sure that I will be able to solve this issue by disabling the ip ban but with an exposed domain I don't want to give unlimited login try to any potential intruder

**Comment by dwainscheeren** [comment]
Can you maybe whitelist your local ip ?

**Comment by Shiroe93** [comment]
I want to do it for a while now but I was never able to find a method that works

Also I've noticed another issue when I cast the dashboard on another display like the nest hub it gives the same cache error that you mentioned in your main page the problem it that I don't think is possible to refresh the page while casting

**Comment by dwainscheeren** [comment]
Could you post a photo here of the message on the nest hub? :)

**Comment by Shiroe93** [comment]
This one ![P_20220428_040551.jpg](https://user-images.githubusercontent.com/56954468/165661941-56db3c3f-abeb-4b73-a84f-ce1c438ce9a7.jpg)

**Comment by lbouriez** [comment]
FYI, I am having the same issue with Dwains v3, keeps banning me.
There are no way for now to add a whitelist in HA so I just disabled the ban functionality

**Comment by Shiroe93** [comment]
That seems to be the only solution but it's a bit risky if your home assistant instance is exposed to the outside network
