### ISSUE TITLE
Generic cameras loading issue

### ISSUE THREAD

**Issue by johannwilken** [dwainscheeren/dwains-lovelace-dashboard#470]
Good day Dwain,

I have installed your dashboard and i am very impressed.

I have one issue where some of my generic cameras are not loading. Even refreshing browser does not help.
![Generic cameras](https://user-images.githubusercontent.com/65971874/165278135-b52c2ad6-bf98-4d7b-9e8d-5a368345dc70.JPG)

Cameras are working fine in other dashboards.

Please advise?

**Comment by dwainscheeren** [comment]
Yeah this is a hard one, had this in v1 and v2 too. In other dashboard which lovelace card do you use for the cameras? Could you share the YAML code with me

**Comment by johannwilken** [comment]
Hi Dwain,

Thanx for the reply.

im using the following code, its a normal picture-glance card:

camera_view: auto
type: picture-glance
entities:
  - entity: binary_sensor.living_room_motion
  - entity: light.living_room_light
  - entity: binary_sensor.stairs_motion
  - entity: binary_sensor.guest_toilet_motion
  - entity: binary_sensor.kitchen_motion
camera_image: camera.cube

I also tried to add this card to your dashboard and it didn't even load.

If there something you want me to test, i can do so.

Hope this helps?

Kind regards,

Johann
