### ISSUE TITLE
Incoherence climate list & numbers on home tab

### ISSUE THREAD

**Issue by AlexandreLogist** [dwainscheeren/dwains-lovelace-dashboard#472]
There is an incoherence in the home tab counting and showing the on/off climate devices:

Version: 1.24.5

Sometimes all are showing on in the number icon, but only 2 are on for example here
![_ALO_2022-04-26 16_40_42](https://user-images.githubusercontent.com/5881465/165326901-2df9b163-4b32-495a-b412-db65021b61fb.png)

Other moments it shows the off devices as being on and when clicking it it shows only the off devices...
![_ALO_2022-04-26 16_45_25](https://user-images.githubusercontent.com/5881465/165327297-90f6c801-6994-4b46-ab92-eaa8e4d0fe70.png)

**Comment by dwainscheeren** [comment]
Fixed in 3.1 :)
