### ISSUE TITLE
[FR]: Possibility to configure mushroom card settings for each entity separate

### ISSUE THREAD

**Issue by smarthomejunkie** [dwainscheeren/dwains-lovelace-dashboard#476]
Currently, you can replace the light cards with custom mushroom cards if you want.
In that case, all light cards have all mushroom options (show color, etc) enabled. It would be super nice if we still can change these settings for each entity separately, so for instance for one lightbulb you want to see the color control, and for another lightbulb you only want to see the temperature control. As far as I see now, you cannot alter these settings if the mushroom card is used in conjunction with DD.

**Comment by antonoal** [comment]
I guess you used blueprints to replace light cards with mushroom cards. They are fixed. You can either create your own blueprint with different settings, or (the way I did it) use UI editor to replace the card. 
instead of clicking Dwain Dashboard Blueprint, click Lovelace Card in the menu when you clicked Edit Entity on a light you want to change. Then select Mushroom Light card.

**Comment by dwainscheeren** [comment]
How did you get to this if I may ask? :) Did you also tried going to an area for example, enable edit mode, underneath a light click on three dots (a light with already the global mushroom blueprint applied) then click on edit card then you cant select lovelace and then mushroom to override it?

**Comment by smarthomejunkie** [comment]
This is the path that I followed:
* First applied Dwains blueprint for Mushroom Light card to all the light entities
* Then clicked on an Area (In my case Living Room)
* Click within the area on the three dots
* Click Enable Edit mode
* Click on a light card on the three dots
* Click on Entity Card
* Click on Lovelace Card
* Select Mushroom Light Card
* Set all the settings in the Visual Editor
* Click Submit
* Click on the three dots again for the same light card within the area
* Click Entity Card
* This results in the error above.

**Comment by dwainscheeren** [comment]
Thanks! thats a bug then I gonna patch it in next release :D

**Comment by dwainscheeren** [comment]
Fixed this in 3.1 :)
