### ISSUE TITLE
Using via Home Assistant Cloud - Crash

### ISSUE THREAD

**Issue by Glen-Hart** [dwainscheeren/dwains-lovelace-dashboard#483]
Hi,

My mobile connects and works OK, connected to the same network via WIFI.
However, when connecting via Home Assistant Cloud, I get the following:

Customer element doesn't exits: dwains-dashboard-layout.

titel: Home
icon: mdi:home
path: home
type: customer:dwains-dashboard-layout
Cards:
   - type: customerLhomepage-card

**Comment by dwainscheeren** [comment]
Try resetting the cache of your browser.

**Comment by GlenvdHart** [comment]
Many thanks.
As an FYI. I was using Android 12. I ended up having to clear both the App cache and data to make it work with home assistant cloud.
