### ISSUE TITLE
Custom element doesn't exist

### ISSUE THREAD

**Issue by BartEngelen** [dwainscheeren/dwains-lovelace-dashboard#492]
Hello,
Everytime I log into my home assistant I got this error:
![image](https://user-images.githubusercontent.com/17978789/165908164-1e854cac-af5d-485b-b882-da5586b66335.png)
Clearing the cache will solve the problem but I need to do this everytime I logged in to Home Assistant.
Kind regards,
Bart Engelen

**Comment by dwainscheeren** [comment]
Using home assistant through a proxy like cloudflare?

**Comment by BartEngelen** [comment]
No I don't use cloudflare but I use nginx proxy manager on my Home Assistant can this be the problem?

**Comment by dwainscheeren** [comment]
Seems like its a caching issue so I would look into that.

**Comment by dwainscheeren** [comment]
Solved?

**Comment by bleugray** [comment]
Same issue just started for me today.  I am on 2022.6.0

does appear to be a caching issue with the use of nginx proxy manager?  connecting via IP directly doesn't exhibit the issue.

disabled "asset caching" so we'll see

**Comment by alligator999** [comment]
Hi,
got today the same problem. Purging Cloudflare cache solved the problem.

**Comment by yhalevi** [comment]
same problem

**Comment by dwainscheeren** [comment]
See: #726
