### ISSUE TITLE
Disable edit mode

### ISSUE THREAD

**Issue by zamuta** [dwainscheeren/dwains-lovelace-dashboard#493]
Hi, can I hide this buttons for non admin users?

![ha_scr](https://user-images.githubusercontent.com/5044691/165930811-060b311e-b9cf-489e-b01f-993bd8183087.png)

**Comment by dwainscheeren** [comment]
For now this is not possible. I can look into it for a next release

**Comment by dwainscheeren** [comment]
Fixed it in 3.1. Now only people with admin role can see edit mode :)
