### ISSUE TITLE
Grouped light entity does not show up

### ISSUE THREAD

**Issue by mouledla** [dwainscheeren/dwains-lovelace-dashboard#498]
So I have a light which has 3 bulbs in them. The light should be used as 1. I have grouped them in my configuration.yaml file and this workes as it should work. However in DW version 3 the light entity does not show up in my Lights category, they only come as 3 separate lights. I would like to have only one switch for these light, how can i achieve this?

![image](https://user-images.githubusercontent.com/73481608/166114764-d0628bec-bd32-4fad-b8e7-6e2086409593.png)

![image](https://user-images.githubusercontent.com/73481608/166114731-e5a4c9dc-4237-48be-94eb-b10dfb60c9c7.png)

**Comment by ghost** [comment]
Add a unique_id to your group and assign the group to a room.  It will work as you want.

![2F6CAEBD-2694-41F1-9790-D5B70A5BBB1A](https://user-images.githubusercontent.com/83040228/166117009-d642029b-97d1-4b20-b441-1bb7d77db730.jpeg)

**Comment by mouledla** [comment]
This worked for me! thank you!
