### ISSUE TITLE
[FR or BUG] No smoke detector icon

### ISSUE THREAD

**Issue by giuliandenicola1** [dwainscheeren/dwains-lovelace-dashboard#500]
When I was using DD2 if a smoke detector was going off I could see an icon within that area on the dashboard. Now in DD3 I do not see that icon anymore. 

![IMG_F90C39CA0675-1](https://user-images.githubusercontent.com/67443916/166215388-8ae5991d-3824-47c5-9c75-c76d8948e188.jpg)

**Comment by dwainscheeren** [comment]
Can you show me the state attributes of that entity in developer tools -> states?

**Comment by giuliandenicola1** [comment]
You mean this, right?
![A81F2241-26B3-4375-BCC9-D557C56BB105](https://user-images.githubusercontent.com/67443916/166256081-3273a8db-eeb0-411f-b671-1f156c298b42.jpeg)

**Comment by dwainscheeren** [comment]
Added them in 3.1 :)
