### ISSUE TITLE
No space between custom and auto generated cards.

### ISSUE THREAD

**Issue by giuliandenicola1** [dwainscheeren/dwains-lovelace-dashboard#501]
When you add a custom card within a category then it will be directly above the auto-entities no space in between. 

![IMG_0042656ABD0C-1](https://user-images.githubusercontent.com/67443916/166215908-c4b23577-fde2-46bb-9be2-83422106fcef.jpeg)

**Comment by dwainscheeren** [comment]
Fixed in 3.1
