### ISSUE TITLE
Cards cannot be removed through UI

### ISSUE THREAD

**Issue by giuliandenicola1** [dwainscheeren/dwains-lovelace-dashboard#502]
When you add a card within a category you cannot remove it anymore through the UI, but you can remove the yaml file and it will be removed. 

https://user-images.githubusercontent.com/67443916/166216145-e8b002ac-e66e-4f32-b978-185efd86746e.mov

**Comment by dwainscheeren** [comment]
Thanks! Fixed in 3.1
