### ISSUE TITLE
[FR] Hide/unhide/add categories

### ISSUE THREAD

**Issue by giuliandenicola1** [dwainscheeren/dwains-lovelace-dashboard#505]
Some categories in the devices tab are empty, my thoughts on this are: 

- Automatic hiding of empty categories/categories with hidden or disabled entities, only visible in edit-mode.
- Manually hide/unhide categories
- Automatic unhiding when a card or entity is added to the category

**Comment by dwainscheeren** [comment]
I've added the option to hide them in 3.1 So an user can hide them by hand their self. Good? :)

**Comment by giuliandenicola1** [comment]
Yeah perfect, the automatic thing just came to mind for convenience. It’s not necessary. :)
