### ISSUE TITLE
No options menu

### ISSUE THREAD

**Issue by giuliandenicola1** [dwainscheeren/dwains-lovelace-dashboard#507]
In the devices tab om my phone (iOS app or Safari) when I press the 3 dots in edit-mode I won’t get a menu with option’s but instead it will go to the page.

https://user-images.githubusercontent.com/67443916/166219920-3852f2ad-9107-49c5-b047-d8f7e51a3981.mov

**Comment by dwainscheeren** [comment]
Nice catch, fixed it in 3.1 :)
