### ISSUE TITLE
[FR] Top entities

### ISSUE THREAD

**Issue by giuliandenicola1** [dwainscheeren/dwains-lovelace-dashboard#511]
Having the possibility to add a navigation path to the alarm entity in the left corner.
<img width="277" alt="Schermafbeelding 2022-05-02 om 18 59 26" src="https://user-images.githubusercontent.com/67443916/166291478-45867364-3221-4814-8254-1ba134ae350d.png">

For example if I made a custom alarm page (/dwains-dashboard/more_page_alarm).

Edit: And might as well be handy for the weather entity if someone made a custom weather page or home climate page maybe.

**Comment by dwainscheeren** [comment]
The idea is that you do this in a custom popup you can do that for persons, weather and alarm.

**Comment by giuliandenicola1** [comment]
I have just tried some pop-ups and you are right pages are not that necessary anymore (for me). 

Although for now it's only possible to add the pop-up card to the alarm through YAML. In the beta you did add persons and weather to the categories but not (yet) alarm.

**Comment by dwainscheeren** [comment]
Can you assign an alarm to an area?

**Comment by giuliandenicola1** [comment]
Not that I know of, it has no unique ID.
![IMG_E3050F9B4E12-1](https://user-images.githubusercontent.com/67443916/166450671-7d9ced65-eaea-4739-953b-504054cce53e.jpeg)
