### ISSUE TITLE
[FR] Entity View Preferences

### ISSUE THREAD

**Issue by brandon-claps** [dwainscheeren/dwains-lovelace-dashboard#512]
Would be awesome to have a setting on an entity whether you want it to reflect on the main area icon for its state. For example, I have a subwoofer that is on all the time and I wouldn't want it's on state showing on the area card, just the things I care about seeing if they've been left on.

In addition, allow an entity to not show in the count at the top of the dashboard icons. For example, if I had a specific lock that was always unlocked, I wouldn't want it to show as unlocked in the dashboard.

This is all in the spirit of focusing on only those things that are important.

**Comment by dwainscheeren** [comment]
This is possible in 3.1 :) Then you can exclude entities, this means that they are not used for the view for on devices.

**Comment by brandon-claps** [comment]
WONDERFUL! Any thoughts on when you're releasing 3.1?

**Comment by dwainscheeren** [comment]
This week :)
