### ISSUE TITLE
[FR] Entity name setting for devices screen and main dashboard

### ISSUE THREAD

**Issue by brandon-claps** [dwainscheeren/dwains-lovelace-dashboard#513]
When using the icons at the top of the main dashboard, it reflects the DD name. It would be good if you can customize the name separate for this and the devices screen.

Use case: when you’re in an area you likely want to just call it “TV”, and there are more than one “TV” in different areas. When using the icon at the top or the entity screen, you can’t identify which TV it is
Specifically.

An alternative option would be adding the area to the card in those views to identify.

**Comment by giuliandenicola1** [comment]
Duplicate? #504

**Comment by brandon-claps** [comment]
Yes, this is a duplicate of the last item with the lamp example. Thanks!
