### ISSUE TITLE
[FR] Show Header always - just load content

### ISSUE THREAD

**Issue by xBourner** [dwainscheeren/dwains-lovelace-dashboard#515]
Hi,

the header keeps being loaded after all other elements. This keeps all content under the header being pushed down.
Sometimes its hard to hit the correct button when the header pushes it down.

For me it takes 1-2 seconds longer to load the header than everything else.

Would be great if the header card (container) would be always visible. Only contents like lights, persons etc. would be dynamically loaded.

**Comment by dwainscheeren** [comment]
fixed in 3.1
