### ISSUE TITLE
[FR] Add sorting in blueprint overview

### ISSUE THREAD

**Issue by xBourner** [dwainscheeren/dwains-lovelace-dashboard#519]
please add some sorting of blueprints. now that all blueprint types are shown in the same place it would be better for visibility when you could add sorting by blueprint type. within the types it should be sorting alphabetically.

so on more page there should be more page blueprints on top which are sorted alphabetically. then comes cards and then replace cards.
on entity cards there should be card blueprints (sorted alphabetically) then replace cards and on bottom should be more page blueprints.

the blueprints you can use in the section should be always on top and then sorted alphabetically. so users with many blueprints dont need to search that long

**Comment by dwainscheeren** [comment]
fixed in 3.1
