### ISSUE TITLE
Button for Home assistant menu do not use theme

### ISSUE THREAD

**Issue by ghost** [dwainscheeren/dwains-lovelace-dashboard#525]
In the navigation bar, the button to open the Home assistant menu, does not take the color of the theme.

![F53A92A3-55C0-475A-B04E-85B908B71989](https://user-images.githubusercontent.com/83040228/166698634-d5bf83af-cb0d-429f-87c6-2902be445c3f.jpeg)

**Comment by dwainscheeren** [comment]
Its by design so the button sticks out of the other buttons.
