### ISSUE TITLE
Show sensors (like windows and alarms) in top bar (V3)

### ISSUE THREAD

**Issue by iroQuai** [dwainscheeren/dwains-lovelace-dashboard#527]
Another minor issue on otherwise wonderful V3...

Is it possible to bring back the sensor badge in the top bar if status is something else than "off"? Stuff like open windows, smoke sensors that are going off, stuff like that.

I could find an older issue submitted where the [same request is made for V2](https://github.com/dwainscheeren/dwains-lovelace-dashboard/issues/175). As long as I remember it was present in V2 and I loved it!

**Comment by dwainscheeren** [comment]
They now show in the house information card?  Open window, door etc.

**Comment by iroQuai** [comment]
If I open a window in my living room, it shows in the entities list of that area (green arrow) but not on the main area card and top bar (red arrows)

![Dwain example 1](https://user-images.githubusercontent.com/7004624/166813047-d29fa86e-ad91-4025-84f4-cde9b3f743a6.jpg)

**Comment by dwainscheeren** [comment]
Then you don't got that binary_sensor in HA set to show as window ;)

**Comment by iroQuai** [comment]
It was that simple... 
thanks a lot! fixed the problem. Everything works!
