### ISSUE TITLE
Main panel remains blank

### ISSUE THREAD

**Issue by Miguelin96** [dwainscheeren/dwains-lovelace-dashboard#528]
After updating to the new version of Home Assistant the main panel remains blank

Home Assistant Core 2022.5.0
Home Assistant Supervisor 2022.05.0
HomeAssistant OS 7.6

<img width="1078" alt="image" src="https://user-images.githubusercontent.com/54648539/166832839-900abdb8-e1d7-450b-a21f-882722c294ed.png">

**Comment by dmzyx123** [comment]
The same situation occurs, it should be not adapted to core5.0

**Comment by dwainscheeren** [comment]
Do you got entities assigned to an area? And do you got an error in the HA error log or in the browser console log? Please post it here so I can investigate.

**Comment by dmzyx123** [comment]
> Do you got entities assigned to an area? And do you got an error in the HA error log or in the browser console log? Please post it here so I can investigate. 

It can be displayed normally before, but when it is updated to core5.0, the cover page is blank and the page of the device is displayed normally![Screenshot_2022-05-05-15-39-58-324_io.homeassistant.companion.android.png](https://user-images.githubusercontent.com/54948838/166880727-5167f641-d48b-4d31-8730-c49d0e7e7806.png)![Screenshot_2022-05-05-15-39-56-292_io.homeassistant.companion.android.png](https://user-images.githubusercontent.com/54948838/166880742-48e426ee-9df2-4b60-847c-e30f6ed865f5.png)

**Comment by giuliandenicola1** [comment]
I’m also running core 2022.5.0 but DD3 works fine. I’m not running supervisor tho. 

![6B543099-B9CC-4570-9393-738697B2FB34](https://user-images.githubusercontent.com/67443916/166891019-e73806e3-d718-400b-972d-eb45b30f573c.jpeg)

**Comment by dwainscheeren** [comment]
Please check your ha erorr log. Its an error in y our system

**Comment by B2i** [comment]
Same problem for me.
No log on HA.
Firefox log : 

`Uncaught (in promise) TypeError: this._hass.states[m] is undefined
    render dwains-homepage-card.js:3694
    update lit-element.js:220
    performUpdate updating-element.js:555
    _enqueueUpdate updating-element.js:508
15 dwains-homepage-card.js:3694:10
`

> Uncaught (in promise) TypeError: this._hass.states[m] is undefined
    render dwains-homepage-card.js:3694
    update lit-element.js:220
    performUpdate updating-element.js:555
    _enqueueUpdate updating-element.js:508
    requestUpdateInternal updating-element.js:474
    set updating-element.js:204
    _loadData dwains-homepage-card.js:2408
    connectedCallback dwains-homepage-card.js:2016
    connectedCallback typography.js:181
    M lit-html.js:6
    k lit-html.js:6
    T lit-html.js:6
    _$AI lit-html.js:6
    Dt lit-html.js:6
    update lit-element.js:6
    performUpdate reactive-element.js:6
    scheduleUpdate reactive-element.js:6
    _$E_ reactive-element.js:6
    requestUpdate reactive-element.js:6
    o reactive-element.js:6
    m reactive-element.js:6
    J lit-element.js:6
    ee dwains-dashboard-layout.js:3
    E typography.js:181
    t typography.js:181
    s ha-logbook.ts:29
    u ha-logbook.ts:29
    u ha-logbook.ts:29
    d ha-logbook.ts:29
    l hui-error-badge.ts:22
    value hui-masonry-view.ts:44
    value hui-masonry-view.ts:44
    value hui-masonry-view.ts:44
    performUpdate app.53b92002.js:1248
    scheduleUpdate app.53b92002.js:1248
    _$EC app.53b92002.js:1248
    requestUpdate app.53b92002.js:1248
    o app.53b92002.js:1248
    b app.53b92002.js:1248
    r hui-masonry-view.ts:44
    E typography.js:181
    t typography.js:181
    value eaaf4adc.js:385
    value eaaf4adc.js:385
    setTimeout handler*96151/i/< 206b40c8.js:1
    i 206b40c8.js:1
    value eaaf4adc.js:385
dwains-homepage-card.js:3694:10


`Uncaught (in promise) TypeError: this._hass.states[m] is undefined
    render dwains-homepage-card.js:3694
    update lit-element.js:220
    performUpdate updating-element.js:555
    _enqueueUpdate updating-element.js:508
    requestUpdateInternal updating-element.js:474
    requestUpdate updating-element.js:491
    set hass dwains-homepage-card.js:1997
    value hui-masonry-view.ts:44
    value hui-masonry-view.ts:44
    performUpdate app.53b92002.js:1248
    scheduleUpdate app.53b92002.js:1248
    _$EC app.53b92002.js:1248
    requestUpdate app.53b92002.js:1248
    set app.53b92002.js:1248
    value eaaf4adc.js:385
    _$AE app.53b92002.js:1248
    performUpdate app.53b92002.js:1248
    scheduleUpdate app.53b92002.js:1248
    _$EC app.53b92002.js:1248
    requestUpdate app.53b92002.js:1248
    set app.53b92002.js:1248
    k app.53b92002.js:1248
    _$AI app.53b92002.js:1248
    m app.53b92002.js:1248
    T app.53b92002.js:1248
    _$AI app.53b92002.js:1248
    S app.53b92002.js:1248
    update app.53b92002.js:1248
    performUpdate app.53b92002.js:1248
    scheduleUpdate app.53b92002.js:1248
    _$EC app.53b92002.js:1248
    requestUpdate app.53b92002.js:1248
    set app.53b92002.js:1248
    value app-drawer-layout.js:189
    value hass-loading-screen.ts:11
    performUpdate app.53b92002.js:1248
    scheduleUpdate app.53b92002.js:1248
    _$EC app.53b92002.js:1248
    requestUpdate app.53b92002.js:1248
65 dwains-homepage-card.js:3694:10
    _enqueueUpdate updating-element.js:517
    AsyncFunctionThrow self-hosted:642
    (Asynchrone : async)
    requestUpdateInternal updating-element.js:474
    requestUpdate updating-element.js:491
    set hass dwains-homepage-card.js:1997
    value hui-masonry-view.ts:44
    forEach self-hosted:167
    value hui-masonry-view.ts:44
    performUpdate app.53b92002.js:1248
    scheduleUpdate app.53b92002.js:1248
    _$EC app.53b92002.js:1248
    AsyncFunctionNext self-hosted:638
    (Asynchrone : async)
    requestUpdate app.53b92002.js:1248
    set app.53b92002.js:1248
    value eaaf4adc.js:385
    _$AE app.53b92002.js:1248
    performUpdate app.53b92002.js:1248
    scheduleUpdate app.53b92002.js:1248
    _$EC app.53b92002.js:1248
    AsyncFunctionNext self-hosted:638
    (Asynchrone : async)
    requestUpdate app.53b92002.js:1248
    set app.53b92002.js:1248
    k app.53b92002.js:1248
    _$AI app.53b92002.js:1248
    m app.53b92002.js:1248
    T app.53b92002.js:1248
    _$AI app.53b92002.js:1248
    S app.53b92002.js:1248
    update app.53b92002.js:1248
    performUpdate app.53b92002.js:1248
    scheduleUpdate app.53b92002.js:1248
    _$EC app.53b92002.js:1248
    AsyncFunctionNext self-hosted:638
    (Asynchrone : async)
    requestUpdate app.53b92002.js:1248
    set app.53b92002.js:1248
    value app-drawer-layout.js:189
    value hass-loading-screen.ts:11
    performUpdate app.53b92002.js:1248
    scheduleUpdate app.53b92002.js:1248
    _$EC app.53b92002.js:1248
    AsyncFunctionNext self-hosted:638
    (Asynchrone : async)
    requestUpdate app.53b92002.js:1248
`

**Comment by lurandly** [comment]
I get blank main panel when I add some devices to nav bar. It only happens with some devices like light, switch and person. Only way to resolve this is to remove devices.yaml. Disabling devices from nav bar doesn't help. HA logs do not show anything, only error I get is in browsers console. This started after updating to 3.1

```
Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'sort_order')
    at dwains-homepage-card.js:3445:100
    at Array.sort (<anonymous>)
    at _renderAreaViewCards (dwains-homepage-card.js:3443:46)
    at _renderAreaView (dwains-homepage-card.js:3774:20)
    at dwains-homepage-card.js:4170:45
    at Array.map (<anonymous>)
    at _.render (dwains-homepage-card.js:4170:29)
    at _.update (lit-element.js:220:37)
    at _.performUpdate (updating-element.js:555:22)
    at _enqueueUpdate (updating-element.js:508:29)
```

**Comment by tsspmq** [comment]
I had to delete devices.yaml as well.   I noticed in 3.0 if I hid an entity the sort order would be reset.   I kind of gave up after that, and wonder if the sort_order error could be related to that.    

I'm on the latest public release, was working great in 3.0.   My Fully Kiosk and mobile devices never had this issue.   Deleting the devices.yaml fixed it.

**Comment by emile-bodin** [comment]
Same issue here,

Home Assistant Core 2022.5.3
Home Assistant Supervisor 2022.05.1

After update to 3,1 the main page stays blank.
all other "more pages" worked.

reverted back to 3.0 via HACS, no change
backed up up DD config, uninstalled completely

- removed DD via hacs
- deleted DD intergration
- deleted dwains-dashboard folder

Installed DD 3.1, which worked, but after restoring the backed up config the main page goes empty again.
After deleting devices.yaml everyting seems ok now.

Is devices.yaml used differently in DD3.1?

**Comment by dwainscheeren** [comment]
Seems like a bug. Please remove devices.yaml then its fixed.

**Comment by HairyHook** [comment]
Dwain, not sure if this will help you troubleshoot the bug, but I'm experiencing the same problem where only one device will show the screen with the areas. I updated to 3.1 and my desktop browser displayed the page, while my cell phone did not. Now my cell phone does display the screen after reinstalling HA Companion App and the desktop browser does not.

**Comment by dwainscheeren** [comment]
Are you on Discord? Then we can discuss it there. Please ping me there

**Comment by HairyHook** [comment]
My desktop is back after updating to 3.1. Thank you!

**Comment by dwainscheeren** [comment]
Awesome
