### ISSUE TITLE
Hiding a person results in a long list of hidden person entities

### ISSUE THREAD

**Issue by smarthomejunkie** [dwainscheeren/dwains-lovelace-dashboard#531]
* Go to Devices
* Go to Person
* Click in right top on Enable Edit mode
* Click on three dots at specific person
* Click Hide entity in DD
* The person looks like it gets hidden, but there are multiple hidden entities visible for this person in the list
* The person is also not hidden from the person badges list in the Home page
![Screenshot_1](https://user-images.githubusercontent.com/67226335/167247934-0f8b0c70-515a-483f-b787-9d3a0a538ae7.png)

**Comment by dwainscheeren** [comment]
Thanks fixed :)

**Comment by Atlas-Night-Out** [comment]
I still seem to not be able to hide entity in DD I have lots of them too and looks horrid.



![Image](https://github.com/user-attachments/assets/dd12474e-1069-49b8-9812-94e1ac8b9ee0)


Its in Home I seem to have the issues in!

![Image](https://github.com/user-attachments/assets/7dad9a4b-f7bb-434d-8a47-dce3bf867816)

.
Any clues why
