### ISSUE TITLE
Edit Entity Card (Mushroom) 

### ISSUE THREAD

**Issue by Glen-Hart** [dwainscheeren/dwains-lovelace-dashboard#536]
After changing an entity card to Mushroom, then going back in to maintain it, I am getting the following:

Visual editor is not supported for this configuration:
At path: input_name -- Expected a value of type `never`, but received: `""`
You can still edit your config in YAML.

input_name: ''
input_entity: light.dining_room_wall_lights
collapsible_controls: true
entity: light.dining_room_chandelier
show_brightness_control: true
type: custom:mushroom-light-card

The only way I found around this is to reconfigure the entity card from scratch.

**Comment by dwainscheeren** [comment]
This will be patched in 3.1 :) thanks.
