### ISSUE TITLE
Hidden entities still show on people bar when toggled

### ISSUE THREAD

**Issue by youngman3009** [dwainscheeren/dwains-lovelace-dashboard#537]
We have multiple smart switches that control lights, so we want them to show as lights in DD.

The switch is a hidden entity and we show this as a light.
![image](https://user-images.githubusercontent.com/40072351/167610453-2f4dc3b6-49fb-467a-9aa2-68c0a274456e.png)

We then also hide the hidden entity in DD as it still shows on the dashboard by default.
![image](https://user-images.githubusercontent.com/40072351/167609700-fdbf3439-054d-477d-9829-17c911b49cae.png)

However, when you then toggle the lights for the room, this hidden entity will still show.
![image](https://user-images.githubusercontent.com/40072351/167641567-8e2db161-2f00-4190-97cd-b7f445d42577.png)

Any help would be greatly appreciated.

**Comment by dwainscheeren** [comment]
Then you need to disable them or in 3.1 you can exclude them :)
