### ISSUE TITLE
Temp sensors not on area card

### ISSUE THREAD

**Issue by TorbenSkovsted** [dwainscheeren/dwains-lovelace-dashboard#540]
Good work on the 3.1. update. Donation sent:-)

I am strugling with a relatively simple challenge. I have several rooms with temp sensor. Sensors are visible in the room (not hidden, disabled, excluded etc.). However, the temperature is not visible on the area card. 

I have three rooms where it all works fine - i.e. temperature in on the area card. I cant identify any differences. 

Any guidance or suggestions will be appreciated. 

I have version 3.1.1. installed.
<img width="987" alt="Skærmbillede 2022-05-14 kl  10 38 34" src="https://user-images.githubusercontent.com/61393371/168418219-729756f6-18b2-4cb3-9877-07b372984214.png">

**Comment by emile-bodin** [comment]
I had a similar issue with a mqtt sensor
I solved it by adding

`device_class: temperature`

To my sensor config

**Comment by dwainscheeren** [comment]
Yes the entity must have an valid device_class set. Otherwise DD won't recognize it.
