### ISSUE TITLE
Reload/Refreshing UI

### ISSUE THREAD

**Issue by macattack69traf** [dwainscheeren/dwains-lovelace-dashboard#547]
I am trying to edit a page via a code editor (ATOM) and then saving changes. How do I refresh Dwain's Dashboard? I have tried calling the Dwain's reload dashboard service, and well as reloading the page (and clearing cache), but it doesn't work.

The only way for my chances to be shown is by restarting Home Assistant. Any help would be appreciated!

**Comment by emile-bodin** [comment]
What page are you trying to edit? Blueprint pages?

If that's so, after making changes to a blueprint you need to go to the page edit mode and save again.

**Comment by macattack69traf** [comment]
> 

I am trying to add/edit a "More Page", which includes a Blueprint. I tried the method you outlined, however, it does not work, and the original configuration (prior to editing the file) is saved, and overwritten on the drive/yaml file.

**Comment by dwainscheeren** [comment]
Is this fixed?
