### ISSUE TITLE
Persons

### ISSUE THREAD

**Issue by erwindm** [dwainscheeren/dwains-lovelace-dashboard#549]
how can I change the persons on the dashboard?

**Comment by dwainscheeren** [comment]
It are the same persons as in your normal ha setup.

**Comment by erwindm** [comment]
how can i remove them from the view, need not all of them

**Comment by erwindm** [comment]
the rest of your work is very nice , i like it!

**Comment by dwainscheeren** [comment]
Note that a person is not the same as an user. So in the case you have a person like tablet for login on a wall mounted tablet just remove the person in ha itself. Otherwise disable the person in dd or exclude it.

**Comment by erwindm** [comment]
solved, thanks
