### ISSUE TITLE
Adding Blueprint - YAML editor does not appear

### ISSUE THREAD

**Issue by icornish72** [dwainscheeren/dwains-lovelace-dashboard#550]
Recent new user of Dwains, I just installed yesterday, and am impressed. But, I want to use Mushroom cards, so went to Add Card (in Edit Mode), and selected Dwains Dashboard Blueprint.
I do not get a box in which to enter the YAML content (like below). HA has been restarted and browser cache cleared. Using Chrome and Edge with same effect.

![image](https://user-images.githubusercontent.com/78433319/169084793-63071bae-d6a1-4a1f-b047-4d7fca889033.png)

**Comment by dwainscheeren** [comment]
If you wait sometime, like a few seconds, does it show up then? It needs to load in sometimes and can take some seconds.

**Comment by whoamicrypto** [comment]
Hi. I do have the same problem. Even when waiting the yaml editor does not appear. Running HA 2211.01 and DD3.3.
Any Thoughts?
Btw: is it also possible to add the blueprints manually via saving files in the appropriate directory?
Many thanks.

**Comment by TCS80** [comment]
> Hi. I do have the same problem. Even when waiting the yaml editor does not appear. Running HA 2211.01 and DD3.3. Any Thoughts? Btw: is it also possible to add the blueprints manually via saving files in the appropriate directory? Many thanks.

Same issue for me in both Edge and Firefox. Running Homeassistant Supervised on Proxmox VSE as a container

**Comment by whoamicrypto** [comment]
Hallo TCS80, with me the following seemed to maxically make the problem disappear: Instead of trying to add a blueprint, I went to adding a DD Card. Here the yaml field appeared. After adding a DD card, I went back to adding a DD blueprint ... and the yaml field was there and continues to be there. Maybe it works also for you ...

**Comment by mrshaharb** [comment]
same problem here.
waited and waited but it doesn't show up.
tried @whoamicrypto  sussgestion, but no luck.

running HA 2022.11.2 (but also didn't work on previous versions).
tried chrome & edge.

any thoughts or suggestions on what else to check?
![image](https://user-images.githubusercontent.com/30053246/200930465-3699c908-892f-4c48-b1ca-dc80d07f8ec1.png)

**Comment by nopoi** [comment]
I'm having the same problem.  Has anyone solved this?

**Comment by agrdbf** [comment]
After adding my first blueprint page, I'm not able to add more blueprint pages or cards. The YAML editor doesn't show up anymore. Im currently running HA 2022.11.2 as well. :/

**Comment by adamgerges** [comment]
Same issue here

**Comment by berfarah** [comment]
I'm also seeing this issue. Tried waiting a few seconds. Also tried doing CSS overrides to make the thing show up, but I think some JS call that should happen might not be happening.

**Comment by Roatan2005** [comment]
Likewise.  Added a first blueprint and can add no more, as the YAML field has disappeared...

**Comment by ks09aao** [comment]
same issue here, first time user option never comes up

**Comment by renaatdb** [comment]
Same issue here.

**Comment by dwainscheeren** [comment]
I'm working on a fix for this. :)

**Comment by whoamicrypto** [comment]
Thanks Dwain, for this great dashboard and appreciate your dedication. We wait patiently …

**Comment by aashon** [comment]
> I'm working on a fix for this. :)

Hi Dwain, 
First thank you for the amazing job, 
do you have an ETA for the fix?

**Comment by joshnl1977** [comment]
Wondering if this has been fixed yet. I'm also having the same issue!

Thanks for the awesome dashboard, Dwain, and for all the hard work you put into this!

**Comment by pavolholes** [comment]
I also have the same issue with Firefox and Edge. The "ha-yaml-editor" is empty... It showed at some point but now it's gone again... I've tried two devices, same behaviour....

![image](https://user-images.githubusercontent.com/35877348/211329395-11a6f3e7-17fe-4dac-8bc5-7be31c74f9eb.png)

**Comment by nathothan** [comment]
I'm having the same issue too. Any ideas on how to work around this?

Also, thank you Dwain. I'm new to your dashboard and love it so far!

**Comment by fandert-git** [comment]
> I'm having the same issue too. Any ideas on how to work around this?
> 
> Also, thank you Dwain. I'm new to your dashboard and love it so far!

upload the Blueprint YAML to /config/dwains-dashboard/blueprints, find it afterwards within Create new more page > Installed blueprints

**Comment by nathothan** [comment]
> upload the Blueprint YAML to /config/dwains-dashboard/blueprints, find it afterwards within Create new more page > Installed blueprints

Thank you so much! That worked perfectly. A pretty simple process if you're using the File Editor add-on. A few more clicks than the original method but not many.

**Comment by Planetcom** [comment]
Same problem here.
Unfortunately, creating a YAML file under /config/dwains-dashboard/blueprints/ didn't help either.
![Screenshot_2](https://user-images.githubusercontent.com/91396556/212539724-e255c6e2-d23e-4fe8-a307-0c262271ddd9.png)
Is there another solution now?

**Comment by openam** [comment]
Can we get this re-opened? I just loaded up dwains dashboard 3.3.0, and this is a problem right out of the gate.

**Comment by vinnie1234** [comment]
Same problem with 3.3.0

**Comment by haplm** [comment]
I have the same problem (3.3.0), can't paste the blueprint code into the dialog when creating "More" page.

**Comment by Tobster77** [comment]
Same issue for me. Latest version. Please consider to re-open the issue.

**Comment by Thunderf1** [comment]
Same issue here :(, last version.

**Comment by ihavn1** [comment]
Same issue. Hope it will be solved.
Btw the dashboard is so nice :)

**Comment by Tobster77** [comment]
I placed a request to re-open this:
https://github.com/dwainscheeren/dwains-lovelace-dashboard/issues/680

**Comment by giveyouup** [comment]
installed one blueprint, now yaml field is gone. latest version :

**Comment by 6502c** [comment]
I just recently learned about Dwains Dashboard in a video from 'Smart Home Junkie' on Youtube. 
I fell in love right away with it and installed it. 
Now I'm having the same problem that others have been reporting here since May 2022. No matter which browser I use (tried Safari, Firefox, DuckDuckGo), there's no possibility to paste the YAML code into the webpage for installing a blueprint.
I helped myself by adding the YAML file directly to the blueprints folder (/config/dwains-dashboard/blueprints/).

**Comment by M4Marc** [comment]
Same Here and a little bit lost.

**Comment by ctranter** [comment]
i had this problem yesterday, but now i can enter yaml on a new card, but not on other screens. however whatever yaml i post from the github it says "no yaml code entered".

**Comment by limakpb** [comment]
I have same issue. But I can paste code on my Android phone correctly.

**Comment by dennisantad** [comment]
I had the same problem. So i tried to add the blueprint manually.
In file editor i created a file with .yaml in the name in the dwains-dashboard/blueprints folder. It didnt work so i removed the .yaml file and went back to see if the editor was there and it was showing up. Maybe it will work for you too? Let me know.

**Comment by dwainscheeren** [comment]
Try the latest beta version.
