### ISSUE TITLE
Missing Alarm or Weather entity results in Blank DD Home Page

### ISSUE THREAD

**Issue by Daneish** [dwainscheeren/dwains-lovelace-dashboard#553]
For the past few days I have had a blank home page with Dwains Dashboard. The Devices and other DD pages load fine.

Refreshing cache, reloading DD, rebooting Home Assistant core, installing the latest version of DD, all made no difference. The issue occurred on the iOS and iPadOS Home Assistant apps. There was no relevant `Warnings`/`Errors` in the Home Assistant Core logs.

I went looking in the DD configuration directory and in the `config/dwains-dashboard/configs/settings.yaml` file, I found that I had a `weather_entity` that had recently been renamed. After changing the entity to use the correct entity_id the Home page loaded fine. 

To test further, I changed the weather_entity back to a invalid id which caused the issue to reoccur. After correcting the weather_entity again, I also tried changing the `alarm_entity` to an invalid id, this also caused the home page to load with a blank screen.

From memory, having an invalid weather_entity did not cause the whole home page to be blank in version 3.0.0. Just the weather entity would not load, but the rest of the home page loaded fine.

This issue could have caused #548 which was resolved by removing the whole Dwains Dashboard config directory. #528 could possibly have been related as well, but that seemed to be an issue with the devices.yaml file.

I’m reporting this as it appears to be a bug causing the whole home page not to load rather than just the effected entity. Assuming it is not specific to my system, it should be easy to be reproduce.

I’m running Dwains Dashboard v3.1.1 on HA Core 2022.5.4.

Thanks for making a great integration! I’ve just started using DD and I’m looking forward to getting stuck into making some beautiful dashboards!

Let me know if you need any further information or testing.

**Comment by MonacledMonkey** [comment]
Thanks for this. I had a blank home screen after deleting the existing weather intgration but not changing the preference.

**Comment by Daneish** [comment]
No worries, glad it was helpful.

**Comment by dwainscheeren** [comment]
Fixed in 3.2

**Comment by Daneish** [comment]
Sorry for belated response, thanks very much!
