### ISSUE TITLE
HA compagnion app Android not loading

### ISSUE THREAD

**Issue by SamJongenelen** [dwainscheeren/dwains-lovelace-dashboard#554]
Quick first off: love this!!! Now my issue: 

DD 3.1.1 (installed via HACS) is working fine on windows desktop, android Chrome, android Firefox.

However, it is not loading in the android HA app itself. I've tested my device (cleared cache&reboot), my girlfriends device (almost never uses HA app) and installed it fresh on a tablet.

All display ` Custom element doesnt exist`  error
> path: home
> type: custom:dwains-dashboard-layout
> cards:
>  - type: custom:homepage-card

screenshot:
![Screenshot_20220520-094433_Home Assistant](https://user-images.githubusercontent.com/3382443/169479542-73bb54be-b76f-4a83-b89b-3a02132c5c36.jpg)

When I go to DD on my Edge browser, in only get 1 Console error

Home Assistant Core 2022.5.5
Home Assistant Supervisor 2022.05.2
Home Assistant OS 8.0
Android 11+

What can I do to get more info about this problem?

**Comment by casper255** [comment]
It's the same for me

**Comment by dwainscheeren** [comment]
Clear the cache.

**Comment by SamJongenelen** [comment]
I cleared the cache (didnt work).
I had to delete all data, and re login to app etc to get it to work  thanks!

**Comment by psychocircus98** [comment]
> I cleared the cache (didnt work). I had to delete all data, and re login to app etc to get it to work thanks!

Thank you - sorted me out too!  I had been refreshing everywhere and I couldn't get the app to work.  Uninstall and reinstall and we're all good!
