### ISSUE TITLE
bug: zoom 90% makes the cards move

### ISSUE THREAD

**Issue by SamJongenelen** [dwainscheeren/dwains-lovelace-dashboard#555]
So I noticed that, when the browser is zoomed to 90%, the cards start moving, or 'wobling'.

this is my DD:
![image](https://user-images.githubusercontent.com/3382443/169483099-47a7501e-1592-4d48-b942-f97be3af015f.png)

I've uploaded a small video to youtube to show the issue, because I dont know the term :')
https://youtu.be/jBgD_M7Kw-I 

Edge browser W11

**Comment by dwainscheeren** [comment]
Very strange, can't reproduce it over here.

**Comment by SamJongenelen** [comment]
Im using a SurfaceLaptop4 with high DPI monitor and different aspect ratio, perhaps this is why?

**Comment by SamJongenelen** [comment]
Hey @dwainscheeren i noticed this is closed. Out of (webdev) interest, what was the issue?
