### ISSUE TITLE
Dashboard not loading error

### ISSUE THREAD

**Issue by tshan1229** [dwainscheeren/dwains-lovelace-dashboard#568]
Fresh install of DD
This error originated from a custom integration.

Logger: custom_components.dwains_dashboard.sensor
Source: custom_components/dwains_dashboard/sensor.py:100
Integration: Dwains Dashboard (documentation, issues)
First occurred: 6:51:49 AM (1 occurrences)
Last logged: 6:51:49 AM

Dwains Dashboard version check failed ClientConnectorError(ConnectionKey(host='dwains-dashboard.dwainscheeren.nl', port=443, is_ssl=True, ssl=None, proxy=None, proxy_auth=None, proxy_headers_hash=-962873103654982153), gaierror(-3, 'Try again'))

I've cleared cache of Android HA app, browser cache but that doesn't help.

**Comment by angelsanchezz** [comment]
Same here after changing the router

**Comment by tshan1229** [comment]
I'm not able to fix it even after removing and installing, so I use the phone browser.

**Comment by angelsanchezz** [comment]
I deleted the hidden .storage folder and restored later, this solved my problem
