### ISSUE TITLE
custom-ui icon colors not showing

### ISSUE THREAD

**Issue by tethlah** [dwainscheeren/dwains-lovelace-dashboard#572]
I added a template customization for icon and color on a sensor, the icon has changed in the dashboard, but for some reason the color does.  When I bring up the information the color shows up in the default more info cards, but anything dwains related doesn't have the colors.

**Comment by tethlah** [comment]
And just to be clear, these are state based color changes.

**Comment by dwainscheeren** [comment]
No idea, can you provide a video example.
