### ISSUE TITLE
Use this blueprint button does not appear

### ISSUE THREAD

**Issue by aussie-oddball** [dwainscheeren/dwains-lovelace-dashboard#576]
HI 
I am new to home assistant and recently installed your Dashboard

When I add a blueprint like the Replace Slider Button Card I copy the raw YAML from Github and hit the install blueprint the USE THIS BLUEPRINT button does not appear.  

When I install the ClockWheather Calendar that requires additional components the button does appear  (see pictures below)

I, therefore, can't install any blueprint cards.   I have tried on firefox and chrome and I get the same problem.  I am running HA on a raspberry pi.  All software components are up to date.

![Screenshot 2022-06-18 at 10 42 36](https://user-images.githubusercontent.com/17731517/174432155-1444e6ee-7e58-443f-8a86-9aec6ec7eaa6.png)

![Screenshot 2022-06-18 at 10 35 16](https://user-images.githubusercontent.com/17731517/174432058-97d5d18e-3e11-4376-a59e-22e96c1030ae.png)

![Screenshot 2022-06-18 at 10 39 24](https://user-images.githubusercontent.com/17731517/174432040-2ad58cb7-1f81-4251-8542-af2eb01f3611.png)

Thanks for a great product.  Love to get some advice if I am doing something stupid!

**Comment by dwainscheeren** [comment]
You only can replace cards in the replace modal, same for normal cards and more pages. You are using the wrong blueprints at the wrong location.
