### ISSUE TITLE
Polish translation is scruffy. How to make some corrections?

### ISSUE THREAD

**Issue by Krzysztonek** [dwainscheeren/dwains-lovelace-dashboard#578]
Hi @dwainscheeren ,

[I translated the previous version of your DD into Polish](https://github.com/Krzysztonek/Dwains-Dashboard-PL).
The Polish translation of the current version (not done by me) is pretty scruffy hence I'd love to do some corrections.
Will you please give me any hints on how the file structure is organized so I could do it?

**Comment by dwainscheeren** [comment]
Fork this, adjust it and post the forked url here :) https://gist.github.com/dwainscheeren/65b4e4704c081830bce4d4bf952dce24

**Comment by Krzysztonek** [comment]
Done :)
See here: https://gist.github.com/Krzysztonek/06889d2659fede6eaf564c1957e8e9cc/revisions

**Comment by kamilk91** [comment]
@Krzysztonek 

`carbon_monoxide: 'Czad CO',` its kind of wrong. Consider to change it to `Tlenek węgla` or `Czad` but word `Czad` is not so correct name. Its name of a country, this name is not so popular now. 

Also what about change "Encja" to "Instancja"? Im not sure but maybe its more readable for people who are not IT.

**Comment by Krzysztonek** [comment]
Hi @kamilk91 
1. Ok then, let's replace `carbon_monoxide: 'Czad CO'` with `carbon_monoxide: 'Tlenek węgla'`, even if it takes a bit more space on the screen.
2. "Encja" is definitely NOT the same as "Instancja". `Encja` in Polish means an `Entity` in English. `Instancja` in Polish means an `Instance` in English. These are two completely different words with two different meanings. Even IT layman knows what's behind it. ;)

**Comment by kamilk91** [comment]
Hi @Krzysztonek, yes i know that. Thats ok but as you know `Encja` is not so popular word. But yes, you right. Let's teach Poles what `Encja` is ;) thanks for your reaction
