### ISSUE TITLE
not showing up in HACS

### ISSUE THREAD

**Issue by snickers2k** [dwainscheeren/dwains-lovelace-dashboard#582]
hey. 
just wanted to install this project. 
but it's not showing up in HACS. if i want to add the repository, it says "already existing".

what do i wrong? 

thanks

**Comment by ghost** [comment]
Have you looked in the HACS integrations?  It's not a lovelace.

**Comment by snickers2k** [comment]
oh boy.. i'm sorry... had it installed long before :/ it was under installed integrations and because of that didn't showed up in search. sorry
