### ISSUE TITLE
Performance horrible. please help me

### ISSUE THREAD

**Issue by aperezva** [dwainscheeren/dwains-lovelace-dashboard#583]
Hi, 

Project is amazing but response from the Systems is not possible to keep this dashboard installed. too slow and affects HA services affecting to all the system.

Any idea how to improve?. Please, don t misunderstand me, it´s a wonderful work, but it needs to improve performance,

Im in a RI 4 GB with SSD.

any idea?

**Comment by LordNex** [comment]
You might be over taxing that SD Card. Make sure your running a database and have a regular purge interval for entities or your just going to keep filling your SD card up until it's out of space. 

Honestly, if your really wanting to run Home Assistant without issues you really need to go up to an i5 or something. The extra cache and hardware support makes a night and day difference. 

Currently I'm running mine on a 40 core 256gig Dell PowerEdge R620 running VMWare ESXi 7 along with a bunch of other goodies.

**Comment by aperezva** [comment]
> You might be over taxing that SD Card. Make sure your running a database and have a regular purge interval for entities or your just going to keep filling your SD card up until it's out of space.
> 
> Honestly, if your really wanting to run Home Assistant without issues you really need to go up to an i5 or something. The extra cache and hardware support makes a night and day difference.
> 
> Currently I'm running mine on a 40 core 256gig Dell PowerEdge R620 running VMWare ESXi 7 along with a bunch of other goodies.

I found the problem, I have 5 cameras, if I keep the card for thes cameras , HA becomes die, and performance goes down.

Solution, change camera cards for the official pictures card in HA, with is not constantly streaming.

**Comment by aperezva** [comment]
Issue has been closed. It´s related a number of cameras, I have 6 cameras streaming together and that´s the problem, I have changed the Camera Cards to have only phot refresh and everything works fine

**Comment by aperezva** [comment]
Right now

I´m in a VDI version with 4 Gb of memory SSD and 2 CPU´s, in a MAC host.

The same problem,

Thanks for your answer, but it seems taht it’s performance problem
