### ISSUE TITLE
Please add option for clock (12 hour clock instead of 24 hour, or tie it to home assistant settings)

### ISSUE THREAD

**Issue by wtstreetglow** [dwainscheeren/dwains-lovelace-dashboard#584]
1.) Clock display tied to Home Assistant display setting (or just a check box to change it over to a 12 hour am/ pm clock)-- I currently have my HA time set to auto which matches my system time but in the Dwains Dashboard, it is still showing the 24 hour clock
Screenshot 1 below
![79852547cd2582f3e31c34ab30efd84f191d8b01_2_690x373](https://user-images.githubusercontent.com/30456018/177024814-a7e1ff3c-ae28-4d08-990b-d7379a77e3d4.png)

**Comment by dwainscheeren** [comment]
I've made an option for it in next release 3.2

**Comment by wtstreetglow** [comment]
Thank you @dwainscheeren
