### ISSUE TITLE
I can't refresh Areas, newly areas are not seenable in Dashboard. 

### ISSUE THREAD

**Issue by kamilk91** [dwainscheeren/dwains-lovelace-dashboard#587]
I can't find any info about that in internet. Is it possible to refresh Areas? Also i changed photos and they are not visible.

**Comment by dwainscheeren** [comment]
It will be automated loaded, just refresh the page.

**Comment by kamilk91** [comment]
@dwainscheeren i also removed all cache/cookies etc and still not works

**Comment by kamilk91** [comment]
Problem was that area wasn't saved. No related to DD.
