### ISSUE TITLE
temperature not matching

### ISSUE THREAD

**Issue by lekdin** [dwainscheeren/dwains-lovelace-dashboard#591]
Temp does match, big differnce!!

![image](https://user-images.githubusercontent.com/81484851/178097616-c8fb5a5e-ce9c-4356-b320-00d5515055e0.png)

**Comment by Gessink** [comment]
You probably have other temperature sensors in the same room (cpu temp or something like that). If you remove that one, this will be fixed. DD always uses mean of all sensors in a room

**Comment by dwainscheeren** [comment]
What @Gessink says. Check all temp sensors in the room. Its the average of all.
