### ISSUE TITLE
FR - Correct italian translation

### ISSUE THREAD

**Issue by ElyFNV** [dwainscheeren/dwains-lovelace-dashboard#592]
Hi Dwain!
I love the work you have done with this dashboard. I think it's the best around... simply brilliant.
However, I noticed how the translation of some things (in italian) is not entirely correct. If you want I can help you in giving you the right terminology. In case you are interested let me know how I can help you!
For example: when a window is open it is written "1 aprire" (it would be like saying, in English, "1 to open") ; the correct term is "1 aperta" ("1 opened").
Another example can be that relating to the lights on. When some light is on, in the dashboard is written "3 su" (3 lights up); however, while in English "3 lights up" is correct, in Italian it is not... the correct translation is: "3 accese" ("3 turned on").
I hope I explained myself correctly! Thank you!!

**Comment by dwainscheeren** [comment]
Please fork it here, and adjust it then post the link so I can use it. https://gist.github.com/dwainscheeren/65b4e4704c081830bce4d4bf952dce24
Thanks

**Comment by ElyFNV** [comment]
Ehi Dwain... I made some corrections ("https://gist.github.com/ElyFNV/484f49dc78d7e27713bc2bc7082b9ff0").
Unfortunately, however, some things will always be "not precise", since the Italian language differs between singular and plural and is closely linked to the context in which a word is said. For example, in English we always say "1 open window" or "2 open windows": the verb is identical. In Italian it changes: it says "1 finestra aperta" and "2 finestre aperte".
Thank you anyway... Ah! I added also the "humidifier" entity since I own a humidifier... and to DD it was unknown.

**Comment by lbouriez** [comment]
@ElyFNV , It would be easier to create a pull request directly to the repo.

**Comment by Andred87** [comment]
Hi Dwain, I have noted that the Italian translation is unprecise in any word. but I also noted that Elyfly has already modified the file "translation.js".
I can suggest a little clarification, the domain cover in Italian translation can be "Tenda" or also "Tapparelle" (if the covers are roller shutter) or also "Persiane".
We can generalize the domain's name in" OSCURANTI" for me that name generalizes all can possible devices that are type covers. 
thanks.

**Comment by dwainscheeren** [comment]
Please make a PR here https://gist.github.com/dwainscheeren/65b4e4704c081830bce4d4bf952dce24
