### ISSUE TITLE
DD empty after adding weather entity

### ISSUE THREAD

**Issue by flyingdutchman7588** [dwainscheeren/dwains-lovelace-dashboard#597]
I recently installed DD on my HA and everything looked fine. Then I clicked on the gear icon and selected openweathermap under the weather entity and clicked ok. I restarted HA and when I went to DD, my entire page is blank. I can see the major titles on top (Home, Devices, More) but that is it. When I went to the configuration directory, I noticed that my config/dwains-dashboard/configs/settings.yaml is completely blank. There is no code in there. 

![DD main page](https://user-images.githubusercontent.com/37387465/179256550-25de02f9-bf4e-4d2f-a9ac-a7848418c772.jpg)

Here is the settings.yaml look:

![Settings](https://user-images.githubusercontent.com/37387465/179256755-897efa32-ce83-47c1-9ece-f04c27a859af.jpg)

What did I do wrong?

**Comment by BNoiZe** [comment]
What is your Home Assistant version? DD is not yet compatible to 2022.7. See issue #588

**Comment by dwainscheeren** [comment]
Try DD 3.2 it was a bug and is now fixed. https://github.com/dwainscheeren/dwains-lovelace-dashboard/releases/tag/v3.2.0
