### ISSUE TITLE
Blank screen now on Home screen of Dashboard

### ISSUE THREAD

**Issue by PhilDGeorge1968** [dwainscheeren/dwains-lovelace-dashboard#599]
After disabling an entity from SmartThings in HA Device settings which the Dashboard wouldn't allow me to hide, I'm not getting a blank Home and found this error in my log file

2022-07-16 12:46:53 ERROR (MainThread) [frontend.js.latest.202207071] http://homeassistant.local:8123/dwains-dashboard/home:0:0 Uncaught

**Comment by BNoiZe** [comment]
DD ist not compatible with HA 2022.7 and later. HA bumped Python to 3.10 which broke some things. This is a known issue, see #588. You can also find a work around there. But don't edit your dashboard as this will break it completely. (You can directly edit the yaml files though.)
