### ISSUE TITLE
Empty dashboard after editing

### ISSUE THREAD

**Issue by Love-to-Soccer** [dwainscheeren/dwains-lovelace-dashboard#600]
Hi,

I have just installed the dashboard.
At the beginning I also saw all entities in the dashboard.
However, for reasons I can't explain, I suddenly only see the "Home, Devices, Other" tabs. 
But completely without content.

I have already cleared the cache etc., but it didn't help.
I also deleted the add-on from the HACS and reinstalled it... also without success.

Edit:
Found out.
I still had to manually delete the dwains-dashboard folder.
But I was able to reconstruct the problem.
As soon as I edit anything (moving, disable,…) I see completely nothing again and have to uninstall everything.

what is wrong here?

**Comment by deku-m** [comment]
You should check out #588 as this is known problem when you run HomeAssistant 2022.07

Wait till Dwains releases the fix/update

**Comment by 48EAS** [comment]
I experienced the same issue

**Comment by sparksbenjamin** [comment]
Same issue here.  Seems that when you try to save the config it writes a blank file to the configs file.  When it reads the blank file it does what you would expect.  Deleting the entire dwains-dashboard directory inside the config clears the issue of the dashboard being blank but means that you can not make changes to the auto-generated dashboard.

**Comment by dwainscheeren** [comment]
Try DD 3.2 it was a bug and is now fixed. https://github.com/dwainscheeren/dwains-lovelace-dashboard/releases/tag/v3.2.0
