### ISSUE TITLE
Unable to change the background in v3.2.0

### ISSUE THREAD

**Issue by nolan879** [dwainscheeren/dwains-lovelace-dashboard#605]
Before the update my Dashboard would use the background from my chosen theme, now I am not able to remember how I changed it before. Anyone able to point me in the right direction?

**Comment by ghost** [comment]
![07E391FE-BEE3-4C93-9069-FA88BA46C06A](https://user-images.githubusercontent.com/83040228/181057276-33bbea35-8703-4e5b-8916-d7323a4b989c.jpeg)

**Comment by prjcarr** [comment]
On a similar note, is it possible to use a dark theme for DD and another theme for the rest of HA?

**Comment by ghost** [comment]
No, that's not possible

**Comment by nolan879** [comment]
> ![07E391FE-BEE3-4C93-9069-FA88BA46C06A](https://user-images.githubusercontent.com/83040228/181057276-33bbea35-8703-4e5b-8916-d7323a4b989c.jpeg)

I have the theme selected, this is what the background should be:
https://i.imgur.com/Ra6NsOj.png
Here is what I see:
https://i.imgur.com/SKhKlhY.png

Theme is selected:
https://i.imgur.com/8Bnoo9P.png

**Comment by nolan879** [comment]
Solved:

In custom_components/dwains_dashboard/lovelace/ui-lovelace.yaml , I had to change 

`lovelace-background: var(--background-image)` 
to 
`background: var(--background-image)`
