### ISSUE TITLE
HA 2022.8.3 & DD 3.2.0 still shows blank screen no matter what

### ISSUE THREAD

**Issue by subnuts** [dwainscheeren/dwains-lovelace-dashboard#611]
Hi,

removed all cookies, tried several different browsers, reinstalled DD .. still just a blank screen. Has been that way since 2022.7.2
To top it off, logs do not show any errors... no idea what to do now.

**Comment by jsandoval77** [comment]
Same thing happened to me. Any solution?

**Comment by subnuts** [comment]
Sort of. I removed the installation, for now. The state it is/was in, it's of no use.

**Comment by mtoftum** [comment]
I've had a couple of times now where I had to do a shift-reload on the HACS page to make DD work after upgrades. Performing the reload directly on DD didn't work.

**Comment by S3DD3S** [comment]
Home Assistant 2022.8.4 the same. Blank screen. And its not in HACS to install it again.

**Comment by dwainscheeren** [comment]
Is there any config file empty in the dd config folder?

**Comment by subnuts** [comment]
Nope, there wasn't. I figured that this could be a problem and checked for that.

**Comment by dwainscheeren** [comment]
If you rename dwains-dashboard to dwains-dashboard2 or something like that does dd work again?

**Comment by subnuts** [comment]
Yes, tried that one also. Didn't work either.

**Comment by dwainscheeren** [comment]
I'm running 8.4 and no issues here. Also on my Discord server nobody with issues. So something on your setup must go wrong. Do you got an error in the ha error log or your browser console log?

**Comment by subnuts** [comment]
No, that is the weird thing. There is nothing in the error logs at all.

Yea, I'm not disputing the fact, that there is something wrong on my side. I'm currently using an RPi 3b+ but I doubt that might be a problem. But as of right now I'm at a total loss as to what might be wrong.

**Comment by LASaether** [comment]
Same for me. Running on RPI4 and i'm on HA 2022.8.5, but had similar issues with 2022.8.4

**Comment by LASaether** [comment]
FYI. Rolled back HA to 2022.8.1 and Darwin 3.1.1, and now the home page of the Darwin dashboard come up with no issues. So there is some change either in the later versions of HA or Darwin that breaks the loading of the home page.

**Comment by LordNex** [comment]
It sounds like it's not actually downloading the new files and installing them in the directory. Try and manually do the install by unzipping the folder and coping it over to the custom components folder. Might want to make a backup of the existing folder first. But once you know the files are there, reboot and give it a try again. Also, make sure your not running out of space on your SD card and there isn't any issues with it.

**Comment by rafalbremer** [comment]
Same problem here. HA 2022.8.6 and DD 3.2.0. HA installed as VM on proxmox. Home page, Devices page empty.

edit:
I can see in logs:
2022-08-21 20:08:50.487 WARNING (MainThread) [custom_components.dwains_dashboard] Update_listener called

edit:
I've found that I'm able to get back DD by complete uninstall and removal all config files related. Unfortunately it works only to first change of DD configuration from UI. It seams that UI changes something in config what cause the problem.

**Comment by subnuts** [comment]
> FYI. Rolled back HA to 2022.8.1 and Darwin 3.1.1

For the fun of it, I tried DD 3.1.1 ... didn't work. Same behaviour, that is, just a blank screen.

>  Also, make sure your not running out of space on your SD card and there isn't any issues with it.

Not sure whether this was directed at me, but if so, I have about 200G space left. So that would hardly be an issue.

> Same problem here. HA 2022.8.6 and DD 3.2.0. HA
> edit: I can see in logs: 2022-08-21 20:08:50.487 WARNING (MainThread) [custom_components.dwains_dashboard] Update_listener called

Can confirm. I updated to 2022.8.6 and reinstalled DD 3.2.0, and I also now get to see the Update_listener called warning.

**Comment by LordNex** [comment]
Nope I'm having the same issue now too. Not sure if it's the newer 2022.9.x of HA or what. But at this point the dashboard is completely broken again even though all the entities are listed in the yaml file. 

This is starting to get too inconsistent to be usable. Hopefully something is done about it but I'm not holding my breath. Guess I'll start rebuilding a true dashboard like I did last time.

**Comment by dwainscheeren** [comment]
So besides only complaining can you also post then an error log from HA and an error log from your browser console so I can actually look into it?

**Comment by LordNex** [comment]
> So besides only complaining can you also post then an error log from HA and an error log from your browser console so I can actually look into it?

```

This error originated from a custom integration.

Logger: custom_components.dwains_dashboard
Source: custom_components/dwains_dashboard/__init__.py:1599 
Integration: Dwains Dashboard (documentation, issues) 
First occurred: 7:00:06 AM (1 occurrences) 
Last logged: 7:00:06 AM

Update_listener called
```

**Comment by LordNex** [comment]
> So besides only complaining can you also post then an error log from HA and an error log from your browser console so I can actually look into it?

Would have posted it but I figured you "knew" the error. If it was different I would have created a new ticket. But next time I'll just create a new one and fill out all the info for ya there

**Comment by LordNex** [comment]
Tried redownloading the source files, still no luck. Tried rolling back HA, still nothing. Tried replacing the dwains-dashboard folder from a previously known good backup, still same error. Entities.yaml is full and properly configured, tried using the default config, still same error. Seems to be something internal. I use the iOS app for all access so browser logs are not available and I don’t see anything else in the client logs that indicate anything. It’s pretty much dead in the water right now which makes things as simple as turning on a light practically impossible for anyone that doesn’t know HA internals. 

Please, I’m not bitching, see if you can get this fixed. For those of us that rely on this daily, it really makes life a lot harder. If you don’t have the time, that’s understandable, maybe you let someone else with experience take over who has more time for development. I think if you did this right. The HA people may want to include it as an official addon. I know they are looking at Music Assistant now as it’s leaps and bounds ahead of the basic media player.

**Comment by dwainscheeren** [comment]
As we are now on 2022.9 this can be closed I think.
