### ISSUE TITLE
DELETE

### ISSUE THREAD

**Issue by Strikky** [dwainscheeren/dwains-lovelace-dashboard#612]
Hoe kan ik DWAINS DASHBOARD VERWIJDEREN/DELETEN.

Het enige wat ik zie zijn lege dashboards en ik vind het nou niet bijzonder, net iets teveel.

**Comment by dwainscheeren** [comment]
If you see an empty dashboard you didn't install DD good. Please re-install it. It will automatic show all your areas and devices.

**Comment by Strikky** [comment]
Hoe kan ik DWAINS DASHBOARD VERWIJDEREN/DELETEN.!!!!!!!!!!!

**Comment by Strikky** [comment]
How can I delete/remove the Dwain dashboard

**Comment by Luukxt8** [comment]
RTFM

**Comment by Strikky** [comment]
Useless answer.
Waisting your and mine time.

Niks beters te doen?

**Comment by dwainscheeren** [comment]
Je moet naar de integrations in HA zelf gaan niet in HACS. Bij de integrations in HA zie je ook Dwains Dashboard staan en daar staan 3 puntjes. Als je daar op klikt zie je Verwijderen of Uninstall staan.
