### ISSUE TITLE
Custom element doesn't exist: dwains-dashboard-layout when trying to cast to TV

### ISSUE THREAD

**Issue by Arv1nt3** [dwainscheeren/dwains-lovelace-dashboard#614]
So everything went fine when installing the dashboard but when I tried to cast the dashboard on a TV that has Chromecast I encountered the same error as in the documentation. I restarted the TV, the Chromecast, and HA but still could not find a way to solve the issues.

Edit: I just realized that it doesn't work on my phone as well. I'm a beginner to HA so maybe I did something wrong.

**Comment by virtaz** [comment]
Hey, did you get this solved?
Same issue here, trying to cast this in to the android tv with chrome cast and I get error.
Android app gives the same error.

**Comment by dwainscheeren** [comment]
You can cast DD with CATT

**Comment by virtaz** [comment]
How about android app?
Is there a workaround to use normal google cast? It works great with normal love lace dash
