### ISSUE TITLE
templates button card

### ISSUE THREAD

**Issue by Ngouaillier** [dwainscheeren/dwains-lovelace-dashboard#620]
Hello Dwains, being new to Home Assistant I find myself faced with a problem that is surely simple but blocking for me, I am looking to put templates for but button_card but I don't know where to put them I saw in the ui-lovelace this line (button_card_templates: !include_dir_merge_named ../../../dwains-dashboard/button_card_templates) but in which conf file should the templates be copied thank you for your help 🙂

**Comment by dwainscheeren** [comment]
You can place the yaml files in the folder dwains-dashboard/button_card_templates :) Just reload/reboot DD or HA complete after placing the yaml files there.
