### ISSUE TITLE
How to hard-remove Dwains Dashboard?

### ISSUE THREAD

**Issue by ende0** [dwainscheeren/dwains-lovelace-dashboard#621]
I've tried it about 5 times by removing every file but everytime I reinstall DD it comes in the way it was before, like there's some backup files or something.. I even removed the cache files and tried diffrent browsers but nothing changed.

Is there a way to remove everything and start over with the dash?

**Comment by dwainscheeren** [comment]
You need to remove the folder dwains-dashboard in your main ha folder. Then DD has a clean install. Even without installing the repo itself.

**Comment by ende0** [comment]
I tried that before but the same dashboard returns when I reinstall it, it shows this too:



How can I solve that?

**Comment by dwainscheeren** [comment]
I don't see the photo. It depends if you see all areas and devices each time its the way DD works if you clear the config its 100% clean.

**Comment by ende0** [comment]
Kan het ook in het Nederlands?

Zo ja, op het moment dat ik een nieuwe pagina wil maken komt er een popup naar voren met info, entiteit instellingen en related. 

Ik heb het vermoeden dat er ergens in HA nog insbtellingen ewaard blijven

**Comment by dwainscheeren** [comment]
Remove the dwains-dashboard and dwains_dashboard folders.
