### ISSUE TITLE
Hidden Entities reappear under device class "Switch" if "ON"

### ISSUE THREAD

**Issue by williamhart-az** [dwainscheeren/dwains-lovelace-dashboard#627]
Request would be to honor hidden device status.

Under one of these UI element, in this case 'Switch':
![image](https://user-images.githubusercontent.com/112638858/191787243-7d080aa0-9561-4f14-beb6-21cc659a603a.png)

So that when listed there:
![image](https://user-images.githubusercontent.com/112638858/191786292-cbcce7d6-80c6-4c44-9ce0-b0c36fc47746.png)

You can use this UI element:
![image](https://user-images.githubusercontent.com/112638858/191786493-9aa84e37-ce62-4524-a981-13732ea296b8.png)

Unfortunately this 'switch' in HA is a setting in my OmniPro II controller and turning it off with "Turn All Off" is not my intention.

Otherwise this dashboard rocks, thank you for your contribution!

**Comment by ghost** [comment]
![IMG_4915](https://user-images.githubusercontent.com/83040228/191794917-3c52f670-cdb8-4de1-a344-97ed3c8d019a.jpeg)

**Comment by williamhart-az** [comment]
> ![IMG_4915](https://user-images.githubusercontent.com/83040228/191794917-3c52f670-cdb8-4de1-a344-97ed3c8d019a.jpeg)

Well that did it. Thank you!

Had to stare at this for about 3 minutes straight to understand it.

Wonder if it would be beneficial for a setting to "honor HA hidden/disabled" to make it simpler?
