### ISSUE TITLE
Light icon

### ISSUE THREAD

**Issue by tdonhauser** [dwainscheeren/dwains-lovelace-dashboard#629]
Hello,

I have some problems with the light detection in v3 after migration from v2.
Some of my rooms dont recognize the lights and show them on the icon on the start page:

![grafik](https://user-images.githubusercontent.com/21998742/191803157-5902c29a-0b48-400f-869a-c0ea710e9208.png)

In this example only the rooms "Küche" and "Büro" show lights even if all the other rooms have one as well. How do have to configure the dashboard to recognize the lights?

Thanks!

**Comment by dwainscheeren** [comment]
Just add the lights to the room (they must be a light entity) then DD will see them automatic.

**Comment by tdonhauser** [comment]
Thank you!
