### ISSUE TITLE
Help Needed

### ISSUE THREAD

**Issue by Model-Railroad-Techniques** [dwainscheeren/dwains-lovelace-dashboard#638]
Hello all, I am very new to Dwains. 
Hope someone can help. Attached is a picture of a my dashboard. When I click on the cards at the top left (highlighted) you get this info/settings/related card above it. This makes access this on a mobile device impossible. Is there a setting to get rid of this? Thank you in advance. Daz

![311907006_10159122915617615_5667258273333913302_n](https://user-images.githubusercontent.com/102439366/196289893-195d27f0-945d-499d-b837-d8ed59a9e900.jpg)

**Comment by ghost** [comment]
This problem has been fixed in beta version 3.3.0.  Update via HACS by checking the Beta option.

**Comment by Model-Railroad-Techniques** [comment]
Thank you, I have updated, I can not see an option for the Beta..Sorry I am very new to this.

**Comment by ghost** [comment]
In HACS

![3CF9EB61-6C8E-461C-924A-C50B935E8676](https://user-images.githubusercontent.com/83040228/196545081-b7d54be8-3c9c-4f7f-aa93-53aaa2f4797d.jpeg)

**Comment by Model-Railroad-Techniques** [comment]
fantastic. Thank you so much for your help. I really appreciate this.
