### ISSUE TITLE
Home Assistant - Android App red label error

### ISSUE THREAD

**Issue by BristolBEAT** [dwainscheeren/dwains-lovelace-dashboard#639]
Getting the attached error when loading the DD. I've tried reseting the HA cache in the android settings.

![Screenshot_20221020-124402](https://user-images.githubusercontent.com/109667579/196939668-c55f23d1-8360-4b1f-9c2e-1faf4c158ee4.jpg)

**Comment by thomclae33** [comment]
I have the same issue. Clearing app cache doesn't resolve the problem.

**Comment by dwainscheeren** [comment]
reinstall the app or clear app data
