### ISSUE TITLE
fr.help please!

### ISSUE THREAD

**Issue by Sectorvicioso** [dwainscheeren/dwains-lovelace-dashboard#641]
custom element doesn´t exist: dwains-dashboard-layout
i try to start after install and have this message. 
help please!
Thanks!!!
![image](https://user-images.githubusercontent.com/87580339/199206653-aa5f9449-c9b3-4c19-9627-1211440054f0.png)

**Comment by ghost** [comment]
Clear cashe. Do you use Android?  If yes you have to go to the app: app /configuration /reset frontend cashe

**Comment by dwainscheeren** [comment]
What @MichelJourdain says. Please clear cache
