### ISSUE TITLE
How to set default room?

### ISSUE THREAD

**Issue by hyperlau** [dwainscheeren/dwains-lovelace-dashboard#645]
I want to set a default page,and I create a new room ,how to set this room to default so when I access 'dwains-dashboard/home' it can be show first?

**Comment by ghost** [comment]
This is not possible, but the room at the top left is the one that will be displayed by default.

**Comment by hyperlau** [comment]
sadly it's not..In my case the second room in the second floor is displayed by default..

**Comment by ghost** [comment]
If you use sort by floor, disable it temporarily and move the room you want to default to the top left.

**Comment by hyperlau** [comment]
OK ,That's worked, thank you very much!
