### ISSUE TITLE
Error this is the log 

### ISSUE THREAD

**Issue by Jezza1232** [dwainscheeren/dwains-lovelace-dashboard#651]
This error originated from a custom integration.

Logger: custom_components.dwains_dashboard.sensor
Source: custom_components/dwains_dashboard/sensor.py:76
Integration: Dwains Dashboard (documentation, issues)
First occurred: 6:14:17 PM (1 occurrences)
Last logged: 6:14:17 PM

Dwains Dashboard version check failed ClientConnectorError(ConnectionKey(host='dwains-dashboard.dwainscheeren.nl', port=443, is_ssl=True, ssl=None, proxy=None, proxy_auth=None, proxy_headers_hash=-7561557090097053990), gaierror(-3, 'Try again'))

**Comment by dwainscheeren** [comment]
This is fixed.
