### ISSUE TITLE
"." entity card appears when using dashboard

### ISSUE THREAD

**Issue by Aguasclaras5** [dwainscheeren/dwains-lovelace-dashboard#655]
when editing an entity card appears at the top of page (on desk computer or Ipad) entity is "." . if you close it reappears in 1-10 seconds. If using iPhone it covers entire screen.
![Image 11-15-22 at 10 18 AM](https://user-images.githubusercontent.com/108194955/201956448-65a129eb-f0fa-412f-9f2c-b042ebe51a22.jpg)

**Comment by ghost** [comment]
This problem has been corrected with version.3.3.0.  Make sure you have the latest version of Dwains Dashboard.
