### ISSUE TITLE
Unknown! (Dwains Dashboard v3)

### ISSUE THREAD

**Issue by johnmhedge** [dwainscheeren/dwains-lovelace-dashboard#679]
I am a new user of Dwain's Dashboard v3
I appear as 'unknown'!
How do I become 'known' please?
TIA
John

**Comment by ghost** [comment]
Can you give more details please.

**Comment by johnmhedge** [comment]
I've attached a screenshot. I hope it helps.
![Screenshot 2023-02-13 165147](https://user-images.githubusercontent.com/30383304/218381112-0a770bc5-5ae3-43ae-94b0-62c2a6f4273e.jpg)

**Comment by ghost** [comment]
What tracking device do you use?

![EFD957C4-1D97-4ED7-8D7A-5AE97A302D44](https://user-images.githubusercontent.com/83040228/218480281-6362ce0f-19d2-4d9c-919b-54e1f665f187.jpeg)

**Comment by johnmhedge** [comment]
Thanks for the hint Michel.
I think it must have something to do with my mobile.
HA is allowed to know my mobile's location but still 'unknown'!
![Screenshot 2023-02-14 101025](https://user-images.githubusercontent.com/30383304/218597316-ce95179b-e014-4294-8cb7-343cf21beee3.jpg)

**Comment by johnmhedge** [comment]
I uninstalled HA app on phone, reinstalled making sure 'location' tracking was ticked and it worked at last!
John
