### ISSUE TITLE
Can't Hide User Card On Main Dashboard Page

### ISSUE THREAD

**Issue by colm-smyth** [dwainscheeren/dwains-lovelace-dashboard#683]
Apologies if I have just missed an option but on the main DD page where you see the Welcome Message. There is a list of users. I don't want to see this, is there a way to disable it ?

I have hidden all users in the Devices/Person but I dont think that impacts it anyway.

Any ideas ?

**Comment by dwainscheeren** [comment]
You can exclude them if you go to persons -> then edit -> exclude then they dissapear from homepage

**Comment by DocWind** [comment]
Hi all! I  (deacitvated) somebody I want to see on the main page and I can’t get him back. Can somebody help me?
