### ISSUE TITLE
Android HASS App: "Custom element doesn't exist: dwains-dashboard-layout."

### ISSUE THREAD

**Issue by hase-00** [dwainscheeren/dwains-lovelace-dashboard#691]
Using the Android HomeAssistant App, I get the error: "Custom element doesn't exist: dwains-dashboard-layout."

title:   Home
icon:  mdi:home
path:  home
type:  custom:dwains-dashboard-layout
cards:
  - type custom:homepage-card

Inside the WEB browser on the same Android phone it works but not when I use the HomeAssistant APP.

/GH

**Comment by FUsIon80** [comment]
Me too, empty App Cache of Home Assistant App doesn't help...

**Comment by Idan37S** [comment]
Happens to me as well, even in my Floorplan view.
A refresh usually works, sometimes it takes serval tries.
It would be great if someone would be able to solve it.

**Comment by FUsIon80** [comment]
No problem on Windows Browser... Clearing Cache never Works under Android -.-

**Comment by cmariegaard** [comment]
This issue is also mentioned in #707 
DD3.x Issue is persistent HA Companion App after latest HA/OS updates.
The quickfix to clear cache only works one time, after closing Companion App and reopen the issue is back.
No problem in DD3.x in PC browser

**Comment by dwainscheeren** [comment]
The solution on Android is only to re-install the app.

**Comment by FUsIon80** [comment]
> The solution on Android is only to re-install the app.

Thx, work for me ^^

**Comment by mrVoltrix** [comment]
Hi, 

I have the same problem here on my both tablets, 
one is using the companion app and one is using the WallPanel app to acces HA. 
I tried with both tablets to clear cache, delete data and also tried to complete remove the apps and install them again.
But all the time I got the "Custom element doesn't exist: " message again after a while. 
Is there some long term solution?

**Comment by Geo-Ron** [comment]
> The solution on Android is only to re-install the app.

Not reinstall. Clearing all data and logging in again files it.

**Comment by rosicenko** [comment]
> > The solution on Android is only to re-install the app.
> 
> Not reinstall. Clearing all data and logging in again files it.

not working after 2023.9 update

**Comment by MakkeLeon2** [comment]
right click open in new tab works well.
Strange but works for me.
