### ISSUE TITLE
Partial weather status not showing up in home

### ISSUE THREAD

**Issue by lino-silva** [dwainscheeren/dwains-lovelace-dashboard#706]
For a few weeks now, some of the weather's status shows empty. Screenshot attached. 

Home Assistant 2023.5.2
Supervisor 2023.04.1
Operating System 10.1
Frontend 20230503.3 - latest 

DD Version 3.4.3 

![image](https://github.com/dwainscheeren/dwains-lovelace-dashboard/assets/1109759/154014e1-b314-407e-8f24-00b2c122d3b5)

**Comment by metaiiica** [comment]
is a Part of Issue #702

**Comment by lino-silva** [comment]
Thanks for the heads up, gonna close this one.
