### ISSUE TITLE
Custom popups not working

### ISSUE THREAD

**Issue by marcusboon** [dwainscheeren/dwains-lovelace-dashboard#712]
Configuring individual popups or even trying to replace entire entity types with a pop up blueprint yields the default pop up behaviour regardless of browser or app.

Steps to reproduce:
1. In a dashboard, edit the pop up setting.
2. Pick a Lovelace card (e.g. webrtc-camera card for a camera entity)

Expected:
On click, the camera entity shows the configured webrtc-camera card.

Actual:
On click, the camera entity shows the default entity more info card instead of the configured webrtc-camera card even though reconfiguring the pop up settings for that camera entity shows the correct webrtc-camera config.

Alternatively:
1. Create a webrtc-camera replace card bluprint
2. In the entities dashboard, replace the pop up card with preconfigured webrtc-camera blueprint

Expected:
All camera entities now inherit the webrtc-camera pop up behaviour

Actual:
All camera entities still use the default camera entity more-info behaviour.

_Originally posted by @marcusboon in https://github.com/dwainscheeren/dwains-lovelace-dashboard/issues/708#issuecomment-1565221982_

**Comment by Bruskey** [comment]
I am also experiencing this issue. Every time i try to set a custom pop up card, the browser looks like it refreshes and then afterwards the default pop up shows, but when i click through to see the custom pop up that i created it showing in the settings correctly

**Comment by Bruskey** [comment]
Is nobody else having this issue?

**Comment by Miguelin96** [comment]
I also have the same problem

**Comment by flaviohome** [comment]
Same problem here.

**Comment by JPerfontan** [comment]
Same problem!! :-(

**Comment by marcusboon** [comment]
This is now resolved with the latest version of DD.
