### ISSUE TITLE
Dwain, are you ok?

### ISSUE THREAD

**Issue by lino-silva** [dwainscheeren/dwains-lovelace-dashboard#723]
Just checking up on you - project has been stale for around four months, after a quite a bit of active development.

**Comment by xyeoda** [comment]
still no news from him im guessing?

**Comment by dwainscheeren** [comment]
Yes I'm okay :). I'm working a lot on my other HA project with custom made ESPHome products: https://smarthomeshop.io which will be launched next week. I'm also pretty active on my own Discord server: https://discord.gg/7yt64uX and I'm working on a complete rewriten Dwains Dashboard V4.0

**Comment by lino-silva** [comment]
Ah dude, good to hear! I was genuinely concerned.
