### ISSUE TITLE
type: custom:homepage-card doesn't exist error

### ISSUE THREAD

**Issue by MrNeuronix** [dwainscheeren/dwains-lovelace-dashboard#735]
Hi!
Installed today your dashboard, but it's not starting up. Error is:
```
Custom element doesn't exist: homepage-card
type: custom:homepage-card
```
Tried CTRL+F5, clear cache and so on, but without success
Ha version - latest 2023.10.1

**Comment by dwainscheeren** [comment]
#726

**Comment by Markeydoo** [comment]
Im still running into the same issue.
Is there a fix?
I have checked #726 and still have the issue on Windows 11 pro with Opera as my browser.

**Comment by stevenvanultima** [comment]
I use the actually Mac OS with actually Firefox Browser ;-)
