### ISSUE TITLE
Custom element doesn't exist

### ISSUE THREAD

**Issue by Markeydoo** [dwainscheeren/dwains-lovelace-dashboard#737]
Still having the issue with "Custom element doesn't exist"
I have deinstalled and reinstalled per the document.
I had V2 installed and removed it that installed V3.5 per the docs.
I have not converted V2 to V3 as I want to test and see if I was still having the issue of "Custom element doesn't exist" which is still happening.
I am using it in a Windows 11 pro machine. Tried with Chrome, Firefox and Opera with the same results.
If I close the browsers window, clear history, and reopen the the browser it works without error.
Once I close the window or refresh the window the error comes back.
Help needed please
Thanks
Mark
![image](https://github.com/dwainscheeren/dwains-lovelace-dashboard/assets/86135013/ae23ab5f-1c2f-4fb9-919f-d9ed3000a737)

**Comment by marcosanson** [comment]
Same error here. I'm on docker installation on a macbook m1.

**Comment by xKronyx** [comment]
upgrade to beta 3.5.0

**Comment by Markeydoo** [comment]
I did

**Comment by dwainscheeren** [comment]
This is fixed in 3.5.0
