### ISSUE TITLE
Main menu no longer reachable 

### ISSUE THREAD

**Issue by ghost** [dwainscheeren/dwains-lovelace-dashboard#747]
Hi!

1st of all I have to say that your dashboard is brilliant. We have mobiles, pads and pc's in our family and now I don't have to maintain 3 different dashboards.

The latest update brought a problem, though.

The menu has moved to bottom of screen and the 1st item from the left, that beings you to the main HA menu with settings and such does nothing atm. If you have Dwains dashboard as default you are locked in to the dash and can not access anything else. This is not very practical if you are set to admin and needs to jump around a lot while configuring.

Nice feature, though, to have for non admin users that you really want to lock inside the dashboard.

Did not find any option to set to get out of this other than setting something else as default but it would be nice if it had one. Main menu reachable for admins only. Have to downgrade for the time being so I can work with configs.

**Comment by u20p17** [comment]
i have the same issue - with v3.4.3 it was working perfectly 👍

**Comment by dwainscheeren** [comment]
This is already discussed here #731  and fixed in beta 3.6.0

**Comment by ghost** [comment]
Sorry!
I just hate github. Never seem to find anything here.
