### ISSUE TITLE
Blueprint not installed

### ISSUE THREAD

**Issue by JacTech** [dwainscheeren/dwains-lovelace-dashboard#755]
After pasting the blueprint and htting install blueprint the popup says successfuly saved but in the installed blueprint tab it says (not installed) 

![image](https://github.com/dwainscheeren/dwains-lovelace-dashboard/assets/90476032/210a28e6-43e6-4948-9195-b3341cdd2e37)

**Comment by LordNex** [comment]
Your probably missing the component that the blueprint requires. Try looking in HACS for that mushroom card listedneithbthe red X. Once you find and install that you should be able to use the blueprint. 

Honestly if I were you I would go ahead and download the entire mushroom set. They are much nicer cards than the standard ones and allow for a lot of control
