### ISSUE TITLE
Entity picker not working in blueprints

### ISSUE THREAD

**Issue by backisen** [dwainscheeren/dwains-lovelace-dashboard#767]
I've tried a couple of blueprints but entity picker doesn't seem to work. This is how it looks for ther persons page blueprint:

![image](https://github.com/dwainscheeren/dwains-lovelace-dashboard/assets/43696398/ccb6d81f-87f4-4e87-9be2-bd912f28ecc1)

Running the latest version of DD, HA and all needed cards from HACS.

**Comment by LordNex** [comment]
Still happens for me as well. Be going on for some time now

**Comment by dwainscheeren** [comment]
This will be fixed in version 3.7 😄 

Please consider a donation for my work.
https://www.buymeacoffee.com/FAkYvrx
or
https://www.paypal.me/dwainscheeren
or 
https://github.com/sponsors/dwainscheeren
Thank you in advance ❤️

**Comment by bubez81** [comment]
same problem with 3.7

**Comment by micdesa** [comment]
same problem with 3.7.1
Hi, do you have any news about?

**Comment by slikone27** [comment]
this is still broken.  anyone manage to fix this? @dwainscheeren
