### ISSUE TITLE
Bug: popup

### ISSUE THREAD

**Issue by cyberfly79** [dwainscheeren/dwains-lovelace-dashboard#768]
Hi,
I discovered a bug.

I set up a popup card for an entity. After the popup appears, the menus on the left side of the system do not work (map, logbook, energy dahboard, etc...) If I look at another area on the DD, it works again.
The popup also appears in the list of helpers.

Edit: And now I came across that on IOS the popup set for the entity in the app does not work, instead there is the default appearance.

 Core 2023.12.4 
 DD 3.6.0

**Comment by dwainscheeren** [comment]
This will be fixed in version 3.7 😄 

Please consider a donation for my work.
https://www.buymeacoffee.com/FAkYvrx
or
https://www.paypal.me/dwainscheeren
or 
https://github.com/sponsors/dwainscheeren
Thank you in advance ❤️
