### ISSUE TITLE
How can I support Chinese and which file needs to be modified?

### ISSUE THREAD

**Issue by bbluvgg** [dwainscheeren/dwains-lovelace-dashboard#775]
I knew it didn't support displaying Chinese, and I tried to find his translated files but found nothing.
\config\custom_components\dwains_dashboard\translations, there are only two .json files in the directory.
There are no related phrases for "dwains dashboard".
So how do I get it to support displaying Chinese?

**Comment by dwainscheeren** [comment]
https://github.com/dwainscheeren/dwains-lovelace-dashboard/blob/3.0/custom_components/dwains_dashboard/js/src/translations.js :) Make a PR here.
