### ISSUE TITLE
Restore default 

### ISSUE THREAD

**Issue by Belle2404** [dwainscheeren/dwains-lovelace-dashboard#777]
How can I restore to default?
I did something and now I can't see and add nothing.
![Screenshot_2024-01-30-14-07-21-850_com android chrome](https://github.com/dwainscheeren/dwains-lovelace-dashboard/assets/157913415/d8cad679-ee93-4b82-86fc-d2683a7f217d)

**Comment by dwainscheeren** [comment]
Please clear your cache
