### ISSUE TITLE
Error log

### ISSUE THREAD

**Issue by Rotif** [dwainscheeren/dwains-lovelace-dashboard#779]
Logger: homeassistant.helpers.frame
Source: helpers/frame.py:133
First occurred: 22:09:07 (3 occurrences)
Last logged: 22:10:29

    Detected that custom integration 'dwains_dashboard' uses deprecated 'SafeLineLoader' instead of 'PythonSafeLoader', which will stop working in HA Core 2024.6, at custom_components/dwains_dashboard/process_yaml.py, line 69: loader.SafeLineLoader.add_constructor("!include", _include_yaml), please create a bug report at https://github.com/dwainscheeren/dwains-lovelace-dashboard/issues
    Detected that custom integration 'dwains_dashboard' uses deprecated 'SafeLineLoader' instead of 'PythonSafeLoader', which will stop working in HA Core 2024.6, at custom_components/dwains_dashboard/process_yaml.py, line 46: return loader.yaml.load(config_file, Loader=lambda stream: loader.SafeLineLoader(stream, secrets)) or OrderedDict(), please report it to the author of the 'dwains_dashboard' custom integration
    Detected that custom integration 'dwains_dashboard' uses deprecated 'SafeLineLoader' instead of 'PythonSafeLoader', which will stop working in HA Core 2024.6, at custom_components/dwains_dashboard/process_yaml.py, line 43: return loader.yaml.load(stream, Loader=lambda _stream: loader.SafeLineLoader(_stream, secrets)) or OrderedDict(), please report it to the author of the 'dwains_dashboard' custom integration

**Comment by HenkCenk** [comment]
Hey Rotif,
this could help: [https://github.com/dwainscheeren/dwains-lovelace-dashboard/pull/771]

**Comment by dwainscheeren** [comment]
This will be fixed in version 3.7 😄 

Please consider a donation for my work.
https://www.buymeacoffee.com/FAkYvrx
or
https://www.paypal.me/dwainscheeren
or 
https://github.com/sponsors/dwainscheeren
Thank you in advance ❤️
