### ISSUE TITLE
[FR] Allow notifications to work with variables

### ISSUE THREAD

**Issue by Tosko4** [dwainscheeren/dwains-lovelace-dashboard#78]
Hi there,

Please ensure that notifications can start to show variables from data_template

![C34235DF-8D47-409F-A46C-587B527598C5](https://user-images.githubusercontent.com/1294707/78970712-43774200-7b0a-11ea-9bce-bd3ba2441c56.jpeg)

**Comment by dwainscheeren** [comment]
This is fixed in 2.0
