### ISSUE TITLE
Dashboard Installation Error

### ISSUE THREAD

**Issue by ZulKMohamed** [dwainscheeren/dwains-lovelace-dashboard#783]
Hello Dwain,

I am a novice trying to use your  dashboard.  I get a red error message similar to the one shown in your Installation instructions. The Error Log shows the following: 

 Logger: homeassistant.helpers.frame
Source: helpers/frame.py:133
First occurred: 20:25:28 (3 occurrences)
Last logged: 20:25:31

Detected that custom integration 'dwains_dashboard' uses deprecated 'SafeLineLoader' instead of 'PythonSafeLoader', which will stop working in HA Core 2024.6, at custom_components/dwains_dashboard/process_yaml.py, line 69: loader.SafeLineLoader.add_constructor("!include", _include_yaml), please create a bug report at https://github.com/dwainscheeren/dwains-lovelace-dashboard/issues

Detected that custom integration 'dwains_dashboard' uses deprecated 'SafeLineLoader' instead of 'PythonSafeLoader', which will stop working in HA Core 2024.6, at custom_components/dwains_dashboard/process_yaml.py, line 46: return loader.yaml.load(config_file, Loader=lambda stream: loader.SafeLineLoader(stream, secrets)) or OrderedDict(), please report it to the author of the 'dwains_dashboard' custom integration

Detected that custom integration 'dwains_dashboard' uses deprecated 'SafeLineLoader' instead of 'PythonSafeLoader', which will stop working in HA Core 2024.6, at custom_components/dwains_dashboard/process_yaml.py, line 43: return loader.yaml.load(stream, Loader=lambda _stream: loader.SafeLineLoader(_stream, secrets)) or OrderedDict(),  please report it to the author of the 'dwains_dashboard' custom integration

Please advise the way forward.

Thank you 

Zulfikar

**Comment by dwainscheeren** [comment]
This will be fixed in version 3.7 😄 

Please consider a donation for my work.
https://www.buymeacoffee.com/FAkYvrx
or
https://www.paypal.me/dwainscheeren
or 
https://github.com/sponsors/dwainscheeren
Thank you in advance ❤️
