### ISSUE TITLE
no icons on cards

### ISSUE THREAD

**Issue by kris-tant** [dwainscheeren/dwains-lovelace-dashboard#784]
It seems that the icons in my entity cards are not shown (in none of my areas). Any idea how this can be corrected? 
![image](https://github.com/dwainscheeren/dwains-lovelace-dashboard/assets/124056912/e2cc136f-20d4-4fad-a067-6e5f33ddbeef)

**Comment by FSHelgeland** [comment]
See in PR

**Comment by kris-tant** [comment]
Not clear what you mean with PR, @FSHelgeland could you clarify? Thanks

**Comment by kris-tant** [comment]
My icons are visible in my general dashboard, but not in dwains dashboard.
![image](https://github.com/dwainscheeren/dwains-lovelace-dashboard/assets/124056912/6dd15f86-77a3-42d6-aead-93b432aa6d22)

**Comment by FSHelgeland** [comment]
With PR I ment Pull Requests

https://github.com/dwainscheeren/dwains-lovelace-dashboard/pull/782

But what you need to do is the following: 

From this git: https://github.com/cermakjn/dwains-lovelace-dashboard
You need to download only the Dwains-dashboard.js file from his GitHub. Then delete your existing one in custom_components/dwains_dashboard/js/ and replace with the one you downloaded

I used file editor to upload the new one. Then if you have a file in js called dwains-dashboard.js.gz you need to rename it to dwains.dashboard.js.gz_old.

Then restart Home Assistant, clear cache in browsers. If you have any iOS-devices you will need to go into the companion app and from there clear frontend cache. After that reload the dasboard, and the icons should be there.

**Comment by kris-tant** [comment]
Thank you @FSHelgeland for the very clear guidelines. Unfortunately this did not work for me, although all steps were followed - including multiple restarts and cache clearances.

**Comment by kris-tant** [comment]
... and after a few hours, the icons are included. Thanks @FSHelgeland !
