### ISSUE TITLE
Issue with Ecovacs Deebot Advanced UI in Dwains Dashboard

### ISSUE THREAD

**Issue by Chakkaaa** [dwainscheeren/dwains-lovelace-dashboard#786]
Hi Dwain and Community,

I have an issue integrating the Advanced UI for Ecovacs Deebot into the Dwains Dashboard.

The Deebot Card needs the Button-Card and the Vacuum-Card integrations to work. On my default Overview the Card works great.
But when I try to integrate it into this Dashboard it shows errors. I am not a pro when it comes to scripting but I am assuming since there is that one part to add some code to the RAW-Configuration editor for ecovacs deebot to work that this part is no longer accessed by Dwains Dashboard.

How can I workaround this?

![image](https://github.com/dwainscheeren/dwains-lovelace-dashboard/assets/128637847/68970b45-37ba-449e-b1ca-b72301450b67)

Any hint would be appreciated

Regards Sebastian

**Comment by dwainscheeren** [comment]
You didn't install the right button-card templates. This is not DD related.

**Comment by Chakkaaa** [comment]
Hi Dwain,

it's the only available button-card template I installed via HACS. Any idea what could be missing? I also deleted the Cache and tried several other things I found on the Internet without success.

This Dashboard is really great and I would like to use it as my default one but its useless if I can't get my vacuum to work.

Regards
Sebastian

________________________________
