### ISSUE TITLE
icon missing

### ISSUE THREAD

**Issue by ithaqua974** [dwainscheeren/dwains-lovelace-dashboard#788]
hello, I love Dwains dashboard but in the stock configuration, none of the icons is displayed
![image](https://github.com/dwainscheeren/dwains-lovelace-dashboard/assets/25313988/c732a388-52ad-4e46-8edb-054f6476a2d3)
I need some help I'm a newbie in HA
For Plex and the first light, I change them with a blueprint, but some of my devices are too specific and don't have a blueprint that fits them
Thank you

**Comment by cyrus104** [comment]
Same

**Comment by jpalenz77** [comment]
same here!

**Comment by dnewell73** [comment]
I just installed the dashboard, and have the same problem.   No icons.

**Comment by klimofey** [comment]
same

**Comment by gbomacfly** [comment]
same

**Comment by ajbastien** [comment]
same

**Comment by dwainscheeren** [comment]
This will be fixed in version 3.7 😄 

Please consider a donation for my work.
https://www.buymeacoffee.com/FAkYvrx
or
https://www.paypal.me/dwainscheeren
or 
https://github.com/sponsors/dwainscheeren
Thank you in advance ❤️
