### ISSUE TITLE
HA 2024.3 - Some Icons missing and Mobile App freezes 

### ISSUE THREAD

**Issue by MuppetRus** [dwainscheeren/dwains-lovelace-dashboard#790]
I decided to take the plunge and upgrade to HA 2024.3 and renamed dwains-dashboard.js to dwains-dashboard.js.old then uploaded the recommended the new dwains-dashboard.js and whilst it fixed most icons.........I can fix the ones that are still blank without much effort. 

The bigger pain is now the HA app on IOS freezes after using for a couple of mins, whilst you can close the app and restart it again it freezes after navigating a few different areas.

If anybody has any ideas that would be appreciated.

So far the only fix is to downgrade back to 2024.1.6 which fixes all the issues

**Comment by cyrus104** [comment]
Same here

**Comment by jpalenz77** [comment]
same same

**Comment by three1bro** [comment]
same here

**Comment by klimofey** [comment]
same

**Comment by dwainscheeren** [comment]
This will be fixed in version 3.7 😄 

Please consider a donation for my work.
https://www.buymeacoffee.com/FAkYvrx
or
https://www.paypal.me/dwainscheeren
or 
https://github.com/sponsors/dwainscheeren
Thank you in advance ❤️
