### ISSUE TITLE
having trouble installing dashboard

### ISSUE THREAD

**Issue by Renier30** [dwainscheeren/dwains-lovelace-dashboard#793]
Logger: homeassistant.helpers.frame
Source: helpers/frame.py:156
First occurred: 2:08:10 AM (2 occurrences)
Last logged: 2:08:19 AM

Detected that custom integration 'dwains_dashboard' accesses hass.components.websocket_api. This is deprecated and will stop working in Home Assistant 2024.9, it should be updated to import functions used from websocket_api directly at custom_components/dwains_dashboard/notifications.py, line 220: hass.components.websocket_api.async_register_command(websocket_get_notifications), please create a bug report at https://github.com/dwainscheeren/dwains-lovelace-dashboard/issues
Detected that custom integration 'hacs' accesses hass.components.frontend. This is deprecated and will stop working in Home Assistant 2024.9, it should be updated to import functions used from frontend directly at custom_components/hacs/frontend.py, line 68: hass.components.frontend.async_register_built_in_panel(, please create a bug report at https://github.com/hacs/integration/issues

**Comment by dwainscheeren** [comment]
This are notices, and no errors. Already got it working?
