### ISSUE TITLE
Detected that custom integration 'dwains_dashboard' uses deprecated 'SafeLineLoader' instead of 'PythonSafeLoader', which will stop 

### ISSUE THREAD

**Issue by DivaInACan** [dwainscheeren/dwains-lovelace-dashboard#794]
Logger: homeassistant.helpers.frame
Source: helpers/frame.py:156
First occurred: 1:33:30 PM (5 occurrences)
Last logged: 1:33:47 PM

Detected that custom integration 'dwains_dashboard' uses deprecated 'SafeLineLoader' instead of 'PythonSafeLoader', which will stop working in HA Core 2024.6, at custom_components/dwains_dashboard/process_yaml.py, line 69: loader.SafeLineLoader.add_constructor("!include", _include_yaml), please create a bug report at https://github.com/dwainscheeren/dwains-lovelace-dashboard/issues
Detected that custom integration 'dwains_dashboard' accesses hass.components.websocket_api. This is deprecated and will stop working in Home Assistant 2024.9, it should be updated to import functions used from websocket_api directly at custom_components/dwains_dashboard/notifications.py, line 220: hass.components.websocket_api.async_register_command(websocket_get_notifications), please create a bug report at https://github.com/dwainscheeren/dwains-lovelace-dashboard/issues
Detected that custom integration 'dwains_dashboard' uses deprecated 'SafeLineLoader' instead of 'PythonSafeLoader', which will stop working in HA Core 2024.6, at custom_components/dwains_dashboard/process_yaml.py, line 46: return loader.yaml.load(config_file, Loader=lambda stream: loader.SafeLineLoader(stream, secrets)) or OrderedDict(), please report it to the author of the 'dwains_dashboard' custom integration
Detected that custom integration 'dwains_dashboard' uses deprecated 'SafeLineLoader' instead of 'PythonSafeLoader', which will stop working in HA Core 2024.6, at custom_components/dwains_dashboard/process_yaml.py, line 43: return loader.yaml.load(stream, Loader=lambda _stream: loader.SafeLineLoader(_stream, secrets)) or OrderedDict(), please report it to the author of the 'dwains_dashboard' custom integration
Detected that custom integration 'hacs' accesses hass.components.frontend. This is deprecated and will stop working in Home Assistant 2024.9, it should be updated to import functions used from frontend directly at custom_components/hacs/frontend.py, line 68: hass.components.frontend.async_register_built_in_panel(, please create a bug report at https://github.com/hacs/integration/issues

**Comment by dwainscheeren** [comment]
This will be fixed in version 3.7 😄 

Please consider a donation for my work.
https://www.buymeacoffee.com/FAkYvrx
or
https://www.paypal.me/dwainscheeren
or 
https://github.com/sponsors/dwainscheeren
Thank you in advance ❤️
