### ISSUE TITLE
Defunct in 2024.4.0

### ISSUE THREAD

**Issue by joehun** [dwainscheeren/dwains-lovelace-dashboard#798]
Browser:

Dwains-Dashboard did not start in HA 2024.4.0. Error message: 
 
![Screenshot 2024-04-03 233315](https://github.com/dwainscheeren/dwains-lovelace-dashboard/assets/9888514/a0adb053-4024-443f-8edf-25f8d99add21)

I have tested V3.6.0 and V3.7.0b7

**Comment by casascha** [comment]
Same issue today ...

**Comment by dwainscheeren** [comment]
Reset the browser cache.
