### ISSUE TITLE
Is this a bug? Latest Version

### ISSUE THREAD

**Issue by newbyp** [dwainscheeren/dwains-lovelace-dashboard#801]
I recently started using the dashboard and have noticed the latest version sensor (sensor.dwains_dashboard_latest_version) shows the version as 3.5 yet the latest version and the one I believe I downloaded was v3.6. There is no update offered in HACS. Is this a bug, how can I get HACS to offer me v3.6 and will it update the sensor?

**Comment by tgsparky** [comment]
I noticed the same thing. Mentions it was updated 3 days ago but says its 3.5V

**Comment by dwainscheeren** [comment]
Oops, fixed :) Please check in 24 hours if the version is 3.7 now in the sensor. Post it here please

**Comment by newbyp** [comment]
Thank you it is now working and showing 3.7.0
