### ISSUE TITLE
[FR] A way to rename the default Dwain's Theme dashboard

### ISSUE THREAD

**Issue by dkmcgowan** [dwainscheeren/dwains-lovelace-dashboard#94]
Since I have to sometimes pull the side bar up, It would nice to be able to rename it to Home or Overview.  I think Overview would break things since even if you delete the default lovelace yaml, it still shows up in Config, but not in the left bar.  I would like to name this Home

**Comment by Tosko4** [comment]
take a look at this: https://github.com/dwainscheeren/lovelace-dwains-theme/blob/5e762e5bcdd1b4347d0b766b8941c36fc76acfa4/packages/dwains-theme/dwains_theme_configuration.yaml#L8

**Comment by davidkmcgowan** [comment]
That worked and changed it, but I wonder if that would constantly get overwritten with every new release

**Comment by Tosko4** [comment]
well, if you blindly copy-paste it then yes it would overwrite it. Either make sure you change it back after or during copy, skip this part, and only copy-paste other changes of this file.

**Comment by DamianosS** [comment]
> well, if you blindly copy-paste it then yes it would overwrite it. Either make sure you change it back after or during copy, skip this part, and only copy-paste other changes of this file.

Not a solution :-) Long-term the FR is valid.

**Comment by dwainscheeren** [comment]
This is fixed in 1.5 :D

You can set a own name and icon for my dashboard.

![](http://puu.sh/GEklZ/e7f797c373.png)

![](http://puu.sh/GEknf/9eb320ee5f.png)
